//Verilog block level netlist file for netlist_TH
//Generated by UMN for ALIGN project 

module track_and_hold_single_ended ( CN, CP, IN, ON, VCM, VDD, VSS );
Cap_30f_1x3 CC0 ( .MINUS(VCM), .PLUS(OP) ); 
Cap_30f_1x3 CC1 ( .MINUS(VCM), .PLUS(OP) ); 
Cap_30f_1x3 CC2 ( .MINUS(VCM), .PLUS(OP) ); 
Cap_30f_1x3 CC3 ( .MINUS(VCM), .PLUS(OP) ); 
Switch_NMOS_16x8 MN0 ( .D(OP), .G(CP), .S(IP) ); 
Switch_PMOS_16x8 MN1 ( .D(IP), .G(CN), .S(OP) ); 

endmodule

module top ( CN, CP, IN, IP, ON, OP, VCM, VDD, VSS );
track_and_hold_single_ended I0( CN, CP, IN, ON, VCM, VDD, VSS );
track_and_hold_single_ended I1( CN, CP, IP, OP, VCM, VDD, VSS );

endmodule


// End HDL models
// Global nets module
`celldefine
module cds_globals;

supply0 VDD;
supply1 VSS;

endmodule
`endcelldefine
