//Verilog block level netlist file for ota_asap7
//Generated by UMN for ALIGN project 


module ota_asap7 ( Ids, VSS, Input2, VDD, Input1, VOUT ); 
input Ids, VSS, Input2, VDD, Input1, VOUT;

Switch_NMOS_n12_X4_Y4 m0 ( .D(net8), .G(Input2), .S(net10), .BG(VSS) ); 
DCL_PMOS_n12_X5_Y2 m1 ( .D(net8), .S(VDD), .BG(VDD) ); 
Switch_PMOS_n12_X5_Y2 m2 ( .D(VOUT), .G(net8), .S(VDD), .BG(VDD) ); 
Switch_NMOS_n12_X4_Y4 m3 ( .D(VOUT), .G(Input1), .S(net10), .BG(VSS) ); 
Switch_NMOS_n12_X2_Y2 m4 ( .D(net10), .G(Ids), .S(VSS), .BG(VSS) ); 
DCL_NMOS_n12_X1_Y1 m5 ( .D(Ids), .S(VSS), .BG(VSS) ); 

endmodule
