//Verilog block level netlist file for BUFFER_VREFP_FINAL2
//Generated by UMN for ALIGN project 


module INV_LVT ( SN, SP, i, zn ); 
input SN, SP, i, zn;

Switch_NMOS_n12_X1_Y1 xm0 ( .B(SN), .D(zn), .G(i), .S(SN) ); 
Switch_PMOS_n12_X1_Y1 xm1 ( .B(SP), .D(zn), .G(i), .S(SP) ); 

endmodule

module stage2_inv ( G1, G2, SN, SP ); 
input G1, G2, SN, SP;

INV_LVT MM0_MM2 ( .zn(G1), .i(D), .SN(SN), .SP(SP) ); 
INV_LVT MM1_MM3 ( .zn(D), .i(G2), .SN(SN), .SP(SP) ); 

endmodule

module LSB_NMOS_2 ( B, DA, DB, DC, SA, SB, SC ); 
input B, DA, DB, DC, SA, SB, SC;

Switch_NMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(SC) ); 
LS_NMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .SA(SA), .DB(DB), .SB(SB) ); 

endmodule

module LSB_PMOS_2 ( B, DA, DB, DC, SA, SB, SC ); 
input B, DA, DB, DC, SA, SB, SC;

Switch_PMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(SC) ); 
LS_PMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .SA(SA), .DB(DB), .SB(SB) ); 

endmodule

module BUFFER_VREFP_FINAL2 ( ibias, sw<0>, sw<1>, sw<2>, vref, vrefp ); 
input ibias, sw<0>, sw<1>, sw<2>, vref, vrefp;

Switch_PMOS_n12_X1_Y1 xm58 ( .B(vdd), .D(vrefp), .G(net459), .S(net0129) ); 
Switch_PMOS_n12_X1_Y1 xm15 ( .B(vdd), .D(vfb), .G(net450), .S(net0115) ); 
Switch_PMOS_n12_X1_Y1 xm28 ( .B(vdd), .D(vrefp), .G(net459), .S(net0127) ); 
Dcap_PMOS_n12_X1_Y1 xm106 ( .B(vdd), .S(vdd), .G(net431) ); 
Switch_PMOS_n12_X1_Y1 xm33 ( .B(vdd), .D(vrefp), .G(net459), .S(net0113) ); 
Switch_PMOS_n12_X1_Y1 xm34 ( .B(vdd), .D(vrefp), .G(net459), .S(net0135) ); 
Switch_PMOS_n12_X1_Y1 xm35 ( .B(vdd), .D(net0134), .G(net431), .S(vrefp) ); 
Switch_NMOS_n12_X1_Y1 xm55 ( .B(gnd), .D(net468), .G(swn2), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm20 ( .B(gnd), .D(net469), .G(swn1), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm19 ( .B(gnd), .D(net470), .G(swn0), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm18 ( .B(gnd), .D(net463), .G(vdd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm17 ( .B(gnd), .D(net427), .G(vdd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm9 ( .B(gnd), .D(net466), .G(vdd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm2 ( .B(gnd), .D(net465), .G(vdd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm0 ( .B(gnd), .D(net464), .G(vdd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm3 ( .B(gnd), .D(net418), .G(ibias), .S(net466) ); 
Switch_NMOS_n12_X1_Y1 xm5 ( .B(gnd), .D(net411), .G(ibias), .S(net465) ); 
Switch_NMOS_n12_X1_Y1 xm21 ( .B(net427), .D(net431), .G(ibias), .S(net427) ); 
Switch_NMOS_n12_X1_Y1 xm30 ( .B(gnd), .D(net459), .G(ibias), .S(net463) ); 
Switch_NMOS_n12_X1_Y1 xm36 ( .B(gnd), .D(net0134), .G(ibias), .S(net469) ); 
Switch_PMOS_n12_X1_Y1 xm46 ( .B(vdd), .D(net0135), .G(swp1), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm45 ( .B(vdd), .D(net0113), .G(swp0), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm44 ( .B(vdd), .D(net0127), .G(gnd), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm56 ( .B(vdd), .D(net0129), .G(swp2), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm42 ( .B(vdd), .D(net0115), .G(gnd), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm37 ( .B(vdd), .D(net0121), .G(gnd), .S(vdd) ); 
stage2_inv xm50_xm48_xm49_xm47 ( .G1(swn0), .SN(gnd), .G2(sw<0>), .SP(vdd) ); 
stage2_inv xm54_xm51_xm53_xm52 ( .G1(swn1), .SN(gnd), .G2(sw<1>), .SP(vdd) ); 
stage2_inv xm62_xm59_xm61_xm60 ( .G1(swn2), .SN(gnd), .G2(sw<2>), .SP(vdd) ); 
CMC_NMOS_S_n12_X1_Y1 xm7_xm16 ( .B(gnd), .DA(net467), .G(vdd), .S(gnd), .DB(net462) ); 
CMC_PMOS_S_n12_X1_Y1 xm40_xm39 ( .B(vdd), .DA(net0119), .G(gnd), .S(vdd), .DB(net0114) ); 
CMC_PMOS_S_n12_X1_Y1 xm38_xm41 ( .B(vdd), .DA(net0128), .G(gnd), .S(vdd), .DB(net0124) ); 
CMC_PMOS_S_n12_X1_Y1 xm29_xm32 ( .B(vdd), .DA(net459), .G(net431), .S(vrefp), .DB(net0132) ); 
LSB_NMOS_2 xm4_xm31_xm57 ( .B(gnd), .DA(ibias), .SA(net464), .DB(net0132), .SB(net470), .DC(net0125), .SC(net468) ); 
LSB_PMOS_2 xm22_xm13_xm14 ( .B(vdd), .DA(net411), .SA(net0121), .DB(net450), .SB(net0137), .DC(net412), .SC(net0122) ); 
LS_NMOS_n12_X1_Y1 xm1_xm6 ( .B(gnd), .DA(net412), .SA(net467), .DB(net450), .SB(net462) ); 
LS_PMOS_n12_X1_Y1 xm23_xm24 ( .B(vdd), .DA(net423), .SA(net0114), .DB(net0137), .SB(net0124) ); 
LS_PMOS_n12_X1_Y1 xm25_xm26 ( .B(vdd), .DA(net417), .SA(net0119), .DB(net0122), .SB(net0128) ); 
LS_PMOS_n12_X1_Y1 xm27_xm43 ( .B(vdd), .DA(net431), .SA(vfb), .DB(net0125), .SB(vrefp) ); 
DP_NMOS_n12_X1_Y1 xm12_xm10 ( .B(gnd), .DA(net450), .GA(vref), .S(net418), .DB(net412), .GB(vfb) ); 
DP_NMOS_n12_X1_Y1 xm8_xm11 ( .B(gnd), .DA(net423), .GA(vfb), .S(net418), .DB(net417), .GB(vref) ); 

endmodule

`celldefine
module global_power;
supply0 gnd;
supply1 vdd;
endmodule
`endcelldefine
