//Verilog block level netlist file for linear_equalizer
//Generated by UMN for ALIGN project 


module CMB_NMOS_2 ( B, DA, DB, DC, S ); 
input B, DA, DB, DC, S;

Switch_NMOS_n12_X3_Y2 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 
SCM_NMOS_n12_X3_Y2 M0_M1 ( .B(B), .DA(DA), .S(S), .DB(DB) ); 

endmodule

module linear_equalizer ( s0_ctle, s3_ctle, vin1, vin2, vmirror_ctle, vout_ctle1, vout_ctle2 ); 
input s0_ctle, s3_ctle, vin1, vin2, vmirror_ctle, vout_ctle1, vout_ctle2;

Switch_NMOS_n12_X2_Y2 xI0|MN0 ( .B(b), .D(vout_ctle2), .G(vin2), .S(net8) ); 
Switch_NMOS_n12_X2_Y2 xI1|MN0 ( .B(b), .D(vout_ctle1), .G(vin1), .S(net5) ); 
Res_800 R1 ( .PLUS(vout_ctle2), .MINUS(vps) ); 
Res_800 R0 ( .PLUS(vout_ctle1), .MINUS(vps) ); 
Cap_24f C4 ( .PLUS(net021), .MINUS(net8) ); 
Cap_24f C3 ( .PLUS(net022), .MINUS(net5) ); 
Res_100 R4 ( .PLUS(net016), .MINUS(net5) ); 
Res_100 R3 ( .PLUS(net015), .MINUS(net8) ); 
Switch_NMOS_n12_X2_Y2 MN9 ( .B(vgnd), .D(net021), .G(s3_ctle), .S(net022) ); 
Switch_NMOS_n12_X2_Y2 MN6 ( .B(vgnd), .D(net015), .G(s0_ctle), .S(net016) ); 
CMB_NMOS_2 xI4|MN0_xI2|MN0_xI3|MN0 ( .B(b), .DA(vmirror_ctle), .S(vgnd), .DB(net8), .DC(net5) ); 

endmodule

`celldefine
module global_power;
supply0 vgnd;
supply1 vps;
endmodule
`endcelldefine
