//Verilog block level netlist file for high_speed_comparator
//Generated by UMN for ALIGN project 


module high_speed_comparator ( clk, v_in, vip, von, vop ); 
input clk, v_in, vip, von, vop;

Switch_PMOS_nfin12_n12_X1_Y1 mmp5 ( .D(vy), .G(clk), .S(vdd_nom_123) ); 
Switch_PMOS_nfin12_n12_X1_Y1 mmp7 ( .D(vop), .G(vyy), .S(vdd_nom_123) ); 
Switch_PMOS_nfin12_n12_X1_Y1 mmp4 ( .D(vyy), .G(clk), .S(vdd_nom_123) ); 
Switch_PMOS_nfin12_n12_X1_Y1 mmp6 ( .D(von), .G(vxx), .S(vdd_nom_123) ); 
Switch_PMOS_nfin12_n12_X1_Y1 mmp3 ( .D(vx), .G(clk), .S(vdd_nom_123) ); 
Switch_PMOS_nfin12_n12_X1_Y1 mmp2 ( .D(vxx), .G(clk), .S(vdd_nom_123) ); 
Switch_NMOS_nfin96_n12_X4_Y2 mmn2 ( .D(vcom), .G(clk), .S(vss) ); 
Switch_NMOS_nfin12_n12_X1_Y1 mmn5 ( .D(von), .G(vxx), .S(vss) ); 
Switch_NMOS_nfin12_n12_X1_Y1 mmn6 ( .D(vop), .G(vyy), .S(vss) ); 
CCP_S_NMOS_B_nfin96_n12_X8_Y1 mmn4_mmn3 ( .B(vss), .DA(vxx), .DB(vyy), .SA(vx), .SB(vy) ); 
CCP_PMOS_nfin48_n12_X2_Y2 mmp1_mmp0 ( .DA(vxx), .DB(vyy), .S(vdd_nom_123) ); 
DP_NMOS_B_nfin192_n12_X8_Y2 mmn1_mmn0 ( .B(vss), .DA(vy), .DB(vx), .GA(vip), .GB(v_in), .S(vcom) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd_nom_123;
endmodule
`endcelldefine
