//Verilog block level netlist file for cascode_current_mirror_ota
//Generated by UMN for ALIGN project 


module CMFB_NMOS ( DA, S, DB, GB ); 
input DA, S, DB, GB;

DCL_NMOS_n10_X1_Y1 M0 ( .D(DA), .S(S) ); 
Switch_NMOS_n10_X3_Y1 M1 ( .D(DB), .G(GB), .S(S) ); 

endmodule

module cascode_current_mirror_ota ( vbiasp, vbiasnd, vdd, vss, vinp, vinn, id, vbiasn, voutp ); 
input vbiasp, vbiasnd, vdd, vss, vinp, vinn, id, vbiasn, voutp;

Switch_NMOS_n10_X3_Y1 m10 ( .D(net034), .G(vbiasnd), .S(vss) ); 
DCL_NMOS_n10_X1_Y1 m1nup ( .D(vbiasn), .S(net9b) ); 
DCL_PMOS_n10_X1_Y1 m1pdown ( .D(vbiasp), .S(net8b) ); 
DCL_PMOS_n10_X1_Y1 m1pup ( .D(net8b), .S(vdd) ); 
SCM_NMOS_n10_X2_Y1 m14_m16 ( .DA(id), .DB(net24), .S(vss) ); 
CMC_PMOS_S_n10_X1_Y1 m21_m20 ( .DA(net015), .G(net16), .DB(net06), .S(vdd) ); 
CMC_PMOS_S_n10_X1_Y1 m19_m18 ( .DA(net021), .G(net27), .DB(net024), .S(vdd) ); 
DP_NMOS_n10_X3_Y1 m17_m15 ( .DA(net16), .GA(vinn), .S(net24), .DB(net27), .GB(vinp) ); 
CMFB_NMOS m1ndown_m11 ( .DA(net9b), .S(vss), .DB(net033), .GB(vbiasnd) ); 
CMC_PMOS_n10_X4_Y3 m26_m22 ( .DA(net16), .G(vbiasp), .DB(vbiasnd), .SA(net015), .SB(net06) ); 
CMC_PMOS_n10_X4_Y3 m27_m23 ( .DA(net27), .G(vbiasp), .DB(voutp), .SA(net021), .SB(net024) ); 
CMC_NMOS_n10_X3_Y1 m24_m25 ( .DA(vbiasnd), .G(vbiasn), .DB(voutp), .SA(net033), .SB(net034) ); 

endmodule
