//Verilog block level netlist file for telescopic_ota_multi_connection
//Generated by UMN for ALIGN project 


module telescopic_ota_multi_connection ( d1, vbiasn, vbiasp1, vbiasp2, vinn, vinp, voutn, voutp ); 
input d1, vbiasn, vbiasp1, vbiasp2, vinn, vinp, voutn, voutp;

DCL_NMOS_nfin24_n12_X2_Y1_RVT m5 ( .D(d1), .S(vss) ); 
Switch_NMOS_nfin36_n12_X3_Y1_RVT m4 ( .D(net10), .G(d1), .S(vss) ); 
CMC_S_NMOS_B_nfin36_n12_X3_Y1_RVT m9_m8 ( .B(vss), .DA(voutn), .DB(voutp), .G(vbiasn), .SA(net8), .SB(net014) ); 
CMC_S_PMOS_B_nfin24_n12_X2_Y1_RVT m7_m6 ( .B(vdd), .DA(voutp), .DB(voutn), .G(vbiasp2), .SA(net012), .SB(net06) ); 
CMC_PMOS_nfin12_n12_X1_Y1_RVT m2_m1 ( .DA(net012), .DB(net06), .G(vbiasp1), .S(vdd) ); 
DP_NMOS_B_nfin108_n12_X9_Y1_RVT m3_m0 ( .B(vss), .DA(net014), .DB(net8), .GA(vinn), .GB(vinp), .S(net10) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd;
endmodule
`endcelldefine
