//Verilog block level netlist file for inverter_v3
//Generated by UMN for ALIGN project 


module INV_LVT ( SN, SP, i, zn ); 
input SN, SP, i, zn;

Switch_NMOS_n12_X1_Y1 xm0 ( .B(SN), .D(zn), .G(i), .S(SN) ); 
Switch_PMOS_n12_X1_Y1 xm1 ( .B(SP), .D(zn), .G(i), .S(SP) ); 

endmodule

module inverter_v3 ( vin, vout ); 
input vin, vout;

Dummy_NMOS_n12_X1_Y1 mn2 ( .B(vss), .D(vout), .S(vss) ); 
INV_LVT mn1_mp1 ( .zn(vout), .i(vin), .SN(vss), .SP(vdd) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd;
endmodule
`endcelldefine
