//Verilog block level netlist file for high_speed_comparator
//Generated by UMN for ALIGN project 


module high_speed_comparator ( vip, vcc, vop_latch, vin, von, vop, vss, clk_ideal, von_latch, clk ); 
input vip, vcc, vop_latch, vin, von, vop, vss, clk_ideal, von_latch, clk;

strong_arm_latch xi0 ( .clk(clk), .vcc(vcc), .vin(vin), .vip(vip), .von(von), .vop(vop), .vss(vss) ); 
inv1 xi1 ( .in(clk_ideal), .out(net12), .vddi(vcc), .vssi(vss) ); 
inv2 xi2 ( .in(net12), .out(net11), .vddi(vcc), .vssi(vss) ); 
inv3 xi3 ( .in(net11), .out(net10), .vddi(vcc), .vssi(vss) ); 
inv4 xi4 ( .in(net10), .out(clk), .vddi(vcc), .vssi(vss) ); 
nor xi5 ( .a(vop), .b(von_latch), .o1(vop_latch), .vcc(vcc), .vssx(vss) ); 
nor xi6 ( .a(vop_latch), .b(von), .o1(von_latch), .vcc(vcc), .vssx(vss) ); 

endmodule

module strong_arm_latch ( clk, vcc, vin, vip, von, vop, vss ); 
input clk, vcc, vin, vip, von, vop, vss;

Switch_NMOS_n12_X3_Y2 mn0 ( .D(net44), .G(net16), .S(net42) ); 
Switch_NMOS_n12_X3_Y2 mn1 ( .D(net16), .G(net44), .S(net8) ); 
Switch_NMOS_n12_X11_Y1 mn2 ( .D(net8), .G(vip), .S(net34) ); 
Switch_NMOS_n12_X11_Y1 mn3 ( .D(net42), .G(vin), .S(net34) ); 
Switch_NMOS_n12_X3_Y2 mn4 ( .D(net34), .G(clk), .S(vss) ); 
Switch_PMOS_n12_X3_Y1 mp0 ( .D(net44), .G(net16), .S(vcc) ); 
Switch_PMOS_n12_X1_Y1 mp1 ( .D(net16), .G(clk), .S(vcc) ); 
Switch_PMOS_n12_X3_Y1 mp2 ( .D(net16), .G(net44), .S(vcc) ); 
Switch_PMOS_n12_X1_Y1 mp3 ( .D(net44), .G(clk), .S(vcc) ); 
Switch_PMOS_n12_X1_Y1 mp4 ( .D(net8), .G(clk), .S(vcc) ); 
Switch_PMOS_n12_X1_Y1 mp5 ( .D(net42), .G(clk), .S(vcc) ); 
inv1 xi0 ( .in(net44), .out(vop), .vddi(vcc), .vssi(vss) ); 
inv1 xi1 ( .in(net16), .out(von), .vddi(vcc), .vssi(vss) ); 

endmodule

module inv1 ( in, out, vddi, vssi ); 
input in, out, vddi, vssi;

Switch_NMOS_n12_X1_Y1 mn0 ( .D(out), .G(in), .S(vssi) ); 
Switch_PMOS_n12_X1_Y1 mn1 ( .D(out), .G(in), .S(vddi) ); 

endmodule

module inv2 ( in, out, vddi, vssi ); 
input in, out, vddi, vssi;

Switch_NMOS_n12_X1_Y1 mn0 ( .D(out), .G(in), .S(vssi) ); 
Switch_PMOS_n12_X1_Y1 mn1 ( .D(out), .G(in), .S(vddi) ); 

endmodule

module inv3 ( in, out, vddi, vssi ); 
input in, out, vddi, vssi;

Switch_NMOS_n12_X1_Y1 mn0 ( .D(out), .G(in), .S(vssi) ); 
Switch_PMOS_n12_X1_Y1 mn1 ( .D(out), .G(in), .S(vddi) ); 

endmodule

module inv4 ( in, out, vddi, vssi ); 
input in, out, vddi, vssi;

Switch_NMOS_n12_X2_Y1 mn0 ( .D(out), .G(in), .S(vssi) ); 
Switch_PMOS_n12_X2_Y1 mn1 ( .D(out), .G(in), .S(vddi) ); 

endmodule

module nor ( a, b, o1, vcc, vssx ); 
input a, b, o1, vcc, vssx;

Switch_NMOS_n12_X1_Y1 mn0 ( .D(o1), .G(b), .S(vssx) ); 
Switch_NMOS_n12_X1_Y1 mn1 ( .D(o1), .G(a), .S(vssx) ); 
Switch_PMOS_n12_X1_Y1 mp0 ( .D(net010), .G(b), .S(vcc) ); 
Switch_PMOS_n12_X1_Y1 mp1 ( .D(o1), .G(a), .S(net010) ); 

endmodule
