FROM darpaalign/with_protobuf:2019sept30 as placeroute_coverage_image

RUN \
    git clone https://www.github.com/ALIGN-analoglayout/lpsolve.git  && \
    cp -r lpsolve /usr/local/lib/ && \
    apt-get -qq update && \
    DEBIAN_FRONTEND=noninterative apt-get -qq install wget gfortran && \
    apt-get -qq clean

# SuperLU
RUN \
    mkdir -p /opt && \
    cd /opt && \
    git clone https://www.github.com/ALIGN-analoglayout/superlu.git  && \
    cd superlu && \
    tar xvfz superlu_5.2.1.tar.gz && \
    cd SuperLU_5.2.1 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make
ENV SuperLu_DIR=/opt/superlu

COPY . /PlaceRouteHierFlow

ENV LD_LIBRARY_PATH=/usr/local/lib/lpsolve/lp_solve_5.5.2.5_dev_ux64

WORKDIR /PlaceRouteHierFlow

RUN \
    make COVERAGE=--coverage -j4
