//Verilog block level netlist file for COMPARATOR_2LEVEL_BIDIRECTIONAL_MAC_SKEW
//Generated by UMN for ALIGN project 


module INV_LVT ( SN, SP, i, zn ); 
input SN, SP, i, zn;

Switch_NMOS_n12_X1_Y1 xm0 ( .B(SN), .D(zn), .G(i), .S(SN) ); 
Switch_PMOS_n12_X1_Y1 xm1 ( .B(SP), .D(zn), .G(i), .S(SP) ); 

endmodule

module COMPARATOR_2LEVEL_BIDIRECTIONAL_MAC_SKEW ( _net0, _net1, clk, clkn, fine, fine_boost, flip, flipb, intern, interp, outm, outp, vmid, vmidb, vxn, vxn2, vxp, vxp2 ); 
input _net0, _net1, clk, clkn, fine, fine_boost, flip, flipb, intern, interp, outm, outp, vmid, vmidb, vxn, vxn2, vxp, vxp2;

CLK_BOOST_COMP xi3 ( .bypass(gnd), .clk_boost(fine_boost), .clk_in(fine) ); 
INVD0BWP xi4 ( .i(gnd), .zn(net073), .vss(gnd) ); 
INVD0BWP xi0 ( .i(clk), .zn(clkb), .vss(gnd) ); 
Dcap_NMOS_n12_X1_Y1 xm0 ( .B(gnd), .S(gnd), .G(net066) ); 
Dcap_NMOS_n12_X1_Y1 xm1 ( .B(gnd), .S(gnd), .G(net065) ); 
Dummy1_NMOS_n12_X1_Y1 xm56 ( .B(gnd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 xm51 ( .B(gnd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm31 ( .B(gnd), .D(flipb), .G(flip), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm21 ( .B(gnd), .D(flip), .G(clkb), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm15 ( .B(gnd), .D(net05), .G(clkn), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm32 ( .B(gnd), .D(clkn), .G(flip), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm38 ( .B(gnd), .D(vmidb), .G(vxn2), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm39 ( .B(gnd), .D(vmid), .G(vxp2), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm33 ( .B(gnd), .D(clk), .G(flipb), .S(clkn) ); 
Switch_PMOS_n12_X1_Y1 xm62 ( .B(vdd), .D(vdd), .G(clk), .S(vxp) ); 
Switch_PMOS_n12_X1_Y1 xm61 ( .B(vdd), .D(vdd), .G(clk), .S(vxn) ); 
Dummy1_PMOS_n12_X1_Y1 xm58 ( .B(vdd), .S(gnd) ); 
Dummy1_PMOS_n12_X1_Y1 xm57 ( .B(vdd), .S(gnd) ); 
Dummy1_PMOS_n12_X1_Y1 xm54 ( .B(vdd), .S(gnd) ); 
Switch_PMOS_n12_X1_Y1 xm30 ( .B(vdd), .D(flipb), .G(clk), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm28 ( .B(vdd), .D(flip), .G(vxn), .S(net027) ); 
Switch_PMOS_n12_X1_Y1 xm20 ( .B(vdd), .D(net027), .G(clkb), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm29 ( .B(vdd), .D(flip), .G(vxp), .S(net027) ); 
Switch_PMOS_n12_X1_Y1 xm19 ( .B(vdd), .D(net04), .G(flipb), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm34 ( .B(vdd), .D(clk), .G(flip), .S(clkn) ); 
CCP_PMOS_S_n12_X1_Y1 xm49_xm48 ( .B(vdd), .DA(interp), .DB(intern), .S(vdd) ); 
CMC_NMOS_S_n12_X1_Y1 xm41_xm37 ( .B(gnd), .DA(vxp2), .G(flipb), .S(gnd), .DB(vxn2) ); 
CMC_PMOS_S_n12_X1_Y1 xm45_xm47 ( .B(vdd), .DA(vmidb), .G(vxn2), .S(vdd), .DB(intern) ); 
CMC_PMOS_S_n12_X1_Y1 xm44_xm46 ( .B(vdd), .DA(vmid), .G(vxp2), .S(vdd), .DB(interp) ); 
CCP_NMOS_n12_X1_Y1 xm42_xm43 ( .B(gnd), .DA(interp), .DB(intern), .SA(vmid), .SB(vmidb) ); 
INV_LVT xm16_xm2 ( .zn(outm), .i(intern), .SN(gnd), .SP(vdd) ); 
INV_LVT xm6_xm9 ( .zn(outp), .i(interp), .SN(gnd), .SP(vdd) ); 
DP_NMOS_n12_X1_Y1 xm13_xm14 ( .B(gnd), .DA(vxp), .GA(_net1), .S(net05), .DB(vxn), .GB(_net0) ); 
DP_PMOS_n12_X1_Y1 xm17_xm18 ( .B(vdd), .DA(vxp), .GA(_net1), .S(net04), .DB(vxn), .GB(_net0) ); 
CMC_PMOS_n12_X1_Y1 xm40_xm36 ( .B(vdd), .DA(vxp2), .G(flipb), .SA(vxp), .DB(vxn2), .SB(vxn) ); 
CMC_NMOS_n12_X1_Y1 xm10_xm12 ( .B(gnd), .DA(vxp), .G(fine_boost), .SA(net066), .DB(vxn), .SB(net065) ); 

endmodule

module CLK_BOOST_COMP ( bypass, clk_boost, clk_in ); 
input bypass, clk_boost, clk_in;

Switch_PMOS_n12_X1_Y1 xm5 ( .B(vdd), .D(net8), .G(net5), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm4 ( .B(vdd), .D(clk_boost), .G(net6), .S(net8) ); 
Switch_PMOS_n12_X1_Y1 xm1 ( .B(vdd), .D(net5), .G(net6), .S(net8) ); 
Switch_NMOS_n12_X1_Y1 xm6 ( .B(gnd), .D(clk_boost), .G(net6), .S(clk_in) ); 
Switch_NMOS_n12_X1_Y1 xm2 ( .B(gnd), .D(net5), .G(net6), .S(net013) ); 
NR2D2BWP xi1 ( .a1(net6), .a2(bypass), .zn(net013), .vss(gnd) ); 
INVD0BWP xi2 ( .i(clk_in), .zn(net6), .vss(gnd) ); 
Cap_2f c2 ( .PLUS(net013), .MINUS(net8) ); 

endmodule

module NR2D2BWP ( a1, a2, vss, zn ); 
input a1, a2, vss, zn;

Switch_NMOS_n12_X1_Y1 m0 ( .B(vss), .D(zn), .G(a2), .S(vss) ); 
Switch_NMOS_n12_X1_Y1 m1 ( .B(vss), .D(zn), .G(a1), .S(vss) ); 
Switch_PMOS_n12_X1_Y1 m4 ( .B(vdd), .D(zn), .G(a1), .S(net17) ); 
Switch_PMOS_n12_X1_Y1 m6 ( .B(vdd), .D(zn), .G(a1), .S(net25) ); 
CMC_PMOS_S_n12_X1_Y1 m7_m5 ( .B(vdd), .DA(net17), .G(a2), .S(vdd), .DB(net25) ); 

endmodule

module INVD0BWP ( i, vss, zn ); 
input i, vss, zn;

Switch_NMOS_n12_X1_Y1 m0 ( .B(vss), .D(zn), .G(i), .S(vss) ); 
Switch_PMOS_n12_X1_Y1 m1 ( .B(vdd), .D(zn), .G(i), .S(vdd) ); 

endmodule

`celldefine
module global_power;
supply0 gnd;
supply1 vdd;
endmodule
`endcelldefine
