//Verilog block level netlist file for ota
//Generated by UMN for ALIGN project 


module ota ( vbiasn, vbiasp1, vinn, vinp, voutn, voutp ); 
input vbiasn, vbiasp1, vinn, vinp, voutn, voutp;

Switch_PMOS_nfin15_n12_X2_Y1_RVT m6 ( .D(voutp), .G(vbiasp), .S(net012) ); 
Switch_PMOS_nfin15_n12_X2_Y1_RVT m7 ( .D(voutn), .G(vbiasp), .S(net06) ); 
SCM_NMOS_nfin10_n12_X1_Y1_RVT m4_m3 ( .DA(id), .DB(net10), .S(vss) ); 
CMC_PMOS_nfin10_n12_X1_Y1_RVT m9_m8 ( .DA(net06), .DB(net012), .G(vbiasp1), .S(vdd!) ); 
CMC_S_NMOS_B_nfin25_n12_X3_Y1_RVT m2_m10 ( .B(vss), .DA(voutp), .DB(voutn), .G(vbiasn), .SA(net014), .SB(net8) ); 
DP_NMOS_B_nfin75_n12_X7_Y1_RVT m1_m0 ( .B(vss), .DA(net8), .DB(net014), .GA(vinp), .GB(vinn), .S(net10) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd!;
endmodule
`endcelldefine
