//Verilog block level netlist file for Sanitized_model3x_MDLL_TOP
//Generated by UMN for ALIGN project 


module Sanitized_model3x_MDLL_TOP ( CKOUT, EN_DLL, FRCODE<0>, FRCODE<1>, FRCODE<2>, FRCODE<3>, FRCODE<4>, FRCODE<5>, FRCODE<6>, MD_SAR, MD_TRK, NDIV<0>, NDIV<1>, NDIV<2>, NDIV<3>, NDIV<4>, NDIV<5>, SCLK0 ); 
input CKOUT, EN_DLL, FRCODE<0>, FRCODE<1>, FRCODE<2>, FRCODE<3>, FRCODE<4>, FRCODE<5>, FRCODE<6>, MD_SAR, MD_TRK, NDIV<0>, NDIV<1>, NDIV<2>, NDIV<3>, NDIV<4>, NDIV<5>, SCLK0;

MDLL_CKGEN_V1 XI0 ( .EN_DLL(EN_DLL), .FREE_RUN(FR), .MD_SAR(MD_SAR), .MD_TRK(MD_TRK), .REF_CLK(net15), .SAR_EN(net19), .SCLK0(SCLK0), .SEL_RST(SEL_RST), .TRK_EN(net20) ); 
DEL_7b XI1 ( .CKOUT(net17), .EN(EN_DLL), .LSB<3>(CODE<2>), .LSB<2>(CODE<1>), .LSB<1>(CODE<0>), .REF_CLK(net15), .SEL0(CODE<3>), .SEL1(CODE<4>), .SEL2(CODE<5>), .SEL3(CODE<6>), .SEL_DL(net013) ); 
MDLL_LOGIC_VLOG XI3 ( .CODE<6>(CODE<6>), .CODE<5>(CODE<5>), .CODE<4>(CODE<4>), .CODE<3>(CODE<3>), .CODE<2>(CODE<2>), .CODE<1>(CODE<1>), .CODE<0>(CODE<0>), .COMP(COMP), .EN0DLL(EN_DLL), .FRCODE<6>(FRCODE<6>), .FRCODE<5>(FRCODE<5>), .FRCODE<4>(FRCODE<4>), .FRCODE<3>(FRCODE<3>), .FRCODE<2>(FRCODE<2>), .FRCODE<1>(FRCODE<1>), .FRCODE<0>(FRCODE<0>), .FREE0RUN(FR), .REFCLK(net15), .SAR0EN(net19), .STATUS<2>(net016<0>), .STATUS<1>(net016<1>), .STATUS<0>(net016<2>), .TRK0EN(net20) ); 
DCAP8 XI10<131> (  ); 
DCAP8 XI10<130> (  ); 
DCAP8 XI10<129> (  ); 
DCAP8 XI10<128> (  ); 
DCAP8 XI10<127> (  ); 
DCAP8 XI10<126> (  ); 
DCAP8 XI10<125> (  ); 
DCAP8 XI10<124> (  ); 
DCAP8 XI10<123> (  ); 
DCAP8 XI10<122> (  ); 
DCAP8 XI10<121> (  ); 
DCAP8 XI10<120> (  ); 
DCAP8 XI10<119> (  ); 
DCAP8 XI10<118> (  ); 
DCAP8 XI10<117> (  ); 
DCAP8 XI10<116> (  ); 
DCAP8 XI10<115> (  ); 
DCAP8 XI10<114> (  ); 
DCAP8 XI10<113> (  ); 
DCAP8 XI10<112> (  ); 
DCAP8 XI10<111> (  ); 
DCAP8 XI10<110> (  ); 
DCAP8 XI10<109> (  ); 
DCAP8 XI10<108> (  ); 
DCAP8 XI10<107> (  ); 
DCAP8 XI10<106> (  ); 
DCAP8 XI10<105> (  ); 
DCAP8 XI10<104> (  ); 
DCAP8 XI10<103> (  ); 
DCAP8 XI10<102> (  ); 
DCAP8 XI10<101> (  ); 
DCAP8 XI10<100> (  ); 
DCAP8 XI10<99> (  ); 
DCAP8 XI10<98> (  ); 
DCAP8 XI10<97> (  ); 
DCAP8 XI10<96> (  ); 
DCAP8 XI10<95> (  ); 
DCAP8 XI10<94> (  ); 
DCAP8 XI10<93> (  ); 
DCAP8 XI10<92> (  ); 
DCAP8 XI10<91> (  ); 
DCAP8 XI10<90> (  ); 
DCAP8 XI10<89> (  ); 
DCAP8 XI10<88> (  ); 
DCAP8 XI10<87> (  ); 
DCAP8 XI10<86> (  ); 
DCAP8 XI10<85> (  ); 
DCAP8 XI10<84> (  ); 
DCAP8 XI10<83> (  ); 
DCAP8 XI10<82> (  ); 
DCAP8 XI10<81> (  ); 
DCAP8 XI10<80> (  ); 
DCAP8 XI10<79> (  ); 
DCAP8 XI10<78> (  ); 
DCAP8 XI10<77> (  ); 
DCAP8 XI10<76> (  ); 
DCAP8 XI10<75> (  ); 
DCAP8 XI10<74> (  ); 
DCAP8 XI10<73> (  ); 
DCAP8 XI10<72> (  ); 
DCAP8 XI10<71> (  ); 
DCAP8 XI10<70> (  ); 
DCAP8 XI10<69> (  ); 
DCAP8 XI10<68> (  ); 
DCAP8 XI10<67> (  ); 
DCAP8 XI10<66> (  ); 
DCAP8 XI10<65> (  ); 
DCAP8 XI10<64> (  ); 
DCAP8 XI10<63> (  ); 
DCAP8 XI10<62> (  ); 
DCAP8 XI10<61> (  ); 
DCAP8 XI10<60> (  ); 
DCAP8 XI10<59> (  ); 
DCAP8 XI10<58> (  ); 
DCAP8 XI10<57> (  ); 
DCAP8 XI10<56> (  ); 
DCAP8 XI10<55> (  ); 
DCAP8 XI10<54> (  ); 
DCAP8 XI10<53> (  ); 
DCAP8 XI10<52> (  ); 
DCAP8 XI10<51> (  ); 
DCAP8 XI10<50> (  ); 
DCAP8 XI10<49> (  ); 
DCAP8 XI10<48> (  ); 
DCAP8 XI10<47> (  ); 
DCAP8 XI10<46> (  ); 
DCAP8 XI10<45> (  ); 
DCAP8 XI10<44> (  ); 
DCAP8 XI10<43> (  ); 
DCAP8 XI10<42> (  ); 
DCAP8 XI10<41> (  ); 
DCAP8 XI10<40> (  ); 
DCAP8 XI10<39> (  ); 
DCAP8 XI10<38> (  ); 
DCAP8 XI10<37> (  ); 
DCAP8 XI10<36> (  ); 
DCAP8 XI10<35> (  ); 
DCAP8 XI10<34> (  ); 
DCAP8 XI10<33> (  ); 
DCAP8 XI10<32> (  ); 
DCAP8 XI10<31> (  ); 
DCAP8 XI10<30> (  ); 
DCAP8 XI10<29> (  ); 
DCAP8 XI10<28> (  ); 
DCAP8 XI10<27> (  ); 
DCAP8 XI10<26> (  ); 
DCAP8 XI10<25> (  ); 
DCAP8 XI10<24> (  ); 
DCAP8 XI10<23> (  ); 
DCAP8 XI10<22> (  ); 
DCAP8 XI10<21> (  ); 
DCAP8 XI10<20> (  ); 
DCAP8 XI10<19> (  ); 
DCAP8 XI10<18> (  ); 
DCAP8 XI10<17> (  ); 
DCAP8 XI10<16> (  ); 
DCAP8 XI10<15> (  ); 
DCAP8 XI10<14> (  ); 
DCAP8 XI10<13> (  ); 
DCAP8 XI10<12> (  ); 
DCAP8 XI10<11> (  ); 
DCAP8 XI10<10> (  ); 
DCAP8 XI10<9> (  ); 
DCAP8 XI10<8> (  ); 
DCAP8 XI10<7> (  ); 
DCAP8 XI10<6> (  ); 
DCAP8 XI10<5> (  ); 
DCAP8 XI10<4> (  ); 
DCAP8 XI10<3> (  ); 
DCAP8 XI10<2> (  ); 
DCAP8 XI10<1> (  ); 
DCAP8 XI10<0> (  ); 
SEL_LOGIC_V2 XI2 ( .MDLCLK(net17), .NDIV<5>(NDIV<5>), .NDIV<4>(NDIV<4>), .NDIV<3>(NDIV<3>), .NDIV<2>(NDIV<2>), .NDIV<1>(NDIV<1>), .NDIV<0>(NDIV<0>), .SEL(net16), .SRST(SEL_RST) ); 
INVD0 XI8 ( .I(net16), .ZN(COMP) ); 
CKBD2 XI7 ( .I(net17), .Z(CKOUT) ); 
OR2D1 XI16 ( .A1(net16), .A2(FR), .Z(net013) ); 

endmodule

module MDLL_CKGEN_V1 ( EN_DLL, FREE_RUN, MD_SAR, MD_TRK, REF_CLK, SAR_EN, SCLK0, SEL_RST, TRK_EN ); 
input EN_DLL, FREE_RUN, MD_SAR, MD_TRK, REF_CLK, SAR_EN, SCLK0, SEL_RST, TRK_EN;

INVD0 XI9 ( .I(net31), .ZN(net17) ); 
AN3D2 XI40 ( .A1(net042), .A2(EN_DLL), .A3(MD_SAR), .Z(SAR_EN) ); 
AN3D2 XI45 ( .A1(SCLK), .A2(net010), .A3(net25), .Z(net048) ); 
INVD1 XI25 ( .I(net010), .ZN(FREE_RUN) ); 
INVD1 XI5 ( .I(net37), .ZN(net25) ); 
NR2D0 XI0 ( .A1(MD_SAR), .A2(MD_TRK), .ZN(net36) ); 
DFND1 XI43 ( .CPN(SCLK0), .D(EN_DLL), .Q(net032), .QN(net045) ); 
INVD8 XI44 ( .I(net048), .ZN(SEL_RST) ); 
TIEL XI15 ( .ZN(net32) ); 
DFSNQD1 XI22 ( .CP(SCLK), .D(net30), .Q(net27), .SDN(net14) ); 
DFSNQD1 XI21 ( .CP(SCLK), .D(net29), .Q(net30), .SDN(net14) ); 
DFSNQD1 XI20 ( .CP(SCLK), .D(net27), .Q(net021), .SDN(net14) ); 
DFSNQD1 XI19 ( .CP(SCLK), .D(net34), .Q(net33), .SDN(net14) ); 
DFSNQD1 XI18 ( .CP(SCLK), .D(net33), .Q(net29), .SDN(net14) ); 
DFSNQD1 XI17 ( .CP(SCLK), .D(net35), .Q(net34), .SDN(net14) ); 
DFSNQD1 XI16 ( .CP(SCLK), .D(net32), .Q(net35), .SDN(net14) ); 
ND2D0 XI24 ( .A1(net36), .A2(EN_DLL), .ZN(net010) ); 
DEL015 XI8 ( .I(EN_DLL), .Z(net31) ); 
DEL015 XI4 ( .I(SCLK), .Z(net37) ); 
DFSND1 XI27 ( .CP(SCLK), .D(net021), .Q(net042), .QN(net026), .SDN(net14) ); 
AN2D0 XI28 ( .A1(net026), .A2(EN_DLL), .Z(TRK_RST) ); 
DFCND1 XI30 ( .CDN(TRK_RST), .CP(net020), .D(net039), .Q(net027), .QN(net039) ); 
DFCND1 XI29 ( .CDN(TRK_RST), .CP(SCLK), .D(net015), .Q(net020), .QN(net015) ); 
AN2D2 XI36 ( .A1(net032), .A2(SCLK0), .Z(SCLK) ); 
CKBD4 XI35 ( .I(SCLK), .Z(REF_CLK) ); 
ND3D3 XI38 ( .A1(EN_DLL), .A2(net17), .A3(MD_SAR), .ZN(net14) ); 
AN3D1 XI42 ( .A1(net027), .A2(net015), .A3(MD_TRK), .Z(TRK_EN) ); 

endmodule

module INVD0 ( I, ZN ); 
input I, ZN;

Switch_NMOS_n12_X1_Y1 MMU1_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU1_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 

endmodule

module AN3D2 ( A1, A2, A3, Z ); 
input A1, A2, A3, Z;

Switch_NMOS_n12_X1_Y1 MM_u3_1_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u4_M_u6 ( .B(VSS), .D(net13), .G(A3), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u4_M_u5 ( .B(VSS), .D(net9), .G(A2), .S(net13) ); 
Switch_NMOS_n12_X1_Y1 MM_u4_M_u4 ( .B(VSS), .D(net5), .G(A1), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MM_u3_0_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u3 ( .B(VDD), .D(net5), .G(A3), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u3_1_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u3_0_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u1 ( .B(VDD), .D(net5), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u2 ( .B(VDD), .D(net5), .G(A2), .S(VDD) ); 

endmodule

module INVD1 ( I, ZN ); 
input I, ZN;

Switch_NMOS_n12_X1_Y1 MMU1_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU1_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 

endmodule

module NR2D0 ( A1, A2, ZN ); 
input A1, A2, ZN;

Switch_NMOS_n12_X1_Y1 MMI1_M_u3 ( .B(VSS), .D(ZN), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI1_M_u4 ( .B(VSS), .D(ZN), .G(A1), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u1 ( .B(VDD), .D(net13), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u2 ( .B(VDD), .D(ZN), .G(A1), .S(net13) ); 

endmodule

module DFND1 ( CPN, D, Q, QN ); 
input CPN, D, Q, QN;

Switch_NMOS_n12_X1_Y1 MMI53_M_u2 ( .B(VSS), .D(net63), .G(net100), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI29_M_u2 ( .B(VSS), .D(QN), .G(net97), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI4 ( .B(VSS), .D(net24), .G(net67), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI55 ( .B(VSS), .D(net97), .G(net67), .S(net100) ); 
Switch_NMOS_n12_X1_Y1 MMI13_M_u2 ( .B(VSS), .D(net11), .G(net1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI50 ( .B(VSS), .D(net11), .G(net95), .S(net100) ); 
Switch_NMOS_n12_X1_Y1 MMI32_M_u2 ( .B(VSS), .D(net67), .G(net95), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI5 ( .B(VSS), .D(net1), .G(D), .S(net24) ); 
Switch_NMOS_n12_X1_Y1 MMI31_M_u2 ( .B(VSS), .D(net95), .G(CPN), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI56_M_u2 ( .B(VSS), .D(net97), .G(net63), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI48 ( .B(VSS), .D(net9), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI27_M_u2 ( .B(VSS), .D(Q), .G(net63), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI47 ( .B(VSS), .D(net1), .G(net95), .S(net9) ); 
Switch_PMOS_n12_X1_Y1 MMI53_M_u3 ( .B(VDD), .D(net63), .G(net100), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI54 ( .B(VDD), .D(net97), .G(net95), .S(net100) ); 
Switch_PMOS_n12_X1_Y1 MMI32_M_u3 ( .B(VDD), .D(net67), .G(net95), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI43 ( .B(VDD), .D(net60), .G(net11), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI6 ( .B(VDD), .D(net1), .G(D), .S(net53) ); 
Switch_PMOS_n12_X1_Y1 MMI29_M_u3 ( .B(VDD), .D(QN), .G(net97), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI31_M_u3 ( .B(VDD), .D(net95), .G(CPN), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI27_M_u3 ( .B(VDD), .D(Q), .G(net63), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI13_M_u3 ( .B(VDD), .D(net11), .G(net1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI52 ( .B(VDD), .D(net11), .G(net67), .S(net100) ); 
Switch_PMOS_n12_X1_Y1 MMI56_M_u3 ( .B(VDD), .D(net97), .G(net63), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI45 ( .B(VDD), .D(net1), .G(net67), .S(net60) ); 
Switch_PMOS_n12_X1_Y1 MMI7 ( .B(VDD), .D(net53), .G(net95), .S(VDD) ); 

endmodule

module INVD8 ( I, ZN ); 
input I, ZN;

Switch_NMOS_n12_X1_Y1 MMU1_5_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU1_0_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU1_3_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU1_7_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU1_4_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU1_1_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU1_6_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU1_2_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU1_0_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU1_4_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU1_5_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU1_1_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU1_3_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU1_7_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU1_6_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU1_2_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 

endmodule

module TIEL ( ZN ); 
input ZN;

Switch_NMOS_n12_X1_Y1 MM_u2 ( .B(VSS), .D(ZN), .G(net5), .S(VSS) ); 
DCL_PMOS_n12_X1_Y1 MM_u1 ( .B(VDD), .D(net5), .S(VDD) ); 

endmodule

module DFSNQD1 ( CP, D, Q, SDN ); 
input CP, D, Q, SDN;

Switch_NMOS_n12_X1_Y1 MMI32_M_u4 ( .B(VSS), .D(net44), .G(net25), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI55_M_u2 ( .B(VSS), .D(net11), .G(CP), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI60_M_u2 ( .B(VSS), .D(Q), .G(net13), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI32_M_u3 ( .B(VSS), .D(net7), .G(SDN), .S(net44) ); 
Switch_NMOS_n12_X1_Y1 MMI31_M_u4 ( .B(VSS), .D(net37), .G(net13), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI31_M_u3 ( .B(VSS), .D(net33), .G(SDN), .S(net37) ); 
Switch_NMOS_n12_X1_Y1 MMI20 ( .B(VSS), .D(net7), .G(net83), .S(net63) ); 
Switch_NMOS_n12_X1_Y1 MMI23 ( .B(VSS), .D(net25), .G(net83), .S(net5) ); 
Switch_NMOS_n12_X1_Y1 MMI22 ( .B(VSS), .D(net33), .G(net11), .S(net63) ); 
Switch_NMOS_n12_X1_Y1 MMI21 ( .B(VSS), .D(net25), .G(D), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMI25_M_u2 ( .B(VSS), .D(net13), .G(net63), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI19 ( .B(VSS), .D(net20), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI24 ( .B(VSS), .D(net5), .G(net7), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI40_M_u2 ( .B(VSS), .D(net83), .G(net11), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI55_M_u3 ( .B(VDD), .D(net11), .G(CP), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI33 ( .B(VDD), .D(net33), .G(net83), .S(net63) ); 
Switch_PMOS_n12_X1_Y1 MMI32_M_u1 ( .B(VDD), .D(net7), .G(SDN), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI60_M_u3 ( .B(VDD), .D(Q), .G(net13), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI34 ( .B(VDD), .D(net25), .G(net11), .S(net96) ); 
Switch_PMOS_n12_X1_Y1 MMI30 ( .B(VDD), .D(net7), .G(net11), .S(net63) ); 
Switch_PMOS_n12_X1_Y1 MMI32_M_u2 ( .B(VDD), .D(net7), .G(net25), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI28 ( .B(VDD), .D(net81), .G(net83), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI40_M_u3 ( .B(VDD), .D(net83), .G(net11), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI31_M_u2 ( .B(VDD), .D(net33), .G(net13), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI35 ( .B(VDD), .D(net96), .G(net7), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI31_M_u1 ( .B(VDD), .D(net33), .G(SDN), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI25_M_u3 ( .B(VDD), .D(net13), .G(net63), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI26 ( .B(VDD), .D(net25), .G(D), .S(net81) ); 

endmodule

module ND2D0 ( A1, A2, ZN ); 
input A1, A2, ZN;

Switch_NMOS_n12_X1_Y1 MMI0_M_u3 ( .B(VSS), .D(ZN), .G(A1), .S(net1) ); 
Switch_NMOS_n12_X1_Y1 MMI0_M_u4 ( .B(VSS), .D(net1), .G(A2), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI0_M_u1 ( .B(VDD), .D(ZN), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_M_u2 ( .B(VDD), .D(ZN), .G(A2), .S(VDD) ); 

endmodule

module DEL015 ( I, Z ); 
input I, Z;

Switch_NMOS_n12_X1_Y1 MMI2_M_u2 ( .B(VSS), .D(Z), .G(net13), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI29 ( .B(VSS), .D(net25), .G(net9), .S(net28) ); 
Switch_NMOS_n12_X1_Y1 MMI30 ( .B(VSS), .D(net28), .G(net9), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI37 ( .B(VSS), .D(net17), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI28 ( .B(VSS), .D(net13), .G(net9), .S(net25) ); 
Switch_NMOS_n12_X1_Y1 MMI35 ( .B(VSS), .D(net9), .G(net5), .S(net44) ); 
Switch_NMOS_n12_X1_Y1 MMI1_M_u2 ( .B(VSS), .D(net5), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI36 ( .B(VSS), .D(net44), .G(net5), .S(net17) ); 
Switch_PMOS_n12_X1_Y1 MMI2_M_u3 ( .B(VDD), .D(Z), .G(net13), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI20 ( .B(VDD), .D(net57), .G(net9), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI23 ( .B(VDD), .D(net13), .G(net9), .S(net25) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u3 ( .B(VDD), .D(net5), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI21 ( .B(VDD), .D(net25), .G(net9), .S(net57) ); 
Switch_PMOS_n12_X1_Y1 MMI32 ( .B(VDD), .D(net9), .G(net5), .S(net44) ); 
Switch_PMOS_n12_X1_Y1 MMI31 ( .B(VDD), .D(net44), .G(net5), .S(net33) ); 
Switch_PMOS_n12_X1_Y1 MMI7 ( .B(VDD), .D(net33), .G(net5), .S(VDD) ); 

endmodule

module DFSND1 ( CP, D, Q, QN, SDN ); 
input CP, D, Q, QN, SDN;

Switch_NMOS_n12_X1_Y1 MMI32_M_u4 ( .B(VSS), .D(net57), .G(net61), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI55_M_u2 ( .B(VSS), .D(net11), .G(CP), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI60_M_u2 ( .B(VSS), .D(Q), .G(net79), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI32_M_u3 ( .B(VSS), .D(net97), .G(SDN), .S(net57) ); 
Switch_NMOS_n12_X1_Y1 MMI31_M_u4 ( .B(VSS), .D(net40), .G(net79), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI31_M_u3 ( .B(VSS), .D(net25), .G(SDN), .S(net40) ); 
Switch_NMOS_n12_X1_Y1 MMI20 ( .B(VSS), .D(net97), .G(net81), .S(net67) ); 
Switch_NMOS_n12_X1_Y1 MMI23 ( .B(VSS), .D(net61), .G(net81), .S(net5) ); 
Switch_NMOS_n12_X1_Y1 MMI22 ( .B(VSS), .D(net25), .G(net11), .S(net67) ); 
Switch_NMOS_n12_X1_Y1 MMI21 ( .B(VSS), .D(net61), .G(D), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MMI25_M_u2 ( .B(VSS), .D(net79), .G(net67), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI57_M_u2 ( .B(VSS), .D(QN), .G(net25), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI19 ( .B(VSS), .D(net9), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI24 ( .B(VSS), .D(net5), .G(net97), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI40_M_u2 ( .B(VSS), .D(net81), .G(net11), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI55_M_u3 ( .B(VDD), .D(net11), .G(CP), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI33 ( .B(VDD), .D(net25), .G(net81), .S(net67) ); 
Switch_PMOS_n12_X1_Y1 MMI32_M_u1 ( .B(VDD), .D(net97), .G(SDN), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI60_M_u3 ( .B(VDD), .D(Q), .G(net79), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI34 ( .B(VDD), .D(net61), .G(net11), .S(net104) ); 
Switch_PMOS_n12_X1_Y1 MMI30 ( .B(VDD), .D(net97), .G(net11), .S(net67) ); 
Switch_PMOS_n12_X1_Y1 MMI57_M_u3 ( .B(VDD), .D(QN), .G(net25), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI32_M_u2 ( .B(VDD), .D(net97), .G(net61), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI28 ( .B(VDD), .D(net85), .G(net81), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI40_M_u3 ( .B(VDD), .D(net81), .G(net11), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI31_M_u2 ( .B(VDD), .D(net25), .G(net79), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI35 ( .B(VDD), .D(net104), .G(net97), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI31_M_u1 ( .B(VDD), .D(net25), .G(SDN), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI25_M_u3 ( .B(VDD), .D(net79), .G(net67), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI26 ( .B(VDD), .D(net61), .G(D), .S(net85) ); 

endmodule

module AN2D0 ( A1, A2, Z ); 
input A1, A2, Z;

Switch_PMOS_n12_X1_Y1 MM_u3_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u1 ( .B(VDD), .D(net5), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u2 ( .B(VDD), .D(net5), .G(A2), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MM_u3_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u4 ( .B(VSS), .D(net17), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u3 ( .B(VSS), .D(net5), .G(A1), .S(net17) ); 

endmodule

module DFCND1 ( CDN, CP, D, Q, QN ); 
input CDN, CP, D, Q, QN;

Switch_NMOS_n12_X1_Y1 MMI29_M_u2 ( .B(VSS), .D(QN), .G(net33), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI4 ( .B(VSS), .D(net53), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI18 ( .B(VSS), .D(net33), .G(net5), .S(net79) ); 
Switch_NMOS_n12_X1_Y1 MMI21_M_u3 ( .B(VSS), .D(net95), .G(net79), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MMI13_M_u2 ( .B(VSS), .D(net81), .G(net25), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI15 ( .B(VSS), .D(net81), .G(net67), .S(net79) ); 
Switch_NMOS_n12_X1_Y1 MMI14_M_u2 ( .B(VSS), .D(net33), .G(net95), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI32_M_u2 ( .B(VSS), .D(net67), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI5 ( .B(VSS), .D(net25), .G(D), .S(net53) ); 
Switch_NMOS_n12_X1_Y1 MMI49 ( .B(VSS), .D(net20), .G(CDN), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI48 ( .B(VSS), .D(net17), .G(net81), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMI27_M_u2 ( .B(VSS), .D(Q), .G(net95), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI21_M_u4 ( .B(VSS), .D(net9), .G(CDN), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI22_M_u2 ( .B(VSS), .D(net5), .G(CP), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI47 ( .B(VSS), .D(net25), .G(net67), .S(net17) ); 
Switch_PMOS_n12_X1_Y1 MMI14_M_u3 ( .B(VDD), .D(net33), .G(net95), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI22_M_u3 ( .B(VDD), .D(net5), .G(CP), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI32_M_u3 ( .B(VDD), .D(net67), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI43 ( .B(VDD), .D(net72), .G(net81), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI6 ( .B(VDD), .D(net25), .G(D), .S(net104) ); 
Switch_PMOS_n12_X1_Y1 MMI29_M_u3 ( .B(VDD), .D(QN), .G(net33), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI27_M_u3 ( .B(VDD), .D(Q), .G(net95), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI44 ( .B(VDD), .D(net72), .G(CDN), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI17 ( .B(VDD), .D(net33), .G(net67), .S(net79) ); 
Switch_PMOS_n12_X1_Y1 MMI13_M_u3 ( .B(VDD), .D(net81), .G(net25), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI21_M_u1 ( .B(VDD), .D(net95), .G(net79), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI16 ( .B(VDD), .D(net81), .G(net5), .S(net79) ); 
Switch_PMOS_n12_X1_Y1 MMI45 ( .B(VDD), .D(net25), .G(net5), .S(net72) ); 
Switch_PMOS_n12_X1_Y1 MMI7 ( .B(VDD), .D(net104), .G(net67), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI21_M_u2 ( .B(VDD), .D(net95), .G(CDN), .S(VDD) ); 

endmodule

module AN2D2 ( A1, A2, Z ); 
input A1, A2, Z;

Switch_PMOS_n12_X1_Y1 MM_u3_1_M_u3 ( .B(VDD), .D(Z), .G(net9), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u2 ( .B(VDD), .D(net9), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u3_0_M_u3 ( .B(VDD), .D(Z), .G(net9), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u1 ( .B(VDD), .D(net9), .G(A1), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u4 ( .B(VSS), .D(net29), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u3 ( .B(VSS), .D(net9), .G(A1), .S(net29) ); 
Switch_NMOS_n12_X1_Y1 MM_u3_1_M_u2 ( .B(VSS), .D(Z), .G(net9), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u3_0_M_u2 ( .B(VSS), .D(Z), .G(net9), .S(VSS) ); 

endmodule

module CKBD4 ( I, Z ); 
input I, Z;

Switch_NMOS_n12_X1_Y1 MM_u15_1 ( .B(VSS), .D(net11), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU23_1 ( .B(VSS), .D(Z), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU23_3 ( .B(VSS), .D(Z), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU23_0 ( .B(VSS), .D(Z), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU23_2 ( .B(VSS), .D(Z), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u15_0 ( .B(VSS), .D(net11), .G(I), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU21_0 ( .B(VDD), .D(Z), .G(net11), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU21_1 ( .B(VDD), .D(Z), .G(net11), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u3_0 ( .B(VDD), .D(net11), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU21_3 ( .B(VDD), .D(Z), .G(net11), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u3_1 ( .B(VDD), .D(net11), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU21_2 ( .B(VDD), .D(Z), .G(net11), .S(VDD) ); 

endmodule

module ND3D3 ( A1, A2, A3, ZN ); 
input A1, A2, A3, ZN;

Switch_PMOS_n12_X1_Y1 MMI0_0_M_u3 ( .B(VDD), .D(ZN), .G(A3), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_0_M_u1 ( .B(VDD), .D(ZN), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_2_M_u3 ( .B(VDD), .D(ZN), .G(A3), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_2_M_u2 ( .B(VDD), .D(ZN), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_1_M_u2 ( .B(VDD), .D(ZN), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_1_M_u3 ( .B(VDD), .D(ZN), .G(A3), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_0_M_u2 ( .B(VDD), .D(ZN), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_2_M_u1 ( .B(VDD), .D(ZN), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_1_M_u1 ( .B(VDD), .D(ZN), .G(A1), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MMI0_1_M_u5 ( .B(VSS), .D(net69), .G(A2), .S(net72) ); 
Switch_NMOS_n12_X1_Y1 MMI0_2_M_u6 ( .B(VSS), .D(net56), .G(A3), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI0_1_M_u4 ( .B(VSS), .D(ZN), .G(A1), .S(net69) ); 
Switch_NMOS_n12_X1_Y1 MMI0_2_M_u4 ( .B(VSS), .D(ZN), .G(A1), .S(net53) ); 
Switch_NMOS_n12_X1_Y1 MMI0_2_M_u5 ( .B(VSS), .D(net53), .G(A2), .S(net56) ); 
Switch_NMOS_n12_X1_Y1 MMI0_1_M_u6 ( .B(VSS), .D(net72), .G(A3), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI0_0_M_u6 ( .B(VSS), .D(net44), .G(A3), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI0_0_M_u5 ( .B(VSS), .D(net40), .G(A2), .S(net44) ); 
Switch_NMOS_n12_X1_Y1 MMI0_0_M_u4 ( .B(VSS), .D(ZN), .G(A1), .S(net40) ); 

endmodule

module AN3D1 ( A1, A2, A3, Z ); 
input A1, A2, A3, Z;

Switch_NMOS_n12_X1_Y1 MM_u4_M_u6 ( .B(VSS), .D(net13), .G(A3), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u3_M_u2 ( .B(VSS), .D(Z), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u4_M_u5 ( .B(VSS), .D(net5), .G(A2), .S(net13) ); 
Switch_NMOS_n12_X1_Y1 MM_u4_M_u4 ( .B(VSS), .D(net11), .G(A1), .S(net5) ); 
Switch_PMOS_n12_X1_Y1 MM_u3_M_u3 ( .B(VDD), .D(Z), .G(net11), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u3 ( .B(VDD), .D(net11), .G(A3), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u1 ( .B(VDD), .D(net11), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u2 ( .B(VDD), .D(net11), .G(A2), .S(VDD) ); 

endmodule

module DEL_7b ( CKOUT, EN, LSB<1>, LSB<2>, LSB<3>, REF_CLK, SEL0, SEL1, SEL2, SEL3, SEL_DL ); 
input CKOUT, EN, LSB<1>, LSB<2>, LSB<3>, REF_CLK, SEL0, SEL1, SEL2, SEL3, SEL_DL;

DEL_3x1_BIN XI29 ( .DEL_IN(net87), .DEL_OUT(net82), .LSB<3>(LSB<3>), .LSB<2>(LSB<2>), .LSB<1>(LSB<1>) ); 
OR2D0 XI14 ( .A1(SEL3), .A2(SEL2), .Z(S2T<1>) ); 
OR2D0 XI23 ( .A1(SEL1), .A2(S2T<1>), .Z(net90) ); 
OR2D0 XI27 ( .A1(SEL1), .A2(S2T<3>), .Z(net88) ); 
OR2D0 XI25 ( .A1(SEL1), .A2(S2T<2>), .Z(net89) ); 
OR2D0 XI24 ( .A1(SEL0), .A2(S2T<1>), .Z(net83) ); 
OR2D0 XI28 ( .A1(SEL0), .A2(S2T<3>), .Z(net85) ); 
OR2D0 XI26 ( .A1(SEL0), .A2(S2T<2>), .Z(net84) ); 
MUX2D0 XI0 ( .I0(REF_CLK), .I1(net82), .S(SEL_DL), .Z(net91) ); 
DEL_3x1 XI19 ( .DEL_IN(net91), .DEL_OUT(net76), .EN(S2T<0>), .SEL0(net83), .SEL1(net90) ); 
DEL_4x1 XI22 ( .DEL_IN(net80), .DEL_OUT(net86), .EN(S2T<3>), .SEL0(SEL0), .SEL1(SEL1) ); 
DEL_4x1 XI21 ( .DEL_IN(net78), .DEL_OUT(net80), .EN(S2T<2>), .SEL0(net85), .SEL1(net88) ); 
DEL_4x1 XI20 ( .DEL_IN(net76), .DEL_OUT(net78), .EN(S2T<1>), .SEL0(net84), .SEL1(net89) ); 
AN2D0 XI18 ( .A1(SEL3), .A2(SEL2), .Z(S2T<3>) ); 
BUFFD0 XI16 ( .I(EN), .Z(S2T<0>) ); 
BUFFD0 XI17 ( .I(SEL3), .Z(S2T<2>) ); 
CKBD2 XI2 ( .I(net82), .Z(CKOUT) ); 
MUX4ND0 XI3 ( .I0(net76), .I1(net78), .I2(net80), .I3(net86), .S0(SEL2), .S1(SEL3), .ZN(net87) ); 

endmodule

module DEL_3x1_BIN ( DEL_IN, DEL_OUT, LSB<1>, LSB<2>, LSB<3> ); 
input DEL_IN, DEL_OUT, LSB<1>, LSB<2>, LSB<3>;

MUX2D1 XI9 ( .I0(net020), .I1(net027), .S(net033), .Z(DEL_OUT) ); 
DEL0 XI1 ( .I(net010), .Z(net032) ); 
DEL0 XI19 ( .I(LSB<3>), .Z(net013) ); 
DEL015 XI20 ( .I(LSB<2>), .Z(net035) ); 
DEL015 XI5 ( .I(net030), .Z(net029) ); 
DEL015 XI21 ( .I(LSB<1>), .Z(net033) ); 
MUX2D0 XI3 ( .I0(DEL_IN), .I1(net032), .S(net013), .Z(net019) ); 
MUX2D0 XI6 ( .I0(net019), .I1(net029), .S(net035), .Z(net020) ); 
DEL005 XI8 ( .I(net028), .Z(net027) ); 
INVD0 XI14 ( .I(DEL_IN), .ZN(net05) ); 
INVD0 XI16 ( .I(net019), .ZN(net018) ); 
INVD0 XI17 ( .I(net020), .ZN(net023) ); 
ND2D0 XI15 ( .A1(net018), .A2(LSB<2>), .ZN(net030) ); 
ND2D0 XI13 ( .A1(net05), .A2(LSB<3>), .ZN(net010) ); 
ND2D0 XI18 ( .A1(net023), .A2(LSB<1>), .ZN(net028) ); 

endmodule

module MUX2D1 ( I0, I1, S, Z ); 
input I0, I1, S, Z;

Switch_PMOS_n12_X1_Y1 MMI14_M_u3 ( .B(VDD), .D(net5), .G(I1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI16_M_u3 ( .B(VDD), .D(net37), .G(I0), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU29_M_u3 ( .B(VDD), .D(Z), .G(net27), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI15_M_u3 ( .B(VDD), .D(net9), .G(S), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI13_M_u2 ( .B(VDD), .D(net5), .G(net9), .S(net27) ); 
Switch_PMOS_n12_X1_Y1 MMU18_M_u2 ( .B(VDD), .D(net37), .G(S), .S(net27) ); 
Switch_NMOS_n12_X1_Y1 MMU18_M_u3 ( .B(VSS), .D(net37), .G(net9), .S(net27) ); 
Switch_NMOS_n12_X1_Y1 MMI15_M_u2 ( .B(VSS), .D(net9), .G(S), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI16_M_u2 ( .B(VSS), .D(net37), .G(I0), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI13_M_u3 ( .B(VSS), .D(net5), .G(S), .S(net27) ); 
Switch_NMOS_n12_X1_Y1 MMI14_M_u2 ( .B(VSS), .D(net5), .G(I1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU29_M_u2 ( .B(VSS), .D(Z), .G(net27), .S(VSS) ); 

endmodule

module DEL0 ( I, Z ); 
input I, Z;

Switch_NMOS_n12_X1_Y1 MMU7_M_u2 ( .B(VSS), .D(net11), .G(net25), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI2_M_u2 ( .B(VSS), .D(Z), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI1_M_u2 ( .B(VSS), .D(net5), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU5_M_u2 ( .B(VSS), .D(net25), .G(net5), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI2_M_u3 ( .B(VDD), .D(Z), .G(net11), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU5_M_u3 ( .B(VDD), .D(net25), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u3 ( .B(VDD), .D(net5), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU7_M_u3 ( .B(VDD), .D(net11), .G(net25), .S(VDD) ); 

endmodule

module MUX2D0 ( I0, I1, S, Z ); 
input I0, I1, S, Z;

Switch_PMOS_n12_X1_Y1 MMU29_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI15_M_u3 ( .B(VDD), .D(net17), .G(S), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI111 ( .B(VDD), .D(net13), .G(I0), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI24 ( .B(VDD), .D(net9), .G(I1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI5 ( .B(VDD), .D(net5), .G(S), .S(net13) ); 
Switch_PMOS_n12_X1_Y1 MMI25 ( .B(VDD), .D(net5), .G(net17), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MMI15_M_u2 ( .B(VSS), .D(net17), .G(S), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI20 ( .B(VSS), .D(net36), .G(I1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI12 ( .B(VSS), .D(net5), .G(net17), .S(net25) ); 
Switch_NMOS_n12_X1_Y1 MMI21 ( .B(VSS), .D(net5), .G(S), .S(net36) ); 
Switch_NMOS_n12_X1_Y1 MMU29_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI19 ( .B(VSS), .D(net25), .G(I0), .S(VSS) ); 

endmodule

module DEL005 ( I, Z ); 
input I, Z;

Switch_PMOS_n12_X1_Y1 MMI2_M_u3 ( .B(VDD), .D(Z), .G(net11), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI3 ( .B(VDD), .D(net5), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI10 ( .B(VDD), .D(net11), .G(I), .S(net5) ); 
Switch_NMOS_n12_X1_Y1 MMI13 ( .B(VSS), .D(net5), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI2_M_u2 ( .B(VSS), .D(Z), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI12 ( .B(VSS), .D(net11), .G(I), .S(net5) ); 

endmodule

module OR2D0 ( A1, A2, Z ); 
input A1, A2, Z;

Switch_NMOS_n12_X1_Y1 MMU1_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u7_M_u4 ( .B(VSS), .D(net5), .G(A1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u7_M_u3 ( .B(VSS), .D(net5), .G(A2), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU1_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u7_M_u1 ( .B(VDD), .D(net17), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u7_M_u2 ( .B(VDD), .D(net5), .G(A1), .S(net17) ); 

endmodule

module DEL_3x1 ( DEL_IN, DEL_OUT, EN, SEL0, SEL1 ); 
input DEL_IN, DEL_OUT, EN, SEL0, SEL1;

AN2D0 XI18 ( .A1(SEL1), .A2(SEL0), .Z(S2T<3>) ); 
AN2D0 XI8 ( .A1(net12), .A2(S2T<3>), .Z(net18) ); 
AN2D0 XI6 ( .A1(net11), .A2(S2T<2>), .Z(net19) ); 
AN2D0 XI4 ( .A1(net21), .A2(S2T<1>), .Z(net20) ); 
AN2D0 XI2 ( .A1(DEL_IN), .A2(S2T<0>), .Z(net21) ); 
DEL1 XI9 ( .I(net18), .Z(net17) ); 
DEL1 XI7 ( .I(net19), .Z(net12) ); 
DEL1 XI5 ( .I(net20), .Z(net11) ); 
MUX4D0 XI11 ( .I0(net21), .I1(net11), .I2(net12), .I3(net17), .S0(SEL0), .S1(SEL1), .Z(DEL_OUT) ); 
BUFFD0 XI17 ( .I(SEL1), .Z(S2T<2>) ); 
BUFFD0 XI16 ( .I(EN), .Z(S2T<0>) ); 
OR2D0 XI14 ( .A1(SEL1), .A2(SEL0), .Z(S2T<1>) ); 

endmodule

module DEL1 ( I, Z ); 
input I, Z;

Switch_NMOS_n12_X1_Y1 MMU7_M_u2 ( .B(VSS), .D(net11), .G(net25), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI2_M_u2 ( .B(VSS), .D(Z), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI1_M_u2 ( .B(VSS), .D(net5), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU5_M_u2 ( .B(VSS), .D(net25), .G(net5), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI2_M_u3 ( .B(VDD), .D(Z), .G(net11), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU5_M_u3 ( .B(VDD), .D(net25), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u3 ( .B(VDD), .D(net5), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU7_M_u3 ( .B(VDD), .D(net11), .G(net25), .S(VDD) ); 

endmodule

module MUX4D0 ( I0, I1, I2, I3, S0, S1, Z ); 
input I0, I1, I2, I3, S0, S1, Z;

Switch_PMOS_n12_X1_Y1 MMU18_M_u3 ( .B(VDD), .D(Z), .G(net20), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI53_M_u2 ( .B(VDD), .D(net97), .G(S1), .S(net20) ); 
Switch_PMOS_n12_X1_Y1 MMI51_M_u3 ( .B(VDD), .D(net37), .G(I3), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI55_M_u2 ( .B(VDD), .D(net37), .G(net61), .S(net104) ); 
Switch_PMOS_n12_X1_Y1 MMI50_M_u3 ( .B(VDD), .D(net33), .G(S1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI48_M_u3 ( .B(VDD), .D(net61), .G(S0), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI49_M_u3 ( .B(VDD), .D(net81), .G(I2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI47_M_u3 ( .B(VDD), .D(net5), .G(I1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI56_M_u2 ( .B(VDD), .D(net104), .G(net33), .S(net20) ); 
Switch_PMOS_n12_X1_Y1 MMI54_M_u2 ( .B(VDD), .D(net81), .G(S0), .S(net104) ); 
Switch_PMOS_n12_X1_Y1 MMI40_M_u2 ( .B(VDD), .D(net9), .G(S0), .S(net97) ); 
Switch_PMOS_n12_X1_Y1 MMI52_M_u2 ( .B(VDD), .D(net5), .G(net61), .S(net97) ); 
Switch_PMOS_n12_X1_Y1 MMI46_M_u3 ( .B(VDD), .D(net9), .G(I0), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MMI55_M_u3 ( .B(VSS), .D(net37), .G(S0), .S(net104) ); 
Switch_NMOS_n12_X1_Y1 MMI53_M_u3 ( .B(VSS), .D(net97), .G(net33), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMI47_M_u2 ( .B(VSS), .D(net5), .G(I1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI51_M_u2 ( .B(VSS), .D(net37), .G(I3), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI52_M_u3 ( .B(VSS), .D(net5), .G(S0), .S(net97) ); 
Switch_NMOS_n12_X1_Y1 MMI54_M_u3 ( .B(VSS), .D(net81), .G(net61), .S(net104) ); 
Switch_NMOS_n12_X1_Y1 MMI56_M_u3 ( .B(VSS), .D(net104), .G(S1), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMI40_M_u3 ( .B(VSS), .D(net9), .G(net61), .S(net97) ); 
Switch_NMOS_n12_X1_Y1 MMI49_M_u2 ( .B(VSS), .D(net81), .G(I2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU18_M_u2 ( .B(VSS), .D(Z), .G(net20), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI48_M_u2 ( .B(VSS), .D(net61), .G(S0), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI46_M_u2 ( .B(VSS), .D(net9), .G(I0), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI50_M_u2 ( .B(VSS), .D(net33), .G(S1), .S(VSS) ); 

endmodule

module BUFFD0 ( I, Z ); 
input I, Z;

Switch_NMOS_n12_X1_Y1 MMI2_M_u2 ( .B(VSS), .D(net5), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI1_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI2_M_u3 ( .B(VDD), .D(net5), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 

endmodule

module DEL_4x1 ( DEL_IN, DEL_OUT, EN, SEL0, SEL1 ); 
input DEL_IN, DEL_OUT, EN, SEL0, SEL1;

AN2D0 XI18 ( .A1(SEL1), .A2(SEL0), .Z(S2T<3>) ); 
AN2D0 XI8 ( .A1(net12), .A2(S2T<3>), .Z(net18) ); 
AN2D0 XI6 ( .A1(net11), .A2(S2T<2>), .Z(net19) ); 
AN2D0 XI4 ( .A1(net10), .A2(S2T<1>), .Z(net20) ); 
AN2D0 XI2 ( .A1(DEL_IN), .A2(S2T<0>), .Z(net21) ); 
DEL1 XI9 ( .I(net18), .Z(net17) ); 
DEL1 XI7 ( .I(net19), .Z(net12) ); 
DEL1 XI5 ( .I(net20), .Z(net11) ); 
DEL1 XI3 ( .I(net21), .Z(net10) ); 
MUX4D0 XI11 ( .I0(net10), .I1(net11), .I2(net12), .I3(net17), .S0(SEL0), .S1(SEL1), .Z(DEL_OUT) ); 
BUFFD0 XI17 ( .I(SEL1), .Z(S2T<2>) ); 
BUFFD0 XI16 ( .I(EN), .Z(S2T<0>) ); 
OR2D0 XI14 ( .A1(SEL1), .A2(SEL0), .Z(S2T<1>) ); 

endmodule

module CKBD2 ( I, Z ); 
input I, Z;

Switch_NMOS_n12_X1_Y1 MMU23_1 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u15 ( .B(VSS), .D(net5), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU23_0 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MM_u3 ( .B(VDD), .D(net5), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU21_0 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU21_1 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 

endmodule

module MUX4ND0 ( I0, I1, I2, I3, S0, S1, ZN ); 
input I0, I1, I2, I3, S0, S1, ZN;

Switch_NMOS_n12_X1_Y1 MMI47_M_u2 ( .B(VSS), .D(net17), .G(I2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI51_M_u3 ( .B(VSS), .D(net20), .G(S1), .S(ZN) ); 
Switch_NMOS_n12_X1_Y1 MMI55_M_u2 ( .B(VSS), .D(net61), .G(I0), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI50_M_u3 ( .B(VSS), .D(net33), .G(net83), .S(ZN) ); 
Switch_NMOS_n12_X1_Y1 MMI48_M_u3 ( .B(VSS), .D(net61), .G(net67), .S(net33) ); 
Switch_NMOS_n12_X1_Y1 MMI58_M_u2 ( .B(VSS), .D(net67), .G(S0), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI49_M_u3 ( .B(VSS), .D(net5), .G(S0), .S(net33) ); 
Switch_NMOS_n12_X1_Y1 MMI52_M_u3 ( .B(VSS), .D(net17), .G(net67), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMI54_M_u3 ( .B(VSS), .D(net9), .G(S0), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMI57_M_u2 ( .B(VSS), .D(net9), .G(I3), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI56_M_u2 ( .B(VSS), .D(net5), .G(I1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU18_M_u2 ( .B(VSS), .D(net83), .G(S1), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI55_M_u3 ( .B(VDD), .D(net61), .G(I0), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU18_M_u3 ( .B(VDD), .D(net83), .G(S1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI58_M_u3 ( .B(VDD), .D(net67), .G(S0), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI51_M_u2 ( .B(VDD), .D(net20), .G(net83), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MMI57_M_u3 ( .B(VDD), .D(net9), .G(I3), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI56_M_u3 ( .B(VDD), .D(net5), .G(I1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI47_M_u3 ( .B(VDD), .D(net17), .G(I2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI49_M_u2 ( .B(VDD), .D(net5), .G(net67), .S(net33) ); 
Switch_PMOS_n12_X1_Y1 MMI48_M_u2 ( .B(VDD), .D(net61), .G(S0), .S(net33) ); 
Switch_PMOS_n12_X1_Y1 MMI54_M_u2 ( .B(VDD), .D(net9), .G(net67), .S(net20) ); 
Switch_PMOS_n12_X1_Y1 MMI52_M_u2 ( .B(VDD), .D(net17), .G(S0), .S(net20) ); 
Switch_PMOS_n12_X1_Y1 MMI50_M_u2 ( .B(VDD), .D(net33), .G(S1), .S(ZN) ); 

endmodule

module MDLL_LOGIC_VLOG ( CODE<0>, CODE<1>, CODE<2>, CODE<3>, CODE<4>, CODE<5>, CODE<6>, COMP, EN0DLL, FRCODE<0>, FRCODE<1>, FRCODE<2>, FRCODE<3>, FRCODE<4>, FRCODE<5>, FRCODE<6>, FREE0RUN, REFCLK, SAR0EN, STATUS<0>, STATUS<1>, STATUS<2>, TRK0EN ); 
input CODE<0>, CODE<1>, CODE<2>, CODE<3>, CODE<4>, CODE<5>, CODE<6>, COMP, EN0DLL, FRCODE<0>, FRCODE<1>, FRCODE<2>, FRCODE<3>, FRCODE<4>, FRCODE<5>, FRCODE<6>, FREE0RUN, REFCLK, SAR0EN, STATUS<0>, STATUS<1>, STATUS<2>, TRK0EN;

CKND0 XU85 ( .I(N130), .ZN(N131) ); 
CKND0 XU2 ( .I(SAR0CODE<5>), .ZN(N2) ); 
CKND0 XU3 ( .I(SAR0CODE<2>), .ZN(N3) ); 
CKND0 XU4 ( .I(SAR0CODE<4>), .ZN(N4) ); 
CKND0 XU5 ( .I(SAR0CODE<0>), .ZN(N5) ); 
CKND0 XU6 ( .I(STATUS<0>), .ZN(N6) ); 
CKND0 XU1 ( .I(FREE0RUN), .ZN(N1) ); 
AO22D0 XU56 ( .A1(N41), .A2(N75), .B1(N27), .B2(N53), .Z(N89) ); 
AO22D0 XU100 ( .A1(N39), .A2(N75), .B1(N25), .B2(N53), .Z(N125) ); 
AO22D0 XU106 ( .A1(N1), .A2(SAR0CODE<3>), .B1(FRCODE<3>), .B2(FREE0RUN), .Z(CODE<3>) ); 
AO22D0 XU105 ( .A1(N1), .A2(SAR0CODE<2>), .B1(FRCODE<2>), .B2(FREE0RUN), .Z(CODE<2>) ); 
AO22D0 XU104 ( .A1(N1), .A2(SAR0CODE<1>), .B1(FRCODE<1>), .B2(FREE0RUN), .Z(CODE<1>) ); 
AO22D0 XU103 ( .A1(N1), .A2(SAR0CODE<0>), .B1(FRCODE<0>), .B2(FREE0RUN), .Z(CODE<0>) ); 
MOAI22D1 XU156 ( .A1(N136), .A2(FREE0RUN), .B1(FRCODE<6>), .B2(FREE0RUN), .ZN(CODE<6>) ); 
MOAI22D1 XU155 ( .A1(FREE0RUN), .A2(N2), .B1(FRCODE<5>), .B2(FREE0RUN), .ZN(CODE<5>) ); 
MOAI22D1 XU154 ( .A1(FREE0RUN), .A2(N4), .B1(FRCODE<4>), .B2(FREE0RUN), .ZN(CODE<4>) ); 
CKAN2D0 XU75 ( .A1(N111), .A2(N6), .Z(N620) ); 
CKAN2D0 XU69 ( .A1(N110), .A2(N56), .Z(N71) ); 
CKAN2D0 XU90 ( .A1(N69), .A2(N110), .Z(N70) ); 
AN2XD1 XU107 ( .A1(N64), .A2(N73), .Z(N76) ); 
AN2XD1 XU68 ( .A1(N113), .A2(N6), .Z(N56) ); 
AN2XD1 XU63 ( .A1(N640), .A2(N108), .Z(N55) ); 
AN2XD1 XU92 ( .A1(N113), .A2(STATUS<0>), .Z(N69) ); 
AN2XD1 XU65 ( .A1(N55), .A2(N69), .Z(N68) ); 
AN3D0 XU81 ( .A1(N82), .A2(N130), .A3(N81), .Z(N73) ); 
AN3D0 XU89 ( .A1(N111), .A2(N6), .A3(N110), .Z(N74) ); 
AN3XD1 XU57 ( .A1(COMP), .A2(N88), .A3(N118), .Z(N53) ); 
AN3XD1 XU91 ( .A1(N55), .A2(STATUS<0>), .A3(N111), .Z(N67) ); 
ND2D1 XU73 ( .A1(N29), .A2(N53), .ZN(N610) ); 
ND2D1 XU72 ( .A1(SAR0CODE<4>), .A2(N101), .ZN(N600) ); 
ND2D1 XU96 ( .A1(N45), .A2(N75), .ZN(N119) ); 
ND2D1 XU95 ( .A1(N31), .A2(N53), .ZN(N120) ); 
ND2D1 XU101 ( .A1(N6), .A2(N85), .ZN(N107) ); 
ND2D1 XU67 ( .A1(STATUS<1>), .A2(STATUS<0>), .ZN(N590) ); 
ND2D1 XU79 ( .A1(N630), .A2(N590), .ZN(N640) ); 
ND2D1 XU66 ( .A1(N640), .A2(N108), .ZN(N110) ); 
INVD1 XU80 ( .I(STATUS<2>), .ZN(N630) ); 
INVD1 XU58 ( .I(N590), .ZN(N109) ); 
INVD1 XU77 ( .I(N111), .ZN(N113) ); 
CKND2D2 XU55 ( .A1(N107), .A2(N590), .ZN(N111) ); 
CKND2D1 XU133 ( .A1(N97), .A2(N96), .ZN(N46) ); 
CKND2D1 XU153 ( .A1(N133), .A2(N132), .ZN(N48) ); 
CKND2D1 XU121 ( .A1(N129), .A2(N91), .ZN(N84) ); 
CKND2D1 XU60 ( .A1(STATUS<2>), .A2(N109), .ZN(N108) ); 
CKND1 XU150 ( .I(SAR0CODE<1>), .ZN(N127) ); 
CKND1 XU141 ( .I(N115), .ZN(N103) ); 
CKND1 XU123 ( .I(N94), .ZN(N83) ); 
CKND1 XU138 ( .I(N104), .ZN(N114) ); 
CKND1 XU125 ( .I(SAR0EN), .ZN(N87) ); 
CKND1 XU139 ( .I(N101), .ZN(N102) ); 
CKND1 XU126 ( .I(STATUS<1>), .ZN(N85) ); 
CKND1 XU129 ( .I(SAR0CODE<3>), .ZN(N92) ); 
CKND1 XU134 ( .I(N98), .ZN(N99) ); 
CKND1 XU120 ( .I(N137), .ZN(N91) ); 
CKND1 XU119 ( .I(N124), .ZN(N129) ); 
CKND1 XU117 ( .I(COMP), .ZN(N86) ); 
CKND1 XU115 ( .I(N80), .ZN(N88) ); 
CKND2D0 XU87 ( .A1(N114), .A2(N2), .ZN(N117) ); 
CKND2D0 XU71 ( .A1(STATUS<2>), .A2(N109), .ZN(N58) ); 
IND2D0 XU157 ( .A1(SAR0CODE<1>), .B1(N5), .ZN(N137) ); 
IND2D0 XU82 ( .A1(N107), .B1(N630), .ZN(N118) ); 
MDLL_LOGIC_VLOG_DW01_sub_J17_0 XSUB049 ( .A<6>(SAR0CODE<6>), .A<5>(N2), .A<4>(SAR0CODE<4>), .A<3>(SAR0CODE<3>), .A<2>(N3), .A<1>(SAR0CODE<1>), .A<0>(N5), .B<6>(N74), .B<5>(N70), .B<4>(N71), .B<3>(N67), .B<2>(N72), .B<1>(N68), .B<0>(N66), .DIFF<6>(N45), .DIFF<5>(N44), .DIFF<4>(N43), .DIFF<3>(N42), .DIFF<2>(N41), .DIFF<1>(N40), .DIFF<0>(N39), .IN0(SAR0CODE<0>), .IN1(SAR0CODE<2>), .IN2(SAR0CODE<5>) ); 
MDLL_LOGIC_VLOG_DW01_add_J16_0 XADD049 ( .A<6>(SAR0CODE<6>), .A<5>(SAR0CODE<5>), .A<4>(N4), .A<3>(SAR0CODE<3>), .A<2>(N3), .A<1>(SAR0CODE<1>), .A<0>(SAR0CODE<0>), .B<6>(N74), .B<5>(N70), .B<4>(N71), .B<3>(N67), .B<2>(N72), .B<1>(N68), .B<0>(N66), .IN0(SAR0CODE<4>), .IN1(SAR0CODE<2>), .SUM<6>(N31), .SUM<5>(N30), .SUM<4>(N29), .SUM<3>(N28), .SUM<2>(N27), .SUM<1>(N26), .SUM<0>(N25) ); 
INVD0 XU114 ( .I(N58), .ZN(N82) ); 
IND2D1 XU99 ( .A1(N123), .B1(N122), .ZN(N430) ); 
IND2D1 XU118 ( .A1(COMP0REG), .B1(N86), .ZN(N81) ); 
IND2D1 XU116 ( .A1(TRK0EN), .B1(N82), .ZN(N130) ); 
IND3D1 XU93 ( .A1(N81), .B1(N82), .B2(N130), .ZN(N124) ); 
MDLL_LOGIC_VLOG_DW01_inc_0 XADD051 ( .A<6>(SAR0CODE<6>), .A<5>(SAR0CODE<5>), .A<4>(SAR0CODE<4>), .A<3>(SAR0CODE<3>), .A<2>(SAR0CODE<2>), .A<1>(SAR0CODE<1>), .A<0>(SAR0CODE<0>), .SUM<6>(N64), .SUM<5>(N63), .SUM<4>(N62), .SUM<3>(N61), .SUM<2>(N60), .SUM<1>(N59) ); 
OAI21D1 XU131 ( .A1(N3), .A2(N92), .B(N98), .ZN(N95) ); 
OAI21D1 XU151 ( .A1(N5), .A2(N127), .B(N137), .ZN(N128) ); 
OAI21D1 XU140 ( .A1(N4), .A2(N124), .B(N102), .ZN(N115) ); 
OAI21D1 XU135 ( .A1(N99), .A2(N124), .B(N130), .ZN(N101) ); 
OAI21D1 XU122 ( .A1(N91), .A2(N124), .B(N130), .ZN(N94) ); 
ND3D1 XU74 ( .A1(N600), .A2(N610), .A3(N104), .ZN(N100) ); 
ND3D1 XU94 ( .A1(N120), .A2(N119), .A3(N118), .ZN(N121) ); 
ND3D1 XU130 ( .A1(N91), .A2(N92), .A3(N3), .ZN(N98) ); 
ND3D1 XU137 ( .A1(N99), .A2(N129), .A3(N4), .ZN(N104) ); 
CKAN2D1 XU70 ( .A1(N113), .A2(N6), .Z(N65) ); 
AN2D2 XU64 ( .A1(N55), .A2(N65), .Z(N66) ); 
AN2D1 XU76 ( .A1(N55), .A2(N620), .Z(N72) ); 
DFCNQD1 XSAR0CODE0REG030 ( .CDN(EN0DLL), .CP(REFCLK), .D(N46), .Q(SAR0CODE<3>) ); 
DFCNQD1 XSAR0CODE0REG040 ( .CDN(EN0DLL), .CP(REFCLK), .D(N450), .Q(SAR0CODE<4>) ); 
DFCNQD1 XSAR0CODE0REG010 ( .CDN(EN0DLL), .CP(REFCLK), .D(N48), .Q(SAR0CODE<1>) ); 
DFCNQD1 XSAR0CODE0REG050 ( .CDN(EN0DLL), .CP(REFCLK), .D(N440), .Q(SAR0CODE<5>) ); 
DFCNQD1 XSAR0CODE0REG020 ( .CDN(EN0DLL), .CP(REFCLK), .D(N47), .Q(SAR0CODE<2>) ); 
DFCNQD1 XCOMP0REG0REG ( .CDN(EN0DLL), .CP(REFCLK), .D(N54), .Q(COMP0REG) ); 
DFCNQD1 XSTATUS0REG010 ( .CDN(EN0DLL), .CP(REFCLK), .D(N51), .Q(STATUS<1>) ); 
DFCNQD1 XSTATUS0REG000 ( .CDN(EN0DLL), .CP(REFCLK), .D(N52), .Q(STATUS<0>) ); 
DFCNQD1 XSTATUS0REG020 ( .CDN(EN0DLL), .CP(REFCLK), .D(N50), .Q(STATUS<2>) ); 
OAI21D0 XU109 ( .A1(N590), .A2(N80), .B(N630), .ZN(N50) ); 
CKXOR2D0 XU78 ( .A1(STATUS<1>), .A2(N79), .Z(N51) ); 
CKXOR2D0 XU112 ( .A1(STATUS<0>), .A2(N88), .Z(N52) ); 
NR2D0 XU110 ( .A1(N6), .A2(N80), .ZN(N79) ); 
ND2D0 XU113 ( .A1(SAR0EN), .A2(N58), .ZN(N80) ); 
OA211D0 XU83 ( .A1(N87), .A2(N86), .B(N118), .C(N58), .Z(N75) ); 
DEL005 XU59 ( .I(COMP), .Z(N54) ); 
AO211D1 XU144 ( .A1(N63), .A2(N73), .B(N106), .C(N105), .Z(N440) ); 
AO211D1 XU127 ( .A1(N60), .A2(N73), .B(N90), .C(N89), .Z(N47) ); 
AO211D1 XU148 ( .A1(N5), .A2(N73), .B(N126), .C(N125), .Z(N49) ); 
MUX2ND0 XU142 ( .I0(N104), .I1(N103), .S(SAR0CODE<5>), .ZN(N106) ); 
MUX2ND0 XU124 ( .I0(N84), .I1(N83), .S(SAR0CODE<2>), .ZN(N90) ); 
MUX2ND0 XU146 ( .I0(N117), .I1(N116), .S(SAR0CODE<6>), .ZN(N123) ); 
MUX2ND0 XU147 ( .I0(N124), .I1(N130), .S(SAR0CODE<0>), .ZN(N126) ); 
DFCNQD4 XSAR0CODE0REG000 ( .CDN(EN0DLL), .CP(REFCLK), .D(N49), .Q(SAR0CODE<0>) ); 
NR2XD0 XU88 ( .A1(N121), .A2(N76), .ZN(N122) ); 
DFSND1 XSAR0CODE0REG060 ( .CP(REFCLK), .D(N430), .Q(SAR0CODE<6>), .QN(N136), .SDN(EN0DLL) ); 
AOI21D0 XU84 ( .A1(N129), .A2(SAR0CODE<5>), .B(N115), .ZN(N116) ); 
AO22D1 XU143 ( .A1(N44), .A2(N75), .B1(N30), .B2(N53), .Z(N105) ); 
AOI22D1 XU132 ( .A1(N42), .A2(N75), .B1(N61), .B2(N73), .ZN(N96) ); 
AOI22D1 XU152 ( .A1(N59), .A2(N73), .B1(N131), .B2(SAR0CODE<1>), .ZN(N132) ); 
AOI222D0 XU98 ( .A1(N28), .A2(N53), .B1(N129), .B2(N95), .C1(SAR0CODE<3>), .C2(N94), .ZN(N97) ); 
AOI222D0 XU97 ( .A1(N40), .A2(N75), .B1(N129), .B2(N128), .C1(N26), .C2(N53), .ZN(N133) ); 
AO221D1 XU86 ( .A1(N43), .A2(N75), .B1(N62), .B2(N73), .C(N100), .Z(N450) ); 

endmodule

module CKND0 ( I, ZN ); 
input I, ZN;

Switch_NMOS_n12_X1_Y1 MM_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MM_u1 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 

endmodule

module AO22D0 ( A1, A2, B1, B2, Z ); 
input A1, A2, B1, B2, Z;

Switch_NMOS_n12_X1_Y1 MMI23 ( .B(VSS), .D(net17), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI8_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI16 ( .B(VSS), .D(net5), .G(B1), .S(net1) ); 
Switch_NMOS_n12_X1_Y1 MMI24 ( .B(VSS), .D(net5), .G(A1), .S(net17) ); 
Switch_NMOS_n12_X1_Y1 MMI22 ( .B(VSS), .D(net1), .G(B2), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI20 ( .B(VDD), .D(net5), .G(A1), .S(net33) ); 
Switch_PMOS_n12_X1_Y1 MM_u2 ( .B(VDD), .D(net33), .G(B2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI19 ( .B(VDD), .D(net5), .G(A2), .S(net33) ); 
Switch_PMOS_n12_X1_Y1 MMI8_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI21 ( .B(VDD), .D(net33), .G(B1), .S(VDD) ); 

endmodule

module MOAI22D1 ( A1, A2, B1, B2, ZN ); 
input A1, A2, B1, B2, ZN;

Switch_NMOS_n12_X1_Y1 MMU1 ( .B(VSS), .D(net37), .G(B1), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMI6 ( .B(VSS), .D(net9), .G(net37), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU9 ( .B(VSS), .D(net9), .G(A1), .S(ZN) ); 
Switch_NMOS_n12_X1_Y1 MMI5 ( .B(VSS), .D(net20), .G(B2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU10 ( .B(VSS), .D(net9), .G(A2), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MMI1 ( .B(VDD), .D(net37), .G(B1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI3 ( .B(VDD), .D(net33), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI4 ( .B(VDD), .D(ZN), .G(A1), .S(net33) ); 
Switch_PMOS_n12_X1_Y1 MMI2 ( .B(VDD), .D(ZN), .G(net37), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU3 ( .B(VDD), .D(net37), .G(B2), .S(VDD) ); 

endmodule

module CKAN2D0 ( A1, A2, Z ); 
input A1, A2, Z;

Switch_PMOS_n12_X1_Y1 MM_u2_M_u2 ( .B(VDD), .D(net5), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u1 ( .B(VDD), .D(net5), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u3_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u4 ( .B(VSS), .D(net21), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u3_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u3 ( .B(VSS), .D(net5), .G(A1), .S(net21) ); 

endmodule

module AN2XD1 ( A1, A2, Z ); 
input A1, A2, Z;

Switch_NMOS_n12_X1_Y1 MM_u2_M_u4 ( .B(VSS), .D(net9), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u3 ( .B(VSS), .D(net5), .G(A1), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MM_u3_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MM_u3_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u2 ( .B(VDD), .D(net5), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u1 ( .B(VDD), .D(net5), .G(A1), .S(VDD) ); 

endmodule

module AN3D0 ( A1, A2, A3, Z ); 
input A1, A2, A3, Z;

Switch_NMOS_n12_X1_Y1 MM_u4_M_u6 ( .B(VSS), .D(net13), .G(A3), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u3_M_u2 ( .B(VSS), .D(Z), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u4_M_u5 ( .B(VSS), .D(net5), .G(A2), .S(net13) ); 
Switch_NMOS_n12_X1_Y1 MM_u4_M_u4 ( .B(VSS), .D(net11), .G(A1), .S(net5) ); 
Switch_PMOS_n12_X1_Y1 MM_u3_M_u3 ( .B(VDD), .D(Z), .G(net11), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u3 ( .B(VDD), .D(net11), .G(A3), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u1 ( .B(VDD), .D(net11), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u2 ( .B(VDD), .D(net11), .G(A2), .S(VDD) ); 

endmodule

module AN3XD1 ( A1, A2, A3, Z ); 
input A1, A2, A3, Z;

Switch_NMOS_n12_X1_Y1 MM_u4_M_u6 ( .B(VSS), .D(net13), .G(A3), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u3_M_u2 ( .B(VSS), .D(Z), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u4_M_u5 ( .B(VSS), .D(net5), .G(A2), .S(net13) ); 
Switch_NMOS_n12_X1_Y1 MM_u4_M_u4 ( .B(VSS), .D(net11), .G(A1), .S(net5) ); 
Switch_PMOS_n12_X1_Y1 MM_u3_M_u3 ( .B(VDD), .D(Z), .G(net11), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u3 ( .B(VDD), .D(net11), .G(A3), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u1 ( .B(VDD), .D(net11), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u2 ( .B(VDD), .D(net11), .G(A2), .S(VDD) ); 

endmodule

module ND2D1 ( A1, A2, ZN ); 
input A1, A2, ZN;

Switch_NMOS_n12_X1_Y1 MMI1_M_u3 ( .B(VSS), .D(ZN), .G(A1), .S(net1) ); 
Switch_NMOS_n12_X1_Y1 MMI1_M_u4 ( .B(VSS), .D(net1), .G(A2), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u1 ( .B(VDD), .D(ZN), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u2 ( .B(VDD), .D(ZN), .G(A2), .S(VDD) ); 

endmodule

module CKND2D2 ( A1, A2, ZN ); 
input A1, A2, ZN;

Switch_PMOS_n12_X1_Y1 MMI0_0_M_u1 ( .B(VDD), .D(ZN), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_1_M_u2 ( .B(VDD), .D(ZN), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_0_M_u2 ( .B(VDD), .D(ZN), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_1_M_u1 ( .B(VDD), .D(ZN), .G(A1), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MMI0_1_M_u4 ( .B(VSS), .D(net24), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI0_0_M_u3 ( .B(VSS), .D(ZN), .G(A1), .S(net17) ); 
Switch_NMOS_n12_X1_Y1 MMI0_1_M_u3 ( .B(VSS), .D(ZN), .G(A1), .S(net24) ); 
Switch_NMOS_n12_X1_Y1 MMI0_0_M_u4 ( .B(VSS), .D(net17), .G(A2), .S(VSS) ); 

endmodule

module CKND2D1 ( A1, A2, ZN ); 
input A1, A2, ZN;

Switch_NMOS_n12_X1_Y1 MMI0_M_u3 ( .B(VSS), .D(ZN), .G(A1), .S(net1) ); 
Switch_NMOS_n12_X1_Y1 MMI0_M_u4 ( .B(VSS), .D(net1), .G(A2), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI0_M_u1 ( .B(VDD), .D(ZN), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_M_u2 ( .B(VDD), .D(ZN), .G(A2), .S(VDD) ); 

endmodule

module CKND1 ( I, ZN ); 
input I, ZN;

Switch_NMOS_n12_X1_Y1 MM_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MM_u1 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 

endmodule

module CKND2D0 ( A1, A2, ZN ); 
input A1, A2, ZN;

Switch_NMOS_n12_X1_Y1 MMU1_M_u3 ( .B(VSS), .D(ZN), .G(A1), .S(net1) ); 
Switch_NMOS_n12_X1_Y1 MMU1_M_u4 ( .B(VSS), .D(net1), .G(A2), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU1_M_u2 ( .B(VDD), .D(ZN), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU1_M_u1 ( .B(VDD), .D(ZN), .G(A1), .S(VDD) ); 

endmodule

module IND2D0 ( A1, B1, ZN ); 
input A1, B1, ZN;

Switch_PMOS_n12_X1_Y1 MMI2_M_u3 ( .B(VDD), .D(net9), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI11 ( .B(VDD), .D(VDD), .G(B1), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MM_u16 ( .B(VDD), .D(VDD), .G(net9), .S(ZN) ); 
Switch_NMOS_n12_X1_Y1 MMI13 ( .B(VSS), .D(net21), .G(net9), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI2_M_u2 ( .B(VSS), .D(net9), .G(A1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI12 ( .B(VSS), .D(ZN), .G(B1), .S(net21) ); 

endmodule

module MDLL_LOGIC_VLOG_DW01_sub_J17_0 ( A<0>, A<1>, A<2>, A<3>, A<4>, A<5>, A<6>, B<0>, B<1>, B<2>, B<3>, B<4>, B<5>, B<6>, DIFF<0>, DIFF<1>, DIFF<2>, DIFF<3>, DIFF<4>, DIFF<5>, DIFF<6>, IN0, IN1, IN2 ); 
input A<0>, A<1>, A<2>, A<3>, A<4>, A<5>, A<6>, B<0>, B<1>, B<2>, B<3>, B<4>, B<5>, B<6>, DIFF<0>, DIFF<1>, DIFF<2>, DIFF<3>, DIFF<4>, DIFF<5>, DIFF<6>, IN0, IN1, IN2;

ND2D1 XU35 ( .A1(N1), .A2(N16), .ZN(N15) ); 
ND2D1 XU45 ( .A1(N10), .A2(N12), .ZN(N22) ); 
ND2D1 XU34 ( .A1(N1), .A2(N18), .ZN(N24) ); 
ND2D1 XU38 ( .A1(A<3>), .A2(N41), .ZN(N36) ); 
ND2D1 XU15 ( .A1(IN1), .A2(N44), .ZN(N35) ); 
ND2D1 XU6 ( .A1(B<3>), .A2(N42), .ZN(N37) ); 
ND2D1 XU37 ( .A1(A<1>), .A2(N54), .ZN(N27) ); 
ND2D1 XU7 ( .A1(B<1>), .A2(N55), .ZN(N29) ); 
ND2D1 XU10 ( .A1(N23), .A2(N18), .ZN(N10) ); 
ND2D1 XU32 ( .A1(N48), .A2(N29), .ZN(N26) ); 
IND2D2 XU9 ( .A1(B<0>), .B1(IN0), .ZN(N51) ); 
CKND1 XU55 ( .I(N18), .ZN(N17) ); 
CKND1 XU62 ( .I(N35), .ZN(N43) ); 
CKND1 XU13 ( .I(N25), .ZN(N14) ); 
CKND1 XU60 ( .I(N37), .ZN(N34) ); 
CKND1 XU54 ( .I(N9), .ZN(N11) ); 
CKND1 XU64 ( .I(N51), .ZN(N48) ); 
AO21D0 XU26 ( .A1(B<0>), .A2(A<0>), .B(N48), .Z(DIFF<0>) ); 
CKND2D0 XU8 ( .A1(N37), .A2(N36), .ZN(N40) ); 
CKND2D0 XU25 ( .A1(N51), .A2(N52), .ZN(N50) ); 
CKND2D0 XU24 ( .A1(N29), .A2(N27), .ZN(N49) ); 
CKND2D0 XU20 ( .A1(B<2>), .A2(A<2>), .ZN(N38) ); 
AN2XD1 XU30 ( .A1(N38), .A2(N35), .Z(N2) ); 
AN2XD1 XU28 ( .A1(N38), .A2(N37), .Z(N1) ); 
IND2D1 XU46 ( .A1(IN2), .B1(B<5>), .ZN(N9) ); 
IND2D1 XU42 ( .A1(B<4>), .B1(A<4>), .ZN(N12) ); 
IND2D1 XU40 ( .A1(A<4>), .B1(B<4>), .ZN(N18) ); 
INVD1 XU49 ( .I(B<2>), .ZN(N44) ); 
INVD1 XU43 ( .I(A<3>), .ZN(N42) ); 
INVD1 XU39 ( .I(A<1>), .ZN(N55) ); 
CKND0 XU48 ( .I(B<0>), .ZN(N53) ); 
CKND0 XU21 ( .I(B<3>), .ZN(N41) ); 
CKND0 XU19 ( .I(B<1>), .ZN(N54) ); 
CKXOR2D1 XU52 ( .A1(N4), .A2(N5), .Z(DIFF<6>) ); 
CKXOR2D1 XU53 ( .A1(B<6>), .A2(A<6>), .Z(N5) ); 
CKXOR2D1 XU56 ( .A1(N19), .A2(N20), .Z(DIFF<5>) ); 
CKXOR2D1 XU57 ( .A1(B<5>), .A2(IN2), .Z(N20) ); 
CKXOR2D1 XU59 ( .A1(B<4>), .A2(A<4>), .Z(N32) ); 
CKXOR2D1 XU58 ( .A1(N31), .A2(N32), .Z(DIFF<4>) ); 
CKXOR2D1 XU61 ( .A1(N39), .A2(N40), .Z(DIFF<3>) ); 
CKXOR2D1 XU29 ( .A1(N33), .A2(N2), .Z(DIFF<2>) ); 
OAI21D1 XU27 ( .A1(N34), .A2(N35), .B(N36), .ZN(N23) ); 
IND2D0 XU51 ( .A1(IN0), .B1(B<0>), .ZN(N30) ); 
IND2D0 XU50 ( .A1(IN0), .B1(B<0>), .ZN(N47) ); 
ND2D0 XU12 ( .A1(N29), .A2(N30), .ZN(N28) ); 
ND2D0 XU11 ( .A1(N29), .A2(N47), .ZN(N46) ); 
ND3D1 XU47 ( .A1(N26), .A2(N27), .A3(N28), .ZN(N25) ); 
ND3D1 XU5 ( .A1(N26), .A2(N27), .A3(N46), .ZN(N33) ); 
XNR2D1 XU63 ( .A1(N49), .A2(N50), .ZN(DIFF<1>) ); 
NR2D0 XU17 ( .A1(N14), .A2(N15), .ZN(N6) ); 
NR2D0 XU23 ( .A1(IN0), .A2(N53), .ZN(N52) ); 
AOI21D0 XU16 ( .A1(N1), .A2(N33), .B(N23), .ZN(N31) ); 
AOI21D0 XU18 ( .A1(N33), .A2(N38), .B(N43), .ZN(N39) ); 
NR2XD0 XU22 ( .A1(N21), .A2(N22), .ZN(N19) ); 
NR2D1 XU36 ( .A1(N17), .A2(N11), .ZN(N16) ); 
NR2D1 XU33 ( .A1(N14), .A2(N24), .ZN(N21) ); 
NR3D0 XU3 ( .A1(N6), .A2(N7), .A3(N8), .ZN(N4) ); 
INR2D1 XU31 ( .A1(N9), .B1(N10), .ZN(N8) ); 
OAI22D0 XU14 ( .A1(N11), .A2(N12), .B1(B<5>), .B2(A<5>), .ZN(N7) ); 

endmodule

module IND2D2 ( A1, B1, ZN ); 
input A1, B1, ZN;

Switch_PMOS_n12_X1_Y1 MMI3 ( .B(VDD), .D(VDD), .G(net11), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MM_u16 ( .B(VDD), .D(VDD), .G(B1), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MMI9_M_u3 ( .B(VDD), .D(net11), .G(A1), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MMI9_M_u2 ( .B(VSS), .D(net11), .G(A1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI4 ( .B(VSS), .D(net20), .G(B1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI11 ( .B(VSS), .D(net21), .G(B1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI12 ( .B(VSS), .D(ZN), .G(net11), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMI10 ( .B(VSS), .D(ZN), .G(net11), .S(net21) ); 

endmodule

module AO21D0 ( A1, A2, B, Z ); 
input A1, A2, B, Z;

Switch_PMOS_n12_X1_Y1 MMI9 ( .B(VDD), .D(net5), .G(A2), .S(net9) ); 
Switch_PMOS_n12_X1_Y1 MM_u2 ( .B(VDD), .D(net9), .G(B), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI10 ( .B(VDD), .D(net5), .G(A1), .S(net9) ); 
Switch_PMOS_n12_X1_Y1 MMI8_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MMI11 ( .B(VSS), .D(net5), .G(A1), .S(net25) ); 
Switch_NMOS_n12_X1_Y1 MMI12 ( .B(VSS), .D(net25), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI8_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI6 ( .B(VSS), .D(net5), .G(B), .S(VSS) ); 

endmodule

module IND2D1 ( A1, B1, ZN ); 
input A1, B1, ZN;

Switch_PMOS_n12_X1_Y1 MMI2_M_u3 ( .B(VDD), .D(net9), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI11 ( .B(VDD), .D(VDD), .G(B1), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MM_u16 ( .B(VDD), .D(VDD), .G(net9), .S(ZN) ); 
Switch_NMOS_n12_X1_Y1 MMI13 ( .B(VSS), .D(net21), .G(net9), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI2_M_u2 ( .B(VSS), .D(net9), .G(A1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI12 ( .B(VSS), .D(ZN), .G(B1), .S(net21) ); 

endmodule

module CKXOR2D1 ( A1, A2, Z ); 
input A1, A2, Z;

Switch_PMOS_n12_X1_Y1 MM_u6_M_u2 ( .B(VDD), .D(net27), .G(A1), .S(net44) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u3 ( .B(VDD), .D(Z), .G(net44), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u5_M_u3 ( .B(VDD), .D(net5), .G(net27), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u8_M_u3 ( .B(VDD), .D(net9), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_M_u2 ( .B(VDD), .D(net5), .G(net9), .S(net44) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u3 ( .B(VDD), .D(net27), .G(A2), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MM_u6_M_u3 ( .B(VSS), .D(net27), .G(net9), .S(net44) ); 
Switch_NMOS_n12_X1_Y1 MMI0_M_u3 ( .B(VSS), .D(net5), .G(A1), .S(net44) ); 
Switch_NMOS_n12_X1_Y1 MM_u8_M_u2 ( .B(VSS), .D(net9), .G(A1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u4_M_u2 ( .B(VSS), .D(Z), .G(net44), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u2 ( .B(VSS), .D(net27), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u5_M_u2 ( .B(VSS), .D(net5), .G(net27), .S(VSS) ); 

endmodule

module OAI21D1 ( A1, A2, B, ZN ); 
input A1, A2, B, ZN;

Switch_PMOS_n12_X1_Y1 MMI16_MI13 ( .B(VDD), .D(net9), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u9 ( .B(VDD), .D(ZN), .G(B), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI16_MI12 ( .B(VDD), .D(ZN), .G(A1), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MM_u3 ( .B(VSS), .D(ZN), .G(A2), .S(net24) ); 
Switch_NMOS_n12_X1_Y1 MM_u4 ( .B(VSS), .D(net24), .G(B), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2 ( .B(VSS), .D(ZN), .G(A1), .S(net24) ); 

endmodule

module ND3D1 ( A1, A2, A3, ZN ); 
input A1, A2, A3, ZN;

Switch_NMOS_n12_X1_Y1 MMI1_M_u5 ( .B(VSS), .D(net9), .G(A2), .S(net1) ); 
Switch_NMOS_n12_X1_Y1 MMI1_M_u4 ( .B(VSS), .D(ZN), .G(A1), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MMI1_M_u6 ( .B(VSS), .D(net1), .G(A3), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u1 ( .B(VDD), .D(ZN), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u3 ( .B(VDD), .D(ZN), .G(A3), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u2 ( .B(VDD), .D(ZN), .G(A2), .S(VDD) ); 

endmodule

module XNR2D1 ( A1, A2, ZN ); 
input A1, A2, ZN;

Switch_PMOS_n12_X1_Y1 MM_u6_M_u2 ( .B(VDD), .D(net27), .G(net9), .S(net44) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u3 ( .B(VDD), .D(ZN), .G(net44), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u5_M_u3 ( .B(VDD), .D(net5), .G(net27), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u8_M_u3 ( .B(VDD), .D(net9), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0_M_u2 ( .B(VDD), .D(net5), .G(A1), .S(net44) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u3 ( .B(VDD), .D(net27), .G(A2), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MM_u6_M_u3 ( .B(VSS), .D(net27), .G(A1), .S(net44) ); 
Switch_NMOS_n12_X1_Y1 MMI0_M_u3 ( .B(VSS), .D(net5), .G(net9), .S(net44) ); 
Switch_NMOS_n12_X1_Y1 MM_u8_M_u2 ( .B(VSS), .D(net9), .G(A1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u4_M_u2 ( .B(VSS), .D(ZN), .G(net44), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u2 ( .B(VSS), .D(net27), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u5_M_u2 ( .B(VSS), .D(net5), .G(net27), .S(VSS) ); 

endmodule

module AOI21D0 ( A1, A2, B, ZN ); 
input A1, A2, B, ZN;

Switch_PMOS_n12_X1_Y1 MMI9 ( .B(VDD), .D(ZN), .G(A1), .S(net5) ); 
Switch_PMOS_n12_X1_Y1 MM_u2 ( .B(VDD), .D(net5), .G(B), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI8 ( .B(VDD), .D(ZN), .G(A2), .S(net5) ); 
Switch_NMOS_n12_X1_Y1 MMI2 ( .B(VSS), .D(ZN), .G(A1), .S(net13) ); 
Switch_NMOS_n12_X1_Y1 MMI11 ( .B(VSS), .D(ZN), .G(B), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI10 ( .B(VSS), .D(net13), .G(A2), .S(VSS) ); 

endmodule

module NR2XD0 ( A1, A2, ZN ); 
input A1, A2, ZN;

Switch_NMOS_n12_X1_Y1 MMI1_M_u3 ( .B(VSS), .D(ZN), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI1_M_u4 ( .B(VSS), .D(ZN), .G(A1), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u1 ( .B(VDD), .D(net13), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u2 ( .B(VDD), .D(ZN), .G(A1), .S(net13) ); 

endmodule

module NR2D1 ( A1, A2, ZN ); 
input A1, A2, ZN;

Switch_NMOS_n12_X1_Y1 MMI1_M_u3 ( .B(VSS), .D(ZN), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI1_M_u4 ( .B(VSS), .D(ZN), .G(A1), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u1 ( .B(VDD), .D(net13), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u2 ( .B(VDD), .D(ZN), .G(A1), .S(net13) ); 

endmodule

module NR3D0 ( A1, A2, A3, ZN ); 
input A1, A2, A3, ZN;

Switch_NMOS_n12_X1_Y1 MMI3 ( .B(VSS), .D(ZN), .G(A1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI2 ( .B(VSS), .D(ZN), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u4 ( .B(VSS), .D(ZN), .G(A3), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI1 ( .B(VDD), .D(ZN), .G(A1), .S(net13) ); 
Switch_PMOS_n12_X1_Y1 MM_u1 ( .B(VDD), .D(net17), .G(A3), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI0 ( .B(VDD), .D(net13), .G(A2), .S(net17) ); 

endmodule

module INR2D1 ( A1, B1, ZN ); 
input A1, B1, ZN;

Switch_NMOS_n12_X1_Y1 MMU1_M_u3 ( .B(VSS), .D(ZN), .G(net11), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU1_M_u4 ( .B(VSS), .D(ZN), .G(B1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU6_M_u2 ( .B(VSS), .D(net11), .G(A1), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU6_M_u3 ( .B(VDD), .D(net11), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU1_M_u2 ( .B(VDD), .D(ZN), .G(B1), .S(net20) ); 
Switch_PMOS_n12_X1_Y1 MMU1_M_u1 ( .B(VDD), .D(net20), .G(net11), .S(VDD) ); 

endmodule

module OAI22D0 ( A1, A2, B1, B2, ZN ); 
input A1, A2, B1, B2, ZN;

Switch_NMOS_n12_X1_Y1 MM_u4 ( .B(VSS), .D(net13), .G(B2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI8 ( .B(VSS), .D(ZN), .G(A2), .S(net13) ); 
Switch_NMOS_n12_X1_Y1 MMI9 ( .B(VSS), .D(ZN), .G(A1), .S(net13) ); 
Switch_NMOS_n12_X1_Y1 MMI7 ( .B(VSS), .D(net13), .G(B1), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI4 ( .B(VDD), .D(ZN), .G(B1), .S(net32) ); 
Switch_PMOS_n12_X1_Y1 MMI6 ( .B(VDD), .D(ZN), .G(A1), .S(net17) ); 
Switch_PMOS_n12_X1_Y1 MMU24 ( .B(VDD), .D(net32), .G(B2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI5 ( .B(VDD), .D(net17), .G(A2), .S(VDD) ); 

endmodule

module MDLL_LOGIC_VLOG_DW01_add_J16_0 ( A<0>, A<1>, A<2>, A<3>, A<4>, A<5>, A<6>, B<0>, B<1>, B<2>, B<3>, B<4>, B<5>, B<6>, IN0, IN1, SUM<0>, SUM<1>, SUM<2>, SUM<3>, SUM<4>, SUM<5>, SUM<6> ); 
input A<0>, A<1>, A<2>, A<3>, A<4>, A<5>, A<6>, B<0>, B<1>, B<2>, B<3>, B<4>, B<5>, B<6>, IN0, IN1, SUM<0>, SUM<1>, SUM<2>, SUM<3>, SUM<4>, SUM<5>, SUM<6>;

CKND2D0 XU41 ( .A1(A<0>), .A2(B<0>), .ZN(N19) ); 
CKND2D0 XU17 ( .A1(N30), .A2(N28), .ZN(N32) ); 
CKND2D0 XU18 ( .A1(B<2>), .A2(IN1), .ZN(N34) ); 
CKND2D0 XU39 ( .A1(N21), .A2(N20), .ZN(N37) ); 
CKND2D0 XU19 ( .A1(B<3>), .A2(A<3>), .ZN(N28) ); 
CKND2D0 XU35 ( .A1(B<0>), .A2(A<0>), .ZN(N38) ); 
ND2D1 XU14 ( .A1(N11), .A2(N12), .ZN(N10) ); 
ND2D1 XU11 ( .A1(N36), .A2(N20), .ZN(N26) ); 
ND2D1 XU30 ( .A1(B<1>), .A2(A<1>), .ZN(N20) ); 
OR2D1 XU32 ( .A1(B<3>), .A2(A<3>), .Z(N30) ); 
OR2D1 XU10 ( .A1(B<1>), .A2(A<1>), .Z(N21) ); 
IND2D1 XU3 ( .A1(B<2>), .B1(A<2>), .ZN(N29) ); 
IND2D1 XU31 ( .A1(B<4>), .B1(A<4>), .ZN(N15) ); 
CKND1 XU47 ( .I(N34), .ZN(N33) ); 
CKND1 XU16 ( .I(N30), .ZN(N16) ); 
CKND1 XU45 ( .I(N29), .ZN(N17) ); 
XNR2D1 XU36 ( .A1(N24), .A2(N7), .ZN(SUM<4>) ); 
XNR2D1 XU43 ( .A1(B<6>), .A2(A<6>), .ZN(N9) ); 
XNR2D1 XU20 ( .A1(N10), .A2(N5), .ZN(SUM<5>) ); 
XNR2D1 XU21 ( .A1(B<5>), .A2(A<5>), .ZN(N5) ); 
NR2D0 XU34 ( .A1(A<0>), .A2(B<0>), .ZN(N39) ); 
INR2D1 XU33 ( .A1(N38), .B1(N39), .ZN(SUM<0>) ); 
CKXOR2D1 XU27 ( .A1(B<4>), .A2(IN0), .Z(N7) ); 
CKXOR2D1 XU42 ( .A1(N8), .A2(N9), .Z(SUM<6>) ); 
CKXOR2D1 XU46 ( .A1(N31), .A2(N32), .Z(SUM<3>) ); 
CKXOR2D1 XU24 ( .A1(N26), .A2(N6), .Z(SUM<2>) ); 
CKXOR2D1 XU23 ( .A1(N37), .A2(N38), .Z(SUM<1>) ); 
AN2XD1 XU6 ( .A1(B<4>), .A2(IN0), .Z(N2) ); 
AN2XD1 XU5 ( .A1(B<5>), .A2(A<5>), .Z(N1) ); 
AN2XD1 XU8 ( .A1(B<0>), .A2(A<0>), .Z(N4) ); 
AN2XD1 XU25 ( .A1(N29), .A2(N34), .Z(N6) ); 
ND2D0 XU13 ( .A1(N21), .A2(N4), .ZN(N36) ); 
CKND2D1 XU38 ( .A1(IN1), .A2(B<2>), .ZN(N27) ); 
OAI21D1 XU44 ( .A1(N18), .A2(N19), .B(N20), .ZN(N13) ); 
OAI21D1 XU26 ( .A1(N16), .A2(N27), .B(N28), .ZN(N22) ); 
AOI21D0 XU15 ( .A1(N26), .A2(N29), .B(N33), .ZN(N31) ); 
AOI21D1 XU28 ( .A1(N25), .A2(N26), .B(N22), .ZN(N24) ); 
AOI21D1 XU9 ( .A1(N22), .A2(N15), .B(N2), .ZN(N11) ); 
AOI21D1 XU29 ( .A1(N3), .A2(N10), .B(N1), .ZN(N8) ); 
OR2XD1 XU7 ( .A1(A<5>), .A2(B<5>), .Z(N3) ); 
INVD1 XU37 ( .I(N21), .ZN(N18) ); 
NR2XD0 XU12 ( .A1(N16), .A2(N17), .ZN(N14) ); 
ND3D1 XU22 ( .A1(N14), .A2(N15), .A3(N13), .ZN(N12) ); 
NR2D1 XU40 ( .A1(N16), .A2(N17), .ZN(N25) ); 

endmodule

module OR2D1 ( A1, A2, Z ); 
input A1, A2, Z;

Switch_NMOS_n12_X1_Y1 MMU1_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u7_M_u4 ( .B(VSS), .D(net5), .G(A1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u7_M_u3 ( .B(VSS), .D(net5), .G(A2), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU1_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u7_M_u1 ( .B(VDD), .D(net17), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u7_M_u2 ( .B(VDD), .D(net5), .G(A1), .S(net17) ); 

endmodule

module AOI21D1 ( A1, A2, B, ZN ); 
input A1, A2, B, ZN;

Switch_PMOS_n12_X1_Y1 MM_u3 ( .B(VDD), .D(net5), .G(A1), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MM_u2 ( .B(VDD), .D(net5), .G(B), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u4 ( .B(VDD), .D(net5), .G(A2), .S(ZN) ); 
Switch_NMOS_n12_X1_Y1 MMI2 ( .B(VSS), .D(ZN), .G(A1), .S(net13) ); 
Switch_NMOS_n12_X1_Y1 MM_u7 ( .B(VSS), .D(ZN), .G(B), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI3 ( .B(VSS), .D(net13), .G(A2), .S(VSS) ); 

endmodule

module OR2XD1 ( A1, A2, Z ); 
input A1, A2, Z;

Switch_NMOS_n12_X1_Y1 MMU1_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u7_M_u4 ( .B(VSS), .D(net5), .G(A1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u7_M_u3 ( .B(VSS), .D(net5), .G(A2), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU1_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u7_M_u1 ( .B(VDD), .D(net17), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u7_M_u2 ( .B(VDD), .D(net5), .G(A1), .S(net17) ); 

endmodule

module IND3D1 ( A1, B1, B2, ZN ); 
input A1, B1, B2, ZN;

Switch_PMOS_n12_X1_Y1 MMI4 ( .B(VDD), .D(VDD), .G(net19), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MMI11 ( .B(VDD), .D(VDD), .G(B2), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MM_u16 ( .B(VDD), .D(VDD), .G(B1), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MMI5_M_u3 ( .B(VDD), .D(net19), .G(A1), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MMI5_M_u2 ( .B(VSS), .D(net19), .G(A1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI6 ( .B(VSS), .D(net25), .G(B1), .S(net17) ); 
Switch_NMOS_n12_X1_Y1 MMI12 ( .B(VSS), .D(ZN), .G(B2), .S(net25) ); 
Switch_NMOS_n12_X1_Y1 MMI7 ( .B(VSS), .D(net17), .G(net19), .S(VSS) ); 

endmodule

module MDLL_LOGIC_VLOG_DW01_inc_0 ( A<0>, A<1>, A<2>, A<3>, A<4>, A<5>, A<6>, SUM<1>, SUM<2>, SUM<3>, SUM<4>, SUM<5>, SUM<6> ); 
input A<0>, A<1>, A<2>, A<3>, A<4>, A<5>, A<6>, SUM<1>, SUM<2>, SUM<3>, SUM<4>, SUM<5>, SUM<6>;

HA1D0 XU10103 ( .A(A<3>), .B(CARRY<3>), .CO(CARRY<4>), .S(SUM<3>) ); 
HA1D0 XU10101 ( .A(A<1>), .B(A<0>), .CO(CARRY<2>), .S(SUM<1>) ); 
HA1D0 XU10102 ( .A(A<2>), .B(CARRY<2>), .CO(CARRY<3>), .S(SUM<2>) ); 
HA1D0 XU10104 ( .A(A<4>), .B(CARRY<4>), .CO(CARRY<5>), .S(SUM<4>) ); 
HA1D0 XU10105 ( .A(A<5>), .B(CARRY<5>), .CO(CARRY<6>), .S(SUM<5>) ); 
CKXOR2D0 XU2 ( .A1(CARRY<6>), .A2(A<6>), .Z(SUM<6>) ); 

endmodule

module INV_LVT ( SN, SP, i, zn ); 
input SN, SP, i, zn;

Switch_NMOS_n12_X1_Y1 xm0 ( .B(SN), .D(zn), .G(i), .S(SN) ); 
Switch_PMOS_n12_X1_Y1 xm1 ( .B(SP), .D(zn), .G(i), .S(SP) ); 

endmodule

module stage2_inv ( G1, G2, SN, SP ); 
input G1, G2, SN, SP;

INV_LVT MM0_MM2 ( .zn(G1), .i(D), .SN(SN), .SP(SP) ); 
INV_LVT MM1_MM3 ( .zn(D), .i(G2), .SN(SN), .SP(SP) ); 

endmodule

module tgate ( D, GA, GB, S ); 
input D, GA, GB, S;

Switch_NMOS_n12_X1_Y1 M0 ( .B(BN), .D(D), .G(GA), .S(S) ); 
Switch_PMOS_n12_X1_Y1 M1 ( .B(BP), .D(D), .G(GB), .S(S) ); 

endmodule

module HA1D0 ( A, B, CO, S ); 
input A, B, CO, S;

Switch_PMOS_n12_X1_Y1 MMU9_M_u1 ( .B(VDD), .D(net25), .G(A), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU9_M_u2 ( .B(VDD), .D(net25), .G(B), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MMU9_M_u4 ( .B(VSS), .D(net56), .G(B), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU9_M_u3 ( .B(VSS), .D(net25), .G(A), .S(net56) ); 
stage2_inv MMU2_M_u2_MMU1_M_u2_MMU2_M_u3_MMU1_M_u3 ( .G1(net13), .SN(VSS), .G2(A), .SP(VDD) ); 
INV_LVT MMU3_M_u2_MMU3_M_u3 ( .zn(net5), .i(B), .SN(VSS), .SP(VDD) ); 
INV_LVT MMU5_M_u2_MMU5_M_u3 ( .zn(CO), .i(net25), .SN(VSS), .SP(VDD) ); 
INV_LVT MMU4_M_u2_MMU4_M_u3 ( .zn(S), .i(net72), .SN(VSS), .SP(VDD) ); 
tgate MMU7_M_u3_MMU7_M_u2 ( .D(net13), .GA(B), .S(net72), .GB(net5) ); 
tgate MMU8_M_u3_MMU8_M_u2 ( .D(net9), .GA(net5), .S(net72), .GB(B) ); 

endmodule

module CKXOR2D0 ( A1, A2, Z ); 
input A1, A2, Z;

Switch_NMOS_n12_X1_Y1 MM_u6_M_u3 ( .B(VSS), .D(net37), .G(net17), .S(net44) ); 
Switch_NMOS_n12_X1_Y1 MMI2_M_u2 ( .B(VSS), .D(net17), .G(A1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u4_M_u2 ( .B(VSS), .D(Z), .G(net44), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI3_M_u3 ( .B(VSS), .D(net5), .G(A1), .S(net44) ); 
Switch_NMOS_n12_X1_Y1 MM_u5_M_u2 ( .B(VSS), .D(net5), .G(net37), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI1_M_u2 ( .B(VSS), .D(net37), .G(A2), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI2_M_u3 ( .B(VDD), .D(net17), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u6_M_u2 ( .B(VDD), .D(net37), .G(A1), .S(net44) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u3 ( .B(VDD), .D(net37), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u4_M_u3 ( .B(VDD), .D(Z), .G(net44), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u5_M_u3 ( .B(VDD), .D(net5), .G(net37), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI3_M_u2 ( .B(VDD), .D(net5), .G(net17), .S(net44) ); 

endmodule

module CKAN2D1 ( A1, A2, Z ); 
input A1, A2, Z;

Switch_PMOS_n12_X1_Y1 MM_u2_M_u2 ( .B(VDD), .D(net5), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u1 ( .B(VDD), .D(net5), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u3_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u4 ( .B(VSS), .D(net21), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u3_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u3 ( .B(VSS), .D(net5), .G(A1), .S(net21) ); 

endmodule

module AN2D1 ( A1, A2, Z ); 
input A1, A2, Z;

Switch_PMOS_n12_X1_Y1 MM_u3_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u1 ( .B(VDD), .D(net5), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u2 ( .B(VDD), .D(net5), .G(A2), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MM_u3_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u4 ( .B(VSS), .D(net17), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u3 ( .B(VSS), .D(net5), .G(A1), .S(net17) ); 

endmodule

module DFCNQD1 ( CDN, CP, D, Q ); 
input CDN, CP, D, Q;

Switch_NMOS_n12_X1_Y1 MMI4 ( .B(VSS), .D(net53), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI21_M_u3 ( .B(VSS), .D(net81), .G(net51), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MMI13_M_u2 ( .B(VSS), .D(net37), .G(net97), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI29 ( .B(VSS), .D(net51), .G(net5), .S(net44) ); 
Switch_NMOS_n12_X1_Y1 MMI15 ( .B(VSS), .D(net37), .G(net63), .S(net51) ); 
Switch_NMOS_n12_X1_Y1 MMI32_M_u2 ( .B(VSS), .D(net63), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI5 ( .B(VSS), .D(net97), .G(D), .S(net53) ); 
Switch_NMOS_n12_X1_Y1 MMI49 ( .B(VSS), .D(net20), .G(CDN), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI26 ( .B(VSS), .D(net44), .G(net81), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI48 ( .B(VSS), .D(net17), .G(net37), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMI27_M_u2 ( .B(VSS), .D(Q), .G(net81), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI21_M_u4 ( .B(VSS), .D(net9), .G(CDN), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI22_M_u2 ( .B(VSS), .D(net5), .G(CP), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI47 ( .B(VSS), .D(net97), .G(net63), .S(net17) ); 
Switch_PMOS_n12_X1_Y1 MMI22_M_u3 ( .B(VDD), .D(net5), .G(CP), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI32_M_u3 ( .B(VDD), .D(net63), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI43 ( .B(VDD), .D(net101), .G(net37), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI6 ( .B(VDD), .D(net97), .G(D), .S(net100) ); 
Switch_PMOS_n12_X1_Y1 MMI27_M_u3 ( .B(VDD), .D(Q), .G(net81), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI44 ( .B(VDD), .D(net101), .G(CDN), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI13_M_u3 ( .B(VDD), .D(net37), .G(net97), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI21_M_u1 ( .B(VDD), .D(net81), .G(net51), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI16 ( .B(VDD), .D(net37), .G(net5), .S(net51) ); 
Switch_PMOS_n12_X1_Y1 MMI24 ( .B(VDD), .D(net72), .G(net81), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI28 ( .B(VDD), .D(net51), .G(net63), .S(net72) ); 
Switch_PMOS_n12_X1_Y1 MMI45 ( .B(VDD), .D(net97), .G(net5), .S(net101) ); 
Switch_PMOS_n12_X1_Y1 MMI7 ( .B(VDD), .D(net100), .G(net63), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI21_M_u2 ( .B(VDD), .D(net81), .G(CDN), .S(VDD) ); 

endmodule

module OAI21D0 ( A1, A2, B, ZN ); 
input A1, A2, B, ZN;

Switch_PMOS_n12_X1_Y1 MMI16_MI13 ( .B(VDD), .D(net9), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u9 ( .B(VDD), .D(ZN), .G(B), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI16_MI12 ( .B(VDD), .D(ZN), .G(A1), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MM_u3 ( .B(VSS), .D(ZN), .G(A2), .S(net24) ); 
Switch_NMOS_n12_X1_Y1 MM_u4 ( .B(VSS), .D(net24), .G(B), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2 ( .B(VSS), .D(ZN), .G(A1), .S(net24) ); 

endmodule

module OA211D0 ( A1, A2, B, C, Z ); 
input A1, A2, B, C, Z;

Switch_NMOS_n12_X1_Y1 MMI8 ( .B(VSS), .D(net17), .G(B), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMI11_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI9 ( .B(VSS), .D(net20), .G(C), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2 ( .B(VSS), .D(net5), .G(A1), .S(net17) ); 
Switch_NMOS_n12_X1_Y1 MMI7 ( .B(VSS), .D(net5), .G(A2), .S(net17) ); 
Switch_PMOS_n12_X1_Y1 MMI4 ( .B(VDD), .D(net5), .G(C), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI6 ( .B(VDD), .D(net5), .G(A2), .S(net25) ); 
Switch_PMOS_n12_X1_Y1 MM_u12 ( .B(VDD), .D(net5), .G(B), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI5 ( .B(VDD), .D(net25), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI11_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 

endmodule

module AO211D1 ( A1, A2, B, C, Z ); 
input A1, A2, B, C, Z;

Switch_NMOS_n12_X1_Y1 MM_u12 ( .B(VSS), .D(net5), .G(C), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI8_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI12_M_u10 ( .B(VSS), .D(net5), .G(A1), .S(net1) ); 
Switch_NMOS_n12_X1_Y1 MM_u13 ( .B(VSS), .D(net5), .G(B), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI12_M_u11 ( .B(VSS), .D(net1), .G(A2), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI16_MI12 ( .B(VDD), .D(net33), .G(B), .S(net25) ); 
Switch_PMOS_n12_X1_Y1 MM_u3 ( .B(VDD), .D(net33), .G(A1), .S(net5) ); 
Switch_PMOS_n12_X1_Y1 MMI0 ( .B(VDD), .D(net33), .G(A2), .S(net5) ); 
Switch_PMOS_n12_X1_Y1 MMI16_MI13 ( .B(VDD), .D(net25), .G(C), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI8_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 

endmodule

module MUX2ND0 ( I0, I1, S, ZN ); 
input I0, I1, S, ZN;

Switch_PMOS_n12_X1_Y1 MMI15_M_u3 ( .B(VDD), .D(net37), .G(S), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI111 ( .B(VDD), .D(net13), .G(I0), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI24 ( .B(VDD), .D(net9), .G(I1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI5 ( .B(VDD), .D(ZN), .G(S), .S(net13) ); 
Switch_PMOS_n12_X1_Y1 MMI25 ( .B(VDD), .D(ZN), .G(net37), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MMI15_M_u2 ( .B(VSS), .D(net37), .G(S), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI20 ( .B(VSS), .D(net33), .G(I1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI12 ( .B(VSS), .D(ZN), .G(net37), .S(net32) ); 
Switch_NMOS_n12_X1_Y1 MMI21 ( .B(VSS), .D(ZN), .G(S), .S(net33) ); 
Switch_NMOS_n12_X1_Y1 MMI19 ( .B(VSS), .D(net32), .G(I0), .S(VSS) ); 

endmodule

module DFCNQD4 ( CDN, CP, D, Q ); 
input CDN, CP, D, Q;

Switch_PMOS_n12_X1_Y1 MMI22_M_u3 ( .B(VDD), .D(Q), .G(net123), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI38 ( .B(VDD), .D(net16), .G(net123), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI32_M_u3 ( .B(VDD), .D(net79), .G(net67), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI43 ( .B(VDD), .D(net61), .G(net125), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI6 ( .B(VDD), .D(net9), .G(D), .S(net1) ); 
Switch_PMOS_n12_X1_Y1 MMI31_M_u3 ( .B(VDD), .D(net67), .G(CP), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI27_M_u3 ( .B(VDD), .D(Q), .G(net123), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI36_M_u2 ( .B(VDD), .D(net123), .G(CDN), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI44 ( .B(VDD), .D(net61), .G(CDN), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI36_M_u1 ( .B(VDD), .D(net123), .G(net13), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI13_M_u3 ( .B(VDD), .D(net125), .G(net9), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI24_M_u3 ( .B(VDD), .D(Q), .G(net123), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI16 ( .B(VDD), .D(net125), .G(net67), .S(net13) ); 
Switch_PMOS_n12_X1_Y1 MMI30_M_u1 ( .B(VDD), .D(net123), .G(net13), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI30_M_u2 ( .B(VDD), .D(net123), .G(CDN), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI28 ( .B(VDD), .D(net13), .G(net79), .S(net16) ); 
Switch_PMOS_n12_X1_Y1 MMI45 ( .B(VDD), .D(net9), .G(net67), .S(net61) ); 
Switch_PMOS_n12_X1_Y1 MMI25_M_u3 ( .B(VDD), .D(Q), .G(net123), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI7 ( .B(VDD), .D(net1), .G(net79), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MMI24_M_u2 ( .B(VSS), .D(Q), .G(net123), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI30_M_u4 ( .B(VSS), .D(net145), .G(CDN), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI4 ( .B(VSS), .D(net112), .G(net67), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI13_M_u2 ( .B(VSS), .D(net125), .G(net9), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI30_M_u3 ( .B(VSS), .D(net123), .G(net13), .S(net145) ); 
Switch_NMOS_n12_X1_Y1 MMI29 ( .B(VSS), .D(net13), .G(net67), .S(net93) ); 
Switch_NMOS_n12_X1_Y1 MMI15 ( .B(VSS), .D(net125), .G(net79), .S(net13) ); 
Switch_NMOS_n12_X1_Y1 MMI25_M_u2 ( .B(VSS), .D(Q), .G(net123), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI36_M_u3 ( .B(VSS), .D(net123), .G(net13), .S(net97) ); 
Switch_NMOS_n12_X1_Y1 MMI32_M_u2 ( .B(VSS), .D(net79), .G(net67), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI5 ( .B(VSS), .D(net9), .G(D), .S(net112) ); 
Switch_NMOS_n12_X1_Y1 MMI31_M_u2 ( .B(VSS), .D(net67), .G(CP), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI49 ( .B(VSS), .D(net92), .G(CDN), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI36_M_u4 ( .B(VSS), .D(net97), .G(CDN), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI26 ( .B(VSS), .D(net93), .G(net123), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI48 ( .B(VSS), .D(net80), .G(net125), .S(net92) ); 
Switch_NMOS_n12_X1_Y1 MMI27_M_u2 ( .B(VSS), .D(Q), .G(net123), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI22_M_u2 ( .B(VSS), .D(Q), .G(net123), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI47 ( .B(VSS), .D(net9), .G(net79), .S(net80) ); 

endmodule

module AO22D1 ( A1, A2, B1, B2, Z ); 
input A1, A2, B1, B2, Z;

Switch_NMOS_n12_X1_Y1 MMI20_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI29 ( .B(VSS), .D(net13), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI22 ( .B(VSS), .D(net9), .G(B2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI28 ( .B(VSS), .D(net5), .G(A1), .S(net13) ); 
Switch_NMOS_n12_X1_Y1 MMI21 ( .B(VSS), .D(net5), .G(B1), .S(net9) ); 
Switch_PMOS_n12_X1_Y1 MMI17 ( .B(VDD), .D(net25), .G(B1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI19 ( .B(VDD), .D(net5), .G(A1), .S(net25) ); 
Switch_PMOS_n12_X1_Y1 MMI18 ( .B(VDD), .D(net5), .G(A2), .S(net25) ); 
Switch_PMOS_n12_X1_Y1 MMI15 ( .B(VDD), .D(net25), .G(B2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI20_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 

endmodule

module AOI22D1 ( A1, A2, B1, B2, ZN ); 
input A1, A2, B1, B2, ZN;

Switch_NMOS_n12_X1_Y1 MMI3 ( .B(VSS), .D(ZN), .G(B1), .S(net1) ); 
Switch_NMOS_n12_X1_Y1 MMI9 ( .B(VSS), .D(ZN), .G(A1), .S(net5) ); 
Switch_NMOS_n12_X1_Y1 MMI10 ( .B(VSS), .D(net5), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI8 ( .B(VSS), .D(net1), .G(B2), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MM_u3 ( .B(VDD), .D(net20), .G(A2), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MM_u5 ( .B(VDD), .D(VDD), .G(B2), .S(net20) ); 
Switch_PMOS_n12_X1_Y1 MM_u2 ( .B(VDD), .D(net20), .G(A1), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MM_u4 ( .B(VDD), .D(VDD), .G(B1), .S(net20) ); 

endmodule

module AOI222D0 ( A1, A2, B1, B2, C1, C2, ZN ); 
input A1, A2, B1, B2, C1, C2, ZN;

Switch_PMOS_n12_X1_Y1 MMI17 ( .B(VDD), .D(net17), .G(B1), .S(net20) ); 
Switch_PMOS_n12_X1_Y1 MMI16 ( .B(VDD), .D(net17), .G(B2), .S(net20) ); 
Switch_PMOS_n12_X1_Y1 MMI19 ( .B(VDD), .D(net20), .G(A1), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MMU27 ( .B(VDD), .D(VDD), .G(C2), .S(net17) ); 
Switch_PMOS_n12_X1_Y1 MMI18 ( .B(VDD), .D(net20), .G(A2), .S(ZN) ); 
Switch_PMOS_n12_X1_Y1 MMI15 ( .B(VDD), .D(VDD), .G(C1), .S(net17) ); 
Switch_NMOS_n12_X1_Y1 MMI20_M_u10 ( .B(VSS), .D(ZN), .G(B1), .S(net25) ); 
Switch_NMOS_n12_X1_Y1 MMI6_M_u11 ( .B(VSS), .D(net40), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI6_M_u10 ( .B(VSS), .D(ZN), .G(A1), .S(net40) ); 
Switch_NMOS_n12_X1_Y1 MMI21_M_u10 ( .B(VSS), .D(ZN), .G(C1), .S(net36) ); 
Switch_NMOS_n12_X1_Y1 MMI21_M_u11 ( .B(VSS), .D(net36), .G(C2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI20_M_u11 ( .B(VSS), .D(net25), .G(B2), .S(VSS) ); 

endmodule

module AO221D1 ( A1, A2, B1, B2, C, Z ); 
input A1, A2, B1, B2, C, Z;

Switch_NMOS_n12_X1_Y1 MMI1_M_u10 ( .B(VSS), .D(net5), .G(A1), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MMI17_M_u10 ( .B(VSS), .D(net5), .G(B1), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMI8_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI1_M_u11 ( .B(VSS), .D(net9), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU20 ( .B(VSS), .D(net5), .G(C), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI17_M_u11 ( .B(VSS), .D(net20), .G(B2), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI5 ( .B(VDD), .D(net44), .G(A1), .S(net5) ); 
Switch_PMOS_n12_X1_Y1 MMI2 ( .B(VDD), .D(net33), .G(B2), .S(net44) ); 
Switch_PMOS_n12_X1_Y1 MMU22 ( .B(VDD), .D(VDD), .G(C), .S(net33) ); 
Switch_PMOS_n12_X1_Y1 MMI3 ( .B(VDD), .D(net33), .G(B1), .S(net44) ); 
Switch_PMOS_n12_X1_Y1 MMI4 ( .B(VDD), .D(net44), .G(A2), .S(net5) ); 
Switch_PMOS_n12_X1_Y1 MMI8_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 

endmodule

module DCAP8 (  ); 
Dcap_NMOS_n12_X1_Y1 MMI4 ( .B(VSS), .S(VSS), .G(net9) ); 
Switch_NMOS_n12_X1_Y1 MM_u2 ( .B(VSS), .D(net11), .G(net9), .S(VSS) ); 
Dcap_PMOS_n12_X1_Y1 MMI3 ( .B(VDD), .S(VDD), .G(net11) ); 
Switch_PMOS_n12_X1_Y1 MM_u1 ( .B(VDD), .D(net9), .G(net11), .S(VDD) ); 

endmodule

module SEL_LOGIC_V2 ( MDLCLK, NDIV<0>, NDIV<1>, NDIV<2>, NDIV<3>, NDIV<4>, NDIV<5>, SEL, SRST ); 
input MDLCLK, NDIV<0>, NDIV<1>, NDIV<2>, NDIV<3>, NDIV<4>, NDIV<5>, SEL, SRST;

DFCNQD1 XCYLCNT0REG010 ( .CDN(SRST), .CP(MDLCLK), .D(N1), .Q(CYLCNT<1>) ); 
DFCNQD1 XCYLCNT0REG020 ( .CDN(SRST), .CP(MDLCLK), .D(N2), .Q(CYLCNT<2>) ); 
DFCNQD1 XCYLCNT0REG030 ( .CDN(SRST), .CP(MDLCLK), .D(N3), .Q(CYLCNT<3>) ); 
DFCNQD1 XCYLCNT0REG040 ( .CDN(SRST), .CP(MDLCLK), .D(N4), .Q(CYLCNT<4>) ); 
DFCNQD1 XCYLCNT0REG050 ( .CDN(SRST), .CP(MDLCLK), .D(N5), .Q(CYLCNT<5>) ); 
DFCNQD1 XCYLCNT0REG000 ( .CDN(SRST), .CP(MDLCLK), .D(N14), .Q(CYLCNT<0>) ); 
INVD1 XU22 ( .I(CYLCNT<0>), .ZN(N14) ); 
OA31D1 XU5 ( .A1(N15), .A2(N16), .A3(N17), .B(SEL), .Z(N10) ); 
XNR2D1 XU11 ( .A1(NDIV<4>), .A2(CYLCNT<4>), .ZN(N20) ); 
XNR2D1 XU12 ( .A1(NDIV<2>), .A2(CYLCNT<2>), .ZN(N19) ); 
XNR2D1 XU13 ( .A1(NDIV<5>), .A2(CYLCNT<5>), .ZN(N18) ); 
XNR2D1 XU16 ( .A1(NDIV<3>), .A2(CYLCNT<3>), .ZN(N21) ); 
XNR2D1 XU15 ( .A1(NDIV<1>), .A2(CYLCNT<1>), .ZN(N22) ); 
XNR2D1 XU17 ( .A1(NDIV<0>), .A2(N14), .ZN(N15) ); 
DFSNQD1 XSEL0REG ( .CP(MDLCLK), .D(N10), .Q(SEL), .SDN(SRST) ); 
ND2D1 XU20 ( .A1(N21), .A2(N22), .ZN(N16) ); 
HA1D0 XU6 ( .A(CYLCNT<1>), .B(CYLCNT<0>), .CO(ADD0190CARRY020), .S(N1) ); 
HA1D0 XU7 ( .A(CYLCNT<3>), .B(ADD0190CARRY030), .CO(ADD0190CARRY040), .S(N3) ); 
HA1D0 XU8 ( .A(CYLCNT<2>), .B(ADD0190CARRY020), .CO(ADD0190CARRY030), .S(N2) ); 
HA1D0 XU9 ( .A(CYLCNT<4>), .B(ADD0190CARRY040), .CO(ADD0190CARRY050), .S(N4) ); 
CKXOR2D1 XU18 ( .A1(ADD0190CARRY050), .A2(CYLCNT<5>), .Z(N5) ); 
ND3D1 XU21 ( .A1(N18), .A2(N19), .A3(N20), .ZN(N17) ); 

endmodule

module OA31D1 ( A1, A2, A3, B, Z ); 
input A1, A2, A3, B, Z;

Switch_NMOS_n12_X1_Y1 MMU1_M_u2 ( .B(VSS), .D(Z), .G(net25), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI6 ( .B(VSS), .D(net5), .G(A1), .S(net25) ); 
Switch_NMOS_n12_X1_Y1 MM_u5 ( .B(VSS), .D(VSS), .G(B), .S(net5) ); 
Switch_NMOS_n12_X1_Y1 MMI8 ( .B(VSS), .D(net5), .G(A3), .S(net25) ); 
Switch_NMOS_n12_X1_Y1 MMI7 ( .B(VSS), .D(net5), .G(A2), .S(net25) ); 
Switch_PMOS_n12_X1_Y1 MMI3 ( .B(VDD), .D(net37), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI4 ( .B(VDD), .D(net33), .G(A2), .S(net37) ); 
Switch_PMOS_n12_X1_Y1 MMU1_M_u3 ( .B(VDD), .D(Z), .G(net25), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u11 ( .B(VDD), .D(net25), .G(B), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI5 ( .B(VDD), .D(net25), .G(A3), .S(net33) ); 

endmodule

`celldefine
module global_power;
supply0 VSS;
supply1 VDD;
endmodule
`endcelldefine
