//Verilog block level netlist file for single_SAR
//Generated by UMN for ALIGN project 


module single_SAR ( Bbar<0>, Bbar<1>, Bbar<2>, Bbar<3>, Bbar<4>, Bbar<5>, Bbar<6>, Bbar<7>, CLK<0>, CLK<1>, CLK<2>, CLK<3>, CLK<4>, CLK<5>, CLK<6>, CLK<7>, CLKC, OUTCODE<0>, OUTCODE<1>, OUTCODE<2>, OUTCODE<3>, OUTCODE<4>, OUTCODE<5>, OUTCODE<6>, OUTCODE<7>, RDY, V2DAC_N<0>, V2DAC_N<1>, V2DAC_N<2>, V2DAC_N<3>, V2DAC_N<4>, V2DAC_N<5>, V2DAC_N<6>, V2DAC_N<7>, V2DAC_P<0>, V2DAC_P<1>, V2DAC_P<2>, V2DAC_P<3>, V2DAC_P<4>, V2DAC_P<5>, V2DAC_P<6>, V2DAC_P<7>, VCMP_N, VCMP_P, VIN_N, VIN_P, VREF, VSH_N, VSH_P, net22<0>, net22<1>, net22<2>, net22<3>, net22<4>, net22<5>, net22<6>, net22<7> ); 
input Bbar<0>, Bbar<1>, Bbar<2>, Bbar<3>, Bbar<4>, Bbar<5>, Bbar<6>, Bbar<7>, CLK<0>, CLK<1>, CLK<2>, CLK<3>, CLK<4>, CLK<5>, CLK<6>, CLK<7>, CLKC, OUTCODE<0>, OUTCODE<1>, OUTCODE<2>, OUTCODE<3>, OUTCODE<4>, OUTCODE<5>, OUTCODE<6>, OUTCODE<7>, RDY, V2DAC_N<0>, V2DAC_N<1>, V2DAC_N<2>, V2DAC_N<3>, V2DAC_N<4>, V2DAC_N<5>, V2DAC_N<6>, V2DAC_N<7>, V2DAC_P<0>, V2DAC_P<1>, V2DAC_P<2>, V2DAC_P<3>, V2DAC_P<4>, V2DAC_P<5>, V2DAC_P<6>, V2DAC_P<7>, VCMP_N, VCMP_P, VIN_N, VIN_P, VREF, VSH_N, VSH_P, net22<0>, net22<1>, net22<2>, net22<3>, net22<4>, net22<5>, net22<6>, net22<7>;

DFF_reset I34<0> ( .CLK(CLKS), .D(B<0>), .Q(OUTCODE<0>), .Qbar(net22<0>), .R(RESET_OUTCODE) ); 
DFF_reset I34<1> ( .CLK(CLKS), .D(B<1>), .Q(OUTCODE<1>), .Qbar(net22<1>), .R(RESET_OUTCODE) ); 
DFF_reset I34<2> ( .CLK(CLKS), .D(B<2>), .Q(OUTCODE<2>), .Qbar(net22<2>), .R(RESET_OUTCODE) ); 
DFF_reset I34<3> ( .CLK(CLKS), .D(B<3>), .Q(OUTCODE<3>), .Qbar(net22<3>), .R(RESET_OUTCODE) ); 
DFF_reset I34<4> ( .CLK(CLKS), .D(B<4>), .Q(OUTCODE<4>), .Qbar(net22<4>), .R(RESET_OUTCODE) ); 
DFF_reset I34<5> ( .CLK(CLKS), .D(B<5>), .Q(OUTCODE<5>), .Qbar(net22<5>), .R(RESET_OUTCODE) ); 
DFF_reset I34<6> ( .CLK(CLKS), .D(B<6>), .Q(OUTCODE<6>), .Qbar(net22<6>), .R(RESET_OUTCODE) ); 
DFF_reset I34<7> ( .CLK(CLKS), .D(B<7>), .Q(OUTCODE<7>), .Qbar(net22<7>), .R(RESET_OUTCODE) ); 
chip_core I0 ( .B<0>(B<0>), .B<1>(B<1>), .B<2>(B<2>), .B<3>(B<3>), .B<4>(B<4>), .B<5>(B<5>), .B<6>(B<6>), .B<7>(B<7>), .Bbar<0>(Bbar<0>), .Bbar<1>(Bbar<1>), .Bbar<2>(Bbar<2>), .Bbar<3>(Bbar<3>), .Bbar<4>(Bbar<4>), .Bbar<5>(Bbar<5>), .Bbar<6>(Bbar<6>), .Bbar<7>(Bbar<7>), .CLKC(CLKC), .CLKS(CLKS), .RDY(RDY), .V2DAC_N<0>(V2DAC_N<0>), .V2DAC_N<1>(V2DAC_N<1>), .V2DAC_N<2>(V2DAC_N<2>), .V2DAC_N<3>(V2DAC_N<3>), .V2DAC_N<4>(V2DAC_N<4>), .V2DAC_N<5>(V2DAC_N<5>), .V2DAC_N<6>(V2DAC_N<6>), .V2DAC_N<7>(V2DAC_N<7>), .V2DAC_P<0>(V2DAC_P<0>), .V2DAC_P<1>(V2DAC_P<1>), .V2DAC_P<2>(V2DAC_P<2>), .V2DAC_P<3>(V2DAC_P<3>), .V2DAC_P<4>(V2DAC_P<4>), .V2DAC_P<5>(V2DAC_P<5>), .V2DAC_P<6>(V2DAC_P<6>), .V2DAC_P<7>(V2DAC_P<7>), .VCMP_N(VCMP_N), .VCMP_P(VCMP_P), .VIN_N(VIN_N), .VIN_P(VIN_P), .VREF(VREF), .VSH_N(VSH_N), .VSH_P(VSH_P), .CLK<0>(CLK<0>), .CLK<1>(CLK<1>), .CLK<2>(CLK<2>), .CLK<3>(CLK<3>), .CLK<4>(CLK<4>), .CLK<5>(CLK<5>), .CLK<6>(CLK<6>), .CLK<7>(CLK<7>) ); 

endmodule

module DFF_reset ( CLK, D, Q, Qbar, R ); 
input CLK, D, Q, Qbar, R;

inverter I10 ( .VIN(net015), .VOUT(net026) ); 
inverter I7 ( .VIN(R), .VOUT(net019) ); 
inverter I13 ( .VIN(CLK), .VOUT(net013) ); 
NAND2 I12 ( .A(net015), .B(net014), .D(net011) ); 
NAND2 I11 ( .A(net014), .B(net026), .D(net010) ); 
NAND2 I9 ( .A(net019), .B(net023), .D(net015) ); 
NAND2 I8 ( .A(net022), .B(net010), .D(net023) ); 
NAND2 I5 ( .A(net011), .B(D), .D(net022) ); 
NAND2 I3 ( .A(Qbar), .B(net010), .D(Q) ); 
NAND2 I2 ( .A(net011), .B(Q), .D(Qbar) ); 
NAND2 I6 ( .A(net019), .B(net013), .D(net014) ); 

endmodule

module INV_LVT ( SN, SP, i, zn ); 
input SN, SP, i, zn;

Switch_NMOS_n12_X2_Y2 xm0 ( .B(SN), .D(zn), .G(i), .S(SN) ); 
Switch_PMOS_n12_X2_Y2 xm1 ( .B(SP), .D(zn), .G(i), .S(SP) ); 

endmodule

module inverter ( VIN, VOUT ); 
input VIN, VOUT;

INV_LVT M0_M1 ( .zn(VOUT), .i(VIN), .SN(VSS), .SP(VDD) ); 

endmodule

module NAND2 ( A, B, D ); 
input A, B, D;

Switch_NMOS_n12_X2_Y2 M1 ( .B(VSS), .D(net7), .G(B), .S(VSS) ); 
Switch_NMOS_n12_X2_Y2 M0 ( .B(VSS), .D(D), .G(A), .S(net7) ); 
Switch_PMOS_n12_X2_Y2 M3 ( .B(VDD), .D(D), .G(B), .S(VDD) ); 
Switch_PMOS_n12_X2_Y2 M2 ( .B(VDD), .D(D), .G(A), .S(VDD) ); 

endmodule

module chip_core ( B<0>, B<1>, B<2>, B<3>, B<4>, B<5>, B<6>, B<7>, Bbar<0>, Bbar<1>, Bbar<2>, Bbar<3>, Bbar<4>, Bbar<5>, Bbar<6>, Bbar<7>, CLK<0>, CLK<1>, CLK<2>, CLK<3>, CLK<4>, CLK<5>, CLK<6>, CLK<7>, CLKC, CLKS, RDY, V2DAC_N<0>, V2DAC_N<1>, V2DAC_N<2>, V2DAC_N<3>, V2DAC_N<4>, V2DAC_N<5>, V2DAC_N<6>, V2DAC_N<7>, V2DAC_P<0>, V2DAC_P<1>, V2DAC_P<2>, V2DAC_P<3>, V2DAC_P<4>, V2DAC_P<5>, V2DAC_P<6>, V2DAC_P<7>, VCMP_N, VCMP_P, VIN_N, VIN_P, VREF, VSH_N, VSH_P ); 
input B<0>, B<1>, B<2>, B<3>, B<4>, B<5>, B<6>, B<7>, Bbar<0>, Bbar<1>, Bbar<2>, Bbar<3>, Bbar<4>, Bbar<5>, Bbar<6>, Bbar<7>, CLK<0>, CLK<1>, CLK<2>, CLK<3>, CLK<4>, CLK<5>, CLK<6>, CLK<7>, CLKC, CLKS, RDY, V2DAC_N<0>, V2DAC_N<1>, V2DAC_N<2>, V2DAC_N<3>, V2DAC_N<4>, V2DAC_N<5>, V2DAC_N<6>, V2DAC_N<7>, V2DAC_P<0>, V2DAC_P<1>, V2DAC_P<2>, V2DAC_P<3>, V2DAC_P<4>, V2DAC_P<5>, V2DAC_P<6>, V2DAC_P<7>, VCMP_N, VCMP_P, VIN_N, VIN_P, VREF, VSH_N, VSH_P;

comparator_p I1 ( .CLKC(CLKC), .RDY(RDY), .VINN(VSH_N), .VINP(VSH_P), .VOUTN(VCMP_N), .VOUTP(VCMP_P) ); 
SAR_logic I2 ( .B<0>(B<0>), .B<1>(B<1>), .B<2>(B<2>), .B<3>(B<3>), .B<4>(B<4>), .B<5>(B<5>), .B<6>(B<6>), .B<7>(B<7>), .Bbar<0>(Bbar<0>), .Bbar<1>(Bbar<1>), .Bbar<2>(Bbar<2>), .Bbar<3>(Bbar<3>), .Bbar<4>(Bbar<4>), .Bbar<5>(Bbar<5>), .Bbar<6>(Bbar<6>), .Bbar<7>(Bbar<7>), .CLKC(CLKC), .CLKS(CLKS), .OUT_N(VCMP_N), .OUT_P(VCMP_P), .RDY(RDY), .V2DAC_N<0>(V2DAC_N<0>), .V2DAC_N<1>(V2DAC_N<1>), .V2DAC_N<2>(V2DAC_N<2>), .V2DAC_N<3>(V2DAC_N<3>), .V2DAC_N<4>(V2DAC_N<4>), .V2DAC_N<5>(V2DAC_N<5>), .V2DAC_N<6>(V2DAC_N<6>), .V2DAC_N<7>(V2DAC_N<7>), .V2DAC_P<0>(V2DAC_P<0>), .V2DAC_P<1>(V2DAC_P<1>), .V2DAC_P<2>(V2DAC_P<2>), .V2DAC_P<3>(V2DAC_P<3>), .V2DAC_P<4>(V2DAC_P<4>), .V2DAC_P<5>(V2DAC_P<5>), .V2DAC_P<6>(V2DAC_P<6>), .V2DAC_P<7>(V2DAC_P<7>), .VREF(VREF), .CLK<0>(CLK<0>), .CLK<1>(CLK<1>), .CLK<2>(CLK<2>), .CLK<3>(CLK<3>), .CLK<4>(CLK<4>), .CLK<5>(CLK<5>), .CLK<6>(CLK<6>), .CLK<7>(CLK<7>) ); 
inverter I6 ( .VIN(CLKS), .VOUT(CLKSbar) ); 
SH I0 ( .CLK(CLKS), .CLKbar(CLKSbar), .INN(VIN_N), .INP(VIN_P), .OUTN(VSH_N), .OUTP(VSH_P), .V2DAC_N<0>(V2DAC_N<0>), .V2DAC_N<1>(V2DAC_N<1>), .V2DAC_N<2>(V2DAC_N<2>), .V2DAC_N<3>(V2DAC_N<3>), .V2DAC_N<4>(V2DAC_N<4>), .V2DAC_N<5>(V2DAC_N<5>), .V2DAC_N<6>(V2DAC_N<6>), .V2DAC_N<7>(V2DAC_N<7>), .V2DAC_P<0>(V2DAC_P<0>), .V2DAC_P<1>(V2DAC_P<1>), .V2DAC_P<2>(V2DAC_P<2>), .V2DAC_P<3>(V2DAC_P<3>), .V2DAC_P<4>(V2DAC_P<4>), .V2DAC_P<5>(V2DAC_P<5>), .V2DAC_P<6>(V2DAC_P<6>), .V2DAC_P<7>(V2DAC_P<7>) ); 

endmodule

module comparator_p ( CLKC, RDY, VINN, VINP, VOUTN, VOUTP ); 
input CLKC, RDY, VINN, VINP, VOUTN, VOUTP;

Switch_NMOS_n12_X2_Y2 M5 ( .B(VSS), .D(net16), .G(CLKC), .S(VSS) ); 
Switch_NMOS_n12_X2_Y2 M4 ( .B(VSS), .D(net9), .G(CLKC), .S(VSS) ); 
Switch_PMOS_n12_X2_Y2 M0 ( .B(VDD), .D(net12), .G(CLKC), .S(VDD) ); 
NAND2 I1 ( .A(VOUTP), .B(VOUTN), .D(RDY) ); 
CCP_NMOS_S_n12_X2_Y2 M6_M3 ( .B(VSS), .DA(net9), .DB(net16), .S(VSS) ); 
INV_LVT M10_M9 ( .zn(VOUTN), .i(net16), .SN(VSS), .SP(VDD) ); 
INV_LVT M7_M8 ( .zn(VOUTP), .i(net9), .SN(VSS), .SP(VDD) ); 
DP_PMOS_n12_X2_Y2 M2_M1 ( .B(VDD), .DA(net16), .GA(VINN), .S(net12), .DB(net9), .GB(VINP) ); 

endmodule

module SAR_logic ( B<0>, B<1>, B<2>, B<3>, B<4>, B<5>, B<6>, B<7>, Bbar<0>, Bbar<1>, Bbar<2>, Bbar<3>, Bbar<4>, Bbar<5>, Bbar<6>, Bbar<7>, CLK<0>, CLK<1>, CLK<2>, CLK<3>, CLK<4>, CLK<5>, CLK<6>, CLK<7>, CLKC, CLKS, OUT_N, OUT_P, RDY, V2DAC_N<0>, V2DAC_N<1>, V2DAC_N<2>, V2DAC_N<3>, V2DAC_N<4>, V2DAC_N<5>, V2DAC_N<6>, V2DAC_N<7>, V2DAC_P<0>, V2DAC_P<1>, V2DAC_P<2>, V2DAC_P<3>, V2DAC_P<4>, V2DAC_P<5>, V2DAC_P<6>, V2DAC_P<7>, VREF ); 
input B<0>, B<1>, B<2>, B<3>, B<4>, B<5>, B<6>, B<7>, Bbar<0>, Bbar<1>, Bbar<2>, Bbar<3>, Bbar<4>, Bbar<5>, Bbar<6>, Bbar<7>, CLK<0>, CLK<1>, CLK<2>, CLK<3>, CLK<4>, CLK<5>, CLK<6>, CLK<7>, CLKC, CLKS, OUT_N, OUT_P, RDY, V2DAC_N<0>, V2DAC_N<1>, V2DAC_N<2>, V2DAC_N<3>, V2DAC_N<4>, V2DAC_N<5>, V2DAC_N<6>, V2DAC_N<7>, V2DAC_P<0>, V2DAC_P<1>, V2DAC_P<2>, V2DAC_P<3>, V2DAC_P<4>, V2DAC_P<5>, V2DAC_P<6>, V2DAC_P<7>, VREF;

DAC_ctrl_logic I10<0> ( .B(Bbar<0>), .CLK(CLK<0>), .OUT(OUT_N), .V2DAC(V2DAC_N<0>), .VREF(VREF) ); 
DAC_ctrl_logic I10<1> ( .B(Bbar<1>), .CLK(CLK<1>), .OUT(OUT_N), .V2DAC(V2DAC_N<1>), .VREF(VREF) ); 
DAC_ctrl_logic I10<2> ( .B(Bbar<2>), .CLK(CLK<2>), .OUT(OUT_N), .V2DAC(V2DAC_N<2>), .VREF(VREF) ); 
DAC_ctrl_logic I10<3> ( .B(Bbar<3>), .CLK(CLK<3>), .OUT(OUT_N), .V2DAC(V2DAC_N<3>), .VREF(VREF) ); 
DAC_ctrl_logic I10<4> ( .B(Bbar<4>), .CLK(CLK<4>), .OUT(OUT_N), .V2DAC(V2DAC_N<4>), .VREF(VREF) ); 
DAC_ctrl_logic I10<5> ( .B(Bbar<5>), .CLK(CLK<5>), .OUT(OUT_N), .V2DAC(V2DAC_N<5>), .VREF(VREF) ); 
DAC_ctrl_logic I10<6> ( .B(Bbar<6>), .CLK(CLK<6>), .OUT(OUT_N), .V2DAC(V2DAC_N<6>), .VREF(VREF) ); 
DAC_ctrl_logic I10<7> ( .B(Bbar<7>), .CLK(CLK<7>), .OUT(OUT_N), .V2DAC(V2DAC_N<7>), .VREF(VREF) ); 
DAC_ctrl_logic I2<0> ( .B(B<0>), .CLK(CLK<0>), .OUT(OUT_P), .V2DAC(V2DAC_P<0>), .VREF(VREF) ); 
DAC_ctrl_logic I2<1> ( .B(B<1>), .CLK(CLK<1>), .OUT(OUT_P), .V2DAC(V2DAC_P<1>), .VREF(VREF) ); 
DAC_ctrl_logic I2<2> ( .B(B<2>), .CLK(CLK<2>), .OUT(OUT_P), .V2DAC(V2DAC_P<2>), .VREF(VREF) ); 
DAC_ctrl_logic I2<3> ( .B(B<3>), .CLK(CLK<3>), .OUT(OUT_P), .V2DAC(V2DAC_P<3>), .VREF(VREF) ); 
DAC_ctrl_logic I2<4> ( .B(B<4>), .CLK(CLK<4>), .OUT(OUT_P), .V2DAC(V2DAC_P<4>), .VREF(VREF) ); 
DAC_ctrl_logic I2<5> ( .B(B<5>), .CLK(CLK<5>), .OUT(OUT_P), .V2DAC(V2DAC_P<5>), .VREF(VREF) ); 
DAC_ctrl_logic I2<6> ( .B(B<6>), .CLK(CLK<6>), .OUT(OUT_P), .V2DAC(V2DAC_P<6>), .VREF(VREF) ); 
DAC_ctrl_logic I2<7> ( .B(B<7>), .CLK(CLK<7>), .OUT(OUT_P), .V2DAC(V2DAC_P<7>), .VREF(VREF) ); 
async_logic I0 ( .CLK<0>(CLK<0>), .CLK<1>(CLK<1>), .CLK<2>(CLK<2>), .CLK<3>(CLK<3>), .CLK<4>(CLK<4>), .CLK<5>(CLK<5>), .CLK<6>(CLK<6>), .CLK<7>(CLK<7>), .CLKC(CLKC), .CLKS(CLKS), .RDY(RDY) ); 

endmodule

module DAC_ctrl_logic ( B, CLK, OUT, V2DAC, VREF ); 
input B, CLK, OUT, V2DAC, VREF;

NAND2 I2 ( .A(B), .B(net7), .D(net015) ); 
inverter I5 ( .VIN(net015), .VOUT(net9) ); 
buffer I4 ( .VIN(CLK), .VOUT(net7) ); 
Switch_NMOS_n12_X2_Y2 M0 ( .B(VSS), .D(V2DAC), .G(net9), .S(VSS) ); 
DFF I0 ( .CLK(CLK), .D(OUT), .Q(B), .Qbar(net11) ); 
Switch_PMOS_n12_X2_Y2 M1 ( .B(VREF), .D(V2DAC), .G(net9), .S(VREF) ); 

endmodule

module stage2_inv ( G1, G2, SN, SP ); 
input G1, G2, SN, SP;

INV_LVT MM0_MM2 ( .zn(G1), .i(D), .SN(SN), .SP(SP) ); 
INV_LVT MM1_MM3 ( .zn(D), .i(G2), .SN(SN), .SP(SP) ); 

endmodule

module buffer ( VIN, VOUT ); 
input VIN, VOUT;

stage2_inv M2_M0_M3_M1 ( .G1(VOUT), .SN(VSS), .G2(VIN), .SP(VDD) ); 

endmodule

module DFF ( CLK, D, Q, Qbar ); 
input CLK, D, Q, Qbar;

Latch I6 ( .CLK(CLK), .D(net013), .Q(Q), .Qbar(Qbar) ); 
Latch I5 ( .CLK(net012), .D(D), .Q(net013), .Qbar(net014) ); 
inverter I7 ( .VIN(CLK), .VOUT(net012) ); 

endmodule

module Latch ( CLK, D, Q, Qbar ); 
input CLK, D, Q, Qbar;

inverter I4 ( .VIN(D), .VOUT(net13) ); 
NAND2 I3 ( .A(Q), .B(net010), .D(Qbar) ); 
NAND2 I2 ( .A(net011), .B(Qbar), .D(Q) ); 
NAND2 I1 ( .A(CLK), .B(net13), .D(net010) ); 
NAND2 I0 ( .A(D), .B(CLK), .D(net011) ); 

endmodule

module async_logic ( CLK<0>, CLK<1>, CLK<2>, CLK<3>, CLK<4>, CLK<5>, CLK<6>, CLK<7>, CLKC, CLKS, RDY ); 
input CLK<0>, CLK<1>, CLK<2>, CLK<3>, CLK<4>, CLK<5>, CLK<6>, CLK<7>, CLKC, CLKS, RDY;

NOR3 I19 ( .A(CLKS), .B(RDY), .C(CLK<7>), .D(net01) ); 
inverter I20 ( .VIN(net01), .VOUT(net016) ); 
buffer I21 ( .VIN(net016), .VOUT(CLKC) ); 
DFF_reset I9 ( .CLK(RDY), .D(CLK<6>), .Q(CLK<7>), .Qbar(net5), .R(CLKS) ); 
DFF_reset I8 ( .CLK(RDY), .D(CLK<5>), .Q(CLK<6>), .Qbar(net12), .R(CLKS) ); 
DFF_reset I7 ( .CLK(RDY), .D(CLK<4>), .Q(CLK<5>), .Qbar(net19), .R(CLKS) ); 
DFF_reset I6 ( .CLK(RDY), .D(CLK<3>), .Q(CLK<4>), .Qbar(net26), .R(CLKS) ); 
DFF_reset I5 ( .CLK(RDY), .D(CLK<2>), .Q(CLK<3>), .Qbar(net33), .R(CLKS) ); 
DFF_reset I4 ( .CLK(RDY), .D(CLK<1>), .Q(CLK<2>), .Qbar(net40), .R(CLKS) ); 
DFF_reset I2 ( .CLK(RDY), .D(VDD), .Q(CLK<0>), .Qbar(net52), .R(CLKS) ); 
DFF_reset I3 ( .CLK(RDY), .D(CLK<0>), .Q(CLK<1>), .Qbar(net47), .R(CLKS) ); 

endmodule

module NOR3 ( A, B, C, D ); 
input A, B, C, D;

Switch_NMOS_n12_X2_Y2 M4 ( .B(VSS), .D(D), .G(C), .S(VSS) ); 
Switch_NMOS_n12_X2_Y2 M0 ( .B(VSS), .D(D), .G(B), .S(VSS) ); 
Switch_NMOS_n12_X2_Y2 M1 ( .B(VSS), .D(D), .G(A), .S(VSS) ); 
Switch_PMOS_n12_X2_Y2 M5 ( .B(VDD), .D(D), .G(C), .S(net23) ); 
Switch_PMOS_n12_X2_Y2 M3 ( .B(VDD), .D(net23), .G(B), .S(net24) ); 
Switch_PMOS_n12_X2_Y2 M2 ( .B(VDD), .D(net24), .G(A), .S(VDD) ); 

endmodule

module SH ( CLK, CLKbar, INN, INP, OUTN, OUTP, V2DAC_N<0>, V2DAC_N<1>, V2DAC_N<2>, V2DAC_N<3>, V2DAC_N<4>, V2DAC_N<5>, V2DAC_N<6>, V2DAC_N<7>, V2DAC_P<0>, V2DAC_P<1>, V2DAC_P<2>, V2DAC_P<3>, V2DAC_P<4>, V2DAC_P<5>, V2DAC_P<6>, V2DAC_P<7> ); 
input CLK, CLKbar, INN, INP, OUTN, OUTP, V2DAC_N<0>, V2DAC_N<1>, V2DAC_N<2>, V2DAC_N<3>, V2DAC_N<4>, V2DAC_N<5>, V2DAC_N<6>, V2DAC_N<7>, V2DAC_P<0>, V2DAC_P<1>, V2DAC_P<2>, V2DAC_P<3>, V2DAC_P<4>, V2DAC_P<5>, V2DAC_P<6>, V2DAC_P<7>;

CDAC I2 ( .S<0>(V2DAC_N<0>), .S<1>(V2DAC_N<1>), .S<2>(V2DAC_N<2>), .S<3>(V2DAC_N<3>), .S<4>(V2DAC_N<4>), .S<5>(V2DAC_N<5>), .S<6>(V2DAC_N<6>), .S<7>(V2DAC_N<7>), .TOP(OUTN), .ground(VSS) ); 
CDAC I1 ( .S<0>(V2DAC_P<0>), .S<1>(V2DAC_P<1>), .S<2>(V2DAC_P<2>), .S<3>(V2DAC_P<3>), .S<4>(V2DAC_P<4>), .S<5>(V2DAC_P<5>), .S<6>(V2DAC_P<6>), .S<7>(V2DAC_P<7>), .TOP(OUTP), .ground(VSS) ); 
bootstrap_diff I0 ( .CLK(CLK), .CLKbar(CLKbar), .INN(INN), .INP(INP), .VOUTN(OUTN), .VOUTP(OUTP) ); 

endmodule

module CDAC ( S<0>, S<1>, S<2>, S<3>, S<4>, S<5>, S<6>, S<7>, TOP, ground ); 
input S<0>, S<1>, S<2>, S<3>, S<4>, S<5>, S<6>, S<7>, TOP, ground;

Cap_7f C6 ( .PLUS(S<6>), .MINUS(TOP) ); 
Cap_15f C5 ( .PLUS(S<5>), .MINUS(TOP) ); 
Cap_31f C4 ( .PLUS(S<4>), .MINUS(TOP) ); 
Cap_62f C3 ( .PLUS(S<3>), .MINUS(TOP) ); 
Cap_125f C2 ( .PLUS(S<2>), .MINUS(TOP) ); 
Cap_250f C1 ( .PLUS(S<1>), .MINUS(TOP) ); 
Cap_500f C0 ( .PLUS(S<0>), .MINUS(TOP) ); 
Cap_cc C10_C7 ( .MINUS0(TOP), .PLUS0(ground), .MINUS1(TOP), .PLUS1(S<7>) ); 

endmodule

module bootstrap_diff ( CLK, CLKbar, INN, INP, VOUTN, VOUTP ); 
input CLK, CLKbar, INN, INP, VOUTN, VOUTP;

clk_doubler I18 ( .VIN(CLK), .VOUT(net6) ); 
clk_doubler I19 ( .VIN(CLK), .VOUT(net5) ); 
bootstrap I14 ( .OUT(VOUTP), .clk(CLK), .clkb(CLKbar), .clkb_high(net6), .IN(INP) ); 
bootstrap I10 ( .OUT(VOUTN), .clk(CLK), .clkb(CLKbar), .clkb_high(net5), .IN(INN) ); 

endmodule

module clk_doubler ( VIN, VOUT ); 
input VIN, VOUT;

Cap_2500f C1 ( .PLUS(VOUT), .MINUS(net5) ); 
Cap_2500f C0 ( .PLUS(VIN), .MINUS(VOUTb) ); 
Switch_NMOS_n12_X2_Y2 M0 ( .B(VSS), .D(VDD), .G(VOUTb), .S(VOUT) ); 
Switch_NMOS_n12_X2_Y2 M18 ( .B(VSS), .D(VDD), .G(VOUT), .S(VOUTb) ); 
inverter I0 ( .VIN(VIN), .VOUT(net5) ); 

endmodule

module bootstrap ( IN, OUT, clk, clkb, clkb_high ); 
input IN, OUT, clk, clkb, clkb_high;

Switch_NMOS_n12_X2_Y2 M10 ( .B(VSS), .D(net01), .G(clk), .S(IN) ); 
Switch_NMOS_n12_X2_Y2 M11 ( .B(VSS), .D(net012), .G(clk), .S(IN) ); 
Switch_NMOS_n12_X2_Y2 M6 ( .B(VSS), .D(net011), .G(clkb), .S(VSS) ); 
Switch_NMOS_n12_X2_Y2 M4 ( .B(VSS), .D(OUT), .G(net011), .S(IN) ); 
Switch_NMOS_n12_X2_Y2 M1q ( .B(VSS), .D(net01), .G(clkb), .S(VSS) ); 
Switch_NMOS_n12_X2_Y2 M0 ( .B(VSS), .D(VDD), .G(clkb_high), .S(net8) ); 
Cap_20000f C0 ( .PLUS(net01), .MINUS(net8) ); 
Switch_PMOS_n12_X2_Y2 M12 ( .B(VDD), .D(IN), .G(clkb), .S(net01) ); 
Switch_PMOS_n12_X2_Y2 M7 ( .B(VDD), .D(IN), .G(clkb), .S(net012) ); 
Switch_PMOS_n12_X2_Y2 M13 ( .B(VDD), .D(net012), .G(clk), .S(VDD) ); 
Switch_PMOS_n12_X2_Y2 M2 ( .B(net8), .D(net011), .G(net012), .S(net8) ); 

endmodule

`celldefine
module global_power;
supply0 VSS;
supply1 VDD;
endmodule
`endcelldefine
