//Verilog block level netlist file for BUFFER_VCM_FINAL4
//Generated by UMN for ALIGN project 


module CMB_PMOS_2 ( B, DA, DB, DC, S ); 
input B, DA, DB, DC, S;

Switch_PMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 
SCM_PMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .S(S), .DB(DB) ); 

endmodule

module BUFFER_VCM_FINAL4 ( ibias, vcm_in, vout ); 
input ibias, vcm_in, vout;

Dummy1_NMOS_n12_X1_Y1 xm17 ( .B(gnd), .S(net023) ); 
Dummy1_NMOS_n12_X1_Y1 xm18 ( .B(gnd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 xm19 ( .B(gnd), .S(net049) ); 
Switch_NMOS_n12_X1_Y1 xm16 ( .B(gnd), .D(vout), .G(net049), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 xm21 ( .B(gnd), .S(gnd) ); 
Dummy1_PMOS_n12_X1_Y1 xm39 ( .B(vdd), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 xm40 ( .B(vdd), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 xm41 ( .B(vdd), .S(net048) ); 
Dcap_PMOS_n12_X1_Y1 xm28 ( .B(vout), .S(vout), .G(net049) ); 
CMB_PMOS_2 xm38_xm34_xm35 ( .B(vdd), .DA(ibias), .S(vdd), .DB(vout), .DC(net048) ); 
SCM_NMOS_n12_X1_Y1 xm14_xm15 ( .B(gnd), .DA(net023), .S(gnd), .DB(net049) ); 
DP_PMOS_n12_X1_Y1 xm36_xm37 ( .B(vdd), .DA(net049), .GA(vcm_in), .S(net048), .DB(net023), .GB(vout) ); 

endmodule

`celldefine
module global_power;
supply0 gnd;
supply1 vdd;
endmodule
`endcelldefine
