//Verilog block level netlist file for five_transistor_ota
//Generated by UMN for ALIGN project 


module five_transistor_ota ( id, vbias, vinn, vinp, voutn, voutp ); 
input id, vbias, vinn, vinp, voutn, voutp;

SCM_NMOS_nfin5_nf4_n12_X2_Y1_RVT m5_m4 ( .DA(id), .DB(net10), .S(vss) );
DP_NMOS_B_nfin5_nf10_n12_X5_Y1_RVT m3_m0 ( .B(vss), .DA(voutp), .DB(voutn), .GA(vinn), .GB(vinp), .S(net10) ); 
CMC_PMOS_nfin5_nf2_n12_X1_Y1_RVT m2_m1 ( .DA(voutp), .DB(voutn), .G(vbias), .S(vdd) ); 


endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd;
endmodule
`endcelldefine
