//Verilog block level netlist file for telescopic_ota
//Generated by UMN for ALIGN project 


module telescopic_ota ( d1, vbiasn, vbiasp1, vbiasp2, vinn, vinp, voutn, voutp ); 
input d1, vbiasn, vbiasp1, vbiasp2, vinn, vinp, voutn, voutp;

SCM_NMOS_n12_X3_Y1 m5_m4 ( .B(vss), .DA(d1), .S(vss), .DB(net10) ); 
CMC_PMOS_S_n12_X1_Y1 m2_m1 ( .B(vdd), .DA(net012), .G(vbiasp1), .S(vdd), .DB(net06) ); 
DP_NMOS_n12_X3_Y3 m3_m0 ( .B(vss), .DA(net014), .GA(vinn), .S(net10), .DB(net8), .GB(vinp) ); 
CMC_PMOS_n12_X2_Y1 m7_m6 ( .B(net06), .DA(voutp), .G(vbiasp2), .SA(net012), .DB(voutn), .SB(net06) ); 
CMC_NMOS_n12_X3_Y1 m9_m8 ( .B(vss), .DA(voutn), .G(vbiasn), .SA(net8), .DB(voutp), .SB(net014) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd;
endmodule
`endcelldefine
