//Verilog block level netlist file for ldo_error_amp
//Generated by UMN for ALIGN project 


module ldo_error_amp ( vbias_an, vbias_bf, vfb, vg, vref ); 
input vbias_an, vbias_bf, vfb, vg, vref;

Switch_NMOS_nfin12_n12_X1_Y1 mn56 ( .D(vbias6), .G(vbias_bf), .S(vss_x) ); 
Dcap_NMOS_nfin12_n12_X1_Y1 mn40 ( .G(vbias_bf), .S(vss_x) ); 
Switch_NMOS_nfin12_n12_X1_Y1 mn41 ( .D(vbias4), .G(vbias_an), .S(vss_x) ); 
Switch_NMOS_B_nfin12_n12_X1_Y1 mn21 ( .B(vss_x), .D(vbias2), .G(vbias1), .S(vbias3) ); 
Switch_NMOS_B_nfin24_n12_X2_Y1 mn39 ( .B(vss_x), .D(v3), .G(vbias3), .S(v5) ); 
Switch_NMOS_nfin24_n12_X2_Y1 mn55 ( .D(v3_d), .G(vbias_bf), .S(vss_x) ); 
Dcap_NMOS_nfin12_n12_X1_Y1 mn3 ( .G(vbias_an), .S(vss_x) ); 
Switch_NMOS_nfin24_n12_X2_Y1 mn2 ( .D(vcom1), .G(vbias_an), .S(vss_x) ); 
DCL_PMOS_nfin12_n12_X1_Y1 mmp5 ( .D(vg), .S(vcc_nom) ); 
Switch_PMOS_B_nfin36_n12_X3_Y1 mmp30 ( .B(vcc_nom), .D(v3), .G(vbias2), .S(v1) ); 
Switch_PMOS_B_nfin24_n12_X2_Y1 mmp1 ( .B(vcc_nom), .D(v3_d), .G(v3), .S(vg) ); 
DCL_PMOS_nfin12_n12_X1_Y1 mp41 ( .D(vbias6), .S(vcc_nom) ); 
Switch_PMOS_nfin24_n12_X2_Y1 mp4 ( .D(vg), .G(vbias6), .S(vcc_nom) ); 
DCL_PMOS_nfin12_n12_X1_Y1 mp34 ( .D(vbias1), .S(vcc_nom) ); 
Switch_NMOS_nfin12_n12_X1_Y1 mmn322 ( .D(vg), .G(v3_d), .S(vss_x) ); 
LS_S_NMOS_B_nfin48_n12_X4_Y1 mmn42_mn38 ( .DA(vbias3), .DB(v4), .SA(vbias4), .SB(v6) ); 
LS_S_PMOS_B_nfin96_n12_X8_Y1 mmp33_mmp29 ( .DA(vbias2), .DB(v4), .SA(vbias1), .SB(v2) ); 
CMC_NMOS_nfin24_n12_X2_Y1 mn37_mn20 ( .DA(v6), .DB(v5), .G(v4), .S(vss_x) ); 
CMC_PMOS_nfin36_n12_X3_Y1 mp28_mp22 ( .DA(v2), .DB(v1), .G(vbias1), .S(vcc_nom) ); 
DP_NMOS_B_nfin60_n12_X5_Y1 mn23_mn22 ( .B(vss_x), .DA(v2), .DB(v1), .GA(vfb), .GB(vref), .S(vcom1) ); 

endmodule

`celldefine
module global_power;
supply0 vss_x;
supply1 vcc_nom;
endmodule
`endcelldefine
