//Verilog block level netlist file for powertrain_thermo
//Generated by UMN for ALIGN project 


module powertrain_thermo ( on_d[0], on_d[10], on_d[11], on_d[12], on_d[13], on_d[14], on_d[15], on_d[16], on_d[17], on_d[18], on_d[19], on_d[1], on_d[20], on_d[21], on_d[22], on_d[23], on_d[24], on_d[25], on_d[26], on_d[27], on_d[28], on_d[29], on_d[2], on_d[30], on_d[31], on_d[32], on_d[33], on_d[34], on_d[35], on_d[36], on_d[37], on_d[38], on_d[39], on_d[3], on_d[40], on_d[41], on_d[42], on_d[43], on_d[44], on_d[45], on_d[46], on_d[47], on_d[48], on_d[49], on_d[4], on_d[50], on_d[51], on_d[52], on_d[53], on_d[54], on_d[55], on_d[56], on_d[57], on_d[58], on_d[59], on_d[5], on_d[60], on_d[61], on_d[62], on_d[63], on_d[6], on_d[7], on_d[8], on_d[9], vout ); 
input on_d[0], on_d[10], on_d[11], on_d[12], on_d[13], on_d[14], on_d[15], on_d[16], on_d[17], on_d[18], on_d[19], on_d[1], on_d[20], on_d[21], on_d[22], on_d[23], on_d[24], on_d[25], on_d[26], on_d[27], on_d[28], on_d[29], on_d[2], on_d[30], on_d[31], on_d[32], on_d[33], on_d[34], on_d[35], on_d[36], on_d[37], on_d[38], on_d[39], on_d[3], on_d[40], on_d[41], on_d[42], on_d[43], on_d[44], on_d[45], on_d[46], on_d[47], on_d[48], on_d[49], on_d[4], on_d[50], on_d[51], on_d[52], on_d[53], on_d[54], on_d[55], on_d[56], on_d[57], on_d[58], on_d[59], on_d[5], on_d[60], on_d[61], on_d[62], on_d[63], on_d[6], on_d[7], on_d[8], on_d[9], vout;

powertrain_cell xu_pmos_title[63] ( .ond(on_d[63]), .vout(vout) ); 
powertrain_cell xu_pmos_title[62] ( .ond(on_d[62]), .vout(vout) ); 
powertrain_cell xu_pmos_title[61] ( .ond(on_d[61]), .vout(vout) ); 
powertrain_cell xu_pmos_title[60] ( .ond(on_d[60]), .vout(vout) ); 
powertrain_cell xu_pmos_title[59] ( .ond(on_d[59]), .vout(vout) ); 
powertrain_cell xu_pmos_title[58] ( .ond(on_d[58]), .vout(vout) ); 
powertrain_cell xu_pmos_title[57] ( .ond(on_d[57]), .vout(vout) ); 
powertrain_cell xu_pmos_title[56] ( .ond(on_d[56]), .vout(vout) ); 
powertrain_cell xu_pmos_title[55] ( .ond(on_d[55]), .vout(vout) ); 
powertrain_cell xu_pmos_title[54] ( .ond(on_d[54]), .vout(vout) ); 
powertrain_cell xu_pmos_title[53] ( .ond(on_d[53]), .vout(vout) ); 
powertrain_cell xu_pmos_title[52] ( .ond(on_d[52]), .vout(vout) ); 
powertrain_cell xu_pmos_title[51] ( .ond(on_d[51]), .vout(vout) ); 
powertrain_cell xu_pmos_title[50] ( .ond(on_d[50]), .vout(vout) ); 
powertrain_cell xu_pmos_title[49] ( .ond(on_d[49]), .vout(vout) ); 
powertrain_cell xu_pmos_title[48] ( .ond(on_d[48]), .vout(vout) ); 
powertrain_cell xu_pmos_title[47] ( .ond(on_d[47]), .vout(vout) ); 
powertrain_cell xu_pmos_title[46] ( .ond(on_d[46]), .vout(vout) ); 
powertrain_cell xu_pmos_title[45] ( .ond(on_d[45]), .vout(vout) ); 
powertrain_cell xu_pmos_title[44] ( .ond(on_d[44]), .vout(vout) ); 
powertrain_cell xu_pmos_title[43] ( .ond(on_d[43]), .vout(vout) ); 
powertrain_cell xu_pmos_title[42] ( .ond(on_d[42]), .vout(vout) ); 
powertrain_cell xu_pmos_title[41] ( .ond(on_d[41]), .vout(vout) ); 
powertrain_cell xu_pmos_title[40] ( .ond(on_d[40]), .vout(vout) ); 
powertrain_cell xu_pmos_title[39] ( .ond(on_d[39]), .vout(vout) ); 
powertrain_cell xu_pmos_title[38] ( .ond(on_d[38]), .vout(vout) ); 
powertrain_cell xu_pmos_title[37] ( .ond(on_d[37]), .vout(vout) ); 
powertrain_cell xu_pmos_title[36] ( .ond(on_d[36]), .vout(vout) ); 
powertrain_cell xu_pmos_title[35] ( .ond(on_d[35]), .vout(vout) ); 
powertrain_cell xu_pmos_title[34] ( .ond(on_d[34]), .vout(vout) ); 
powertrain_cell xu_pmos_title[33] ( .ond(on_d[33]), .vout(vout) ); 
powertrain_cell xu_pmos_title[32] ( .ond(on_d[32]), .vout(vout) ); 
powertrain_cell xu_pmos_title[31] ( .ond(on_d[31]), .vout(vout) ); 
powertrain_cell xu_pmos_title[30] ( .ond(on_d[30]), .vout(vout) ); 
powertrain_cell xu_pmos_title[29] ( .ond(on_d[29]), .vout(vout) ); 
powertrain_cell xu_pmos_title[28] ( .ond(on_d[28]), .vout(vout) ); 
powertrain_cell xu_pmos_title[27] ( .ond(on_d[27]), .vout(vout) ); 
powertrain_cell xu_pmos_title[26] ( .ond(on_d[26]), .vout(vout) ); 
powertrain_cell xu_pmos_title[25] ( .ond(on_d[25]), .vout(vout) ); 
powertrain_cell xu_pmos_title[24] ( .ond(on_d[24]), .vout(vout) ); 
powertrain_cell xu_pmos_title[23] ( .ond(on_d[23]), .vout(vout) ); 
powertrain_cell xu_pmos_title[22] ( .ond(on_d[22]), .vout(vout) ); 
powertrain_cell xu_pmos_title[21] ( .ond(on_d[21]), .vout(vout) ); 
powertrain_cell xu_pmos_title[20] ( .ond(on_d[20]), .vout(vout) ); 
powertrain_cell xu_pmos_title[19] ( .ond(on_d[19]), .vout(vout) ); 
powertrain_cell xu_pmos_title[18] ( .ond(on_d[18]), .vout(vout) ); 
powertrain_cell xu_pmos_title[17] ( .ond(on_d[17]), .vout(vout) ); 
powertrain_cell xu_pmos_title[16] ( .ond(on_d[16]), .vout(vout) ); 
powertrain_cell xu_pmos_title[15] ( .ond(on_d[15]), .vout(vout) ); 
powertrain_cell xu_pmos_title[14] ( .ond(on_d[14]), .vout(vout) ); 
powertrain_cell xu_pmos_title[13] ( .ond(on_d[13]), .vout(vout) ); 
powertrain_cell xu_pmos_title[12] ( .ond(on_d[12]), .vout(vout) ); 
powertrain_cell xu_pmos_title[11] ( .ond(on_d[11]), .vout(vout) ); 
powertrain_cell xu_pmos_title[10] ( .ond(on_d[10]), .vout(vout) ); 
powertrain_cell xu_pmos_title[9] ( .ond(on_d[9]), .vout(vout) ); 
powertrain_cell xu_pmos_title[8] ( .ond(on_d[8]), .vout(vout) ); 
powertrain_cell xu_pmos_title[7] ( .ond(on_d[7]), .vout(vout) ); 
powertrain_cell xu_pmos_title[6] ( .ond(on_d[6]), .vout(vout) ); 
powertrain_cell xu_pmos_title[5] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_title[4] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_title[3] ( .ond(on_d[3]), .vout(vout) ); 
powertrain_cell xu_pmos_title[2] ( .ond(on_d[2]), .vout(vout) ); 
powertrain_cell xu_pmos_title[1] ( .ond(on_d[1]), .vout(vout) ); 
powertrain_cell xu_pmos_title[0] ( .ond(on_d[0]), .vout(vout) ); 

endmodule

module powertrain_cell ( ond, vout ); 
input ond, vout;

Switch_PMOS_n12_X3_Y1 mmp0 ( .B(vcc), .D(vout), .G(ond), .S(vcc) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vcc;
endmodule
`endcelldefine
