//Verilog block level netlist file for high_speed_comparator
//Generated by UMN for ALIGN project 


module INV_LVT ( SN, SP, i, zn ); 
input SN, SP, i, zn;

Switch_NMOS_n12_X1_Y1 xm0 ( .B(SN), .D(zn), .G(i), .S(SN) ); 
Switch_PMOS_n12_X1_Y1 xm1 ( .B(SP), .D(zn), .G(i), .S(SP) ); 

endmodule

module high_speed_comparator ( clk, v_in, vip, von, vop ); 
input clk, v_in, vip, von, vop;

Switch_PMOS_n12_X1_Y1 mmp5 ( .B(vdd_nom_123), .D(vy), .G(clk), .S(vdd_nom_123) ); 
Switch_PMOS_n12_X1_Y1 mmp4 ( .B(vdd_nom_123), .D(vyy), .G(clk), .S(vdd_nom_123) ); 
Switch_PMOS_n12_X1_Y1 mmp3 ( .B(vdd_nom_123), .D(vx), .G(clk), .S(vdd_nom_123) ); 
Switch_PMOS_n12_X1_Y1 mmp2 ( .B(vdd_nom_123), .D(vxx), .G(clk), .S(vdd_nom_123) ); 
Switch_NMOS_n12_X4_Y2 mmn2 ( .B(vss), .D(vcom), .G(clk), .S(vss) ); 
CCP_PMOS_S_n12_X2_Y2 mmp1_mmp0 ( .B(vdd_nom_123), .DA(vxx), .DB(vyy), .S(vdd_nom_123) ); 
CCP_NMOS_n12_X4_Y2 mmn4_mmn3 ( .B(vss), .DA(vxx), .DB(vyy), .SA(vx), .SB(vy) ); 
INV_LVT mmn5_mmp6 ( .zn(von), .i(vxx), .SN(vss), .SP(vdd_nom_123) ); 
INV_LVT mmn6_mmp7 ( .zn(vop), .i(vyy), .SN(vss), .SP(vdd_nom_123) ); 
DP_NMOS_n12_X4_Y4 mmn1_mmn0 ( .B(vss), .DA(vy), .GA(vip), .S(vcom), .DB(vx), .GB(v_in) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd_nom_123;
endmodule
`endcelldefine
