//Verilog block level netlist file for telescopic_ota
//Generated by UMN for ALIGN project 


module telescopic_ota ( vbiasnd, vss, vbiasp1, vinp, vdd, vbiasp2, voutn, vbiasn, d1, vinn, voutp ); 
input vbiasnd, vss, vbiasp1, vinp, vdd, vbiasp2, voutn, vbiasn, d1, vinn, voutp;

Switch_NMOS_n12_X3_Y3 m0 ( .D(net8), .G(vinp), .S(net10) ); 
Switch_PMOS_n12_X1_Y1 m1 ( .D(net06), .G(vbiasp1), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 m2 ( .D(net012), .G(vbiasp1), .S(vdd) ); 
Switch_NMOS_n12_X3_Y3 m3 ( .D(net014), .G(vinn), .S(net10) ); 
Switch_NMOS_n12_X3_Y1 m4 ( .D(net10), .G(vbiasnd), .S(vss) ); 
DCL_NMOS_n12_X2_Y1 m5 ( .D(d1), .S(vss) ); 
Switch_PMOS_n12_X2_Y1 m6 ( .D(voutn), .G(vbiasp2), .S(net06) ); 
Switch_PMOS_n12_X2_Y1 m7 ( .D(voutp), .G(vbiasp2), .S(net012) ); 
Switch_NMOS_n12_X3_Y1 m8 ( .D(voutp), .G(vbiasn), .S(net014) ); 
Switch_NMOS_n12_X3_Y1 m9 ( .D(voutn), .G(vbiasn), .S(net8) ); 

endmodule
