//Verilog block level netlist file for sc_dc_dc_converter
//Generated by UMN for ALIGN project 


module sc_dc_dc_converter ( phi1, phi2, vin, vout ); 
input phi1, phi2, vin, vout;

Switch_NMOS_B_nfin10000_n12_X139_Y6_RVT m8 ( .B(vss), .D(vout), .G(phi1), .S(net7) ); 
Switch_NMOS_B_nfin10000_n12_X139_Y6_RVT m6 ( .B(vss), .D(vout), .G(phi2), .S(net8) ); 
Switch_NMOS_B_nfin10000_n12_X139_Y6_RVT m3 ( .B(vss), .D(vout), .G(phi2), .S(net10) ); 
Cap_1000f c1 ( .MINUS(net8), .PLUS(net7) ); 
Cap_1000f c0 ( .MINUS(net9), .PLUS(net10) ); 
CMC_S_NMOS_B_nfin10000_n12_X139_Y6_RVT m5_m0 ( .B(vss), .DA(net9), .DB(net10), .G(phi1), .SA(net8), .SB(vin) ); 
CMC_NMOS_nfin10000_n12_X139_Y6_RVT m7_m4 ( .DA(net7), .DB(net9), .G(phi2), .S(vss) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd;
endmodule
`endcelldefine
