//Verilog block level netlist file for BUFFER_VREFP_ZHU
//Generated by UMN for ALIGN project 


module CMB_NMOS_2 ( B, DA, DB, DC, S ); 
input B, DA, DB, DC, S;

Switch_NMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 
SCM_NMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .S(S), .DB(DB) ); 

endmodule

module CMB_NMOS_3 ( B, DA, DB, DC, DD, S ); 
input B, DA, DB, DC, DD, S;

Switch_NMOS_n12_X1_Y1 M3 ( .B(B), .D(DD), .G(DA), .S(S) ); 
CMB_NMOS_2 M0_M2_M1 ( .B(B), .DA(DA), .S(S), .DB(DC), .DC(DB) ); 

endmodule

module BUFFER_VREFP_ZHU ( ibias, vin_vrefp, vrefp ); 
input ibias, vin_vrefp, vrefp;

Dcap_PMOS_n12_X1_Y1 xm8 ( .B(vdd), .S(vdd), .G(net030) ); 
Switch_PMOS_n12_X1_Y1 xm28 ( .B(vdd), .D(vrefp), .G(net26), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm15 ( .B(vdd), .D(net026), .G(net037), .S(vdd) ); 
Dcap_PMOS_n12_X1_Y1 xm9 ( .B(vdd), .S(vdd), .G(net037) ); 
CMB_NMOS_3 xm5_xm30_xm4_xm21 ( .B(gnd), .DA(ibias), .S(gnd), .DB(net26), .DC(net16), .DD(net030) ); 
SCM_PMOS_n12_X1_Y1 xm3_xm2 ( .B(vdd), .DA(net14), .S(vdd), .DB(net037) ); 
LS_PMOS_n12_X1_Y1 xm27_xm29 ( .B(vdd), .DA(net030), .SA(net026), .DB(net26), .SB(vrefp) ); 
DP_NMOS_n12_X1_Y1 xm1_xm0 ( .B(gnd), .DA(net037), .GA(vin_vrefp), .S(net16), .DB(net14), .GB(net026) ); 

endmodule

`celldefine
module global_power;
supply0 gnd;
supply1 vdd;
endmodule
`endcelldefine
