//Verilog block level netlist file for BUFFER_VCM_FINAL3
//Generated by UMN for ALIGN project 


module DP_PAIR_PMOS ( B, DA, DB, DC, DD, GB, S ); 
input B, DA, DB, DC, DD, GB, S;

SCM_PMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DC), .S(S), .DB(DA) ); 
CMC_PMOS_S_n12_X1_Y1 M3_M2 ( .B(B), .DA(DD), .G(GB), .S(S), .DB(DB) ); 

endmodule

module CMB_PMOS_2 ( B, DA, DB, DC, S ); 
input B, DA, DB, DC, S;

Switch_PMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 
SCM_PMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .S(S), .DB(DB) ); 

endmodule

module LSB_NMOS_2 ( B, DA, DB, DC, SA, SB, SC ); 
input B, DA, DB, DC, SA, SB, SC;

Switch_NMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(SC) ); 
LS_NMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .SA(SA), .DB(DB), .SB(SB) ); 

endmodule

module BUFFER_VCM_FINAL3 ( ibias, vcm_in, vout ); 
input ibias, vcm_in, vout;

Dummy1_NMOS_n12_X1_Y1 xm3 ( .B(gnd), .S(net050) ); 
Dummy1_NMOS_n12_X1_Y1 xm11 ( .B(gnd), .S(net044) ); 
Dummy1_NMOS_n12_X1_Y1 xm4 ( .B(gnd), .S(net053) ); 
Dummy1_NMOS_n12_X1_Y1 xm5 ( .B(gnd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 xm7 ( .B(gnd), .S(vout) ); 
Dummy1_NMOS_n12_X1_Y1 xm9 ( .B(gnd), .S(net061) ); 
Dummy1_NMOS_n12_X1_Y1 xm8 ( .B(gnd), .S(net047) ); 
Dummy1_NMOS_n12_X1_Y1 xm12 ( .B(gnd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 xm10 ( .B(gnd), .S(net060) ); 
Dummy1_PMOS_n12_X1_Y1 xm1 ( .B(vdd), .S(net052) ); 
Dummy1_PMOS_n12_X1_Y1 xm0 ( .B(vdd), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 xm13 ( .B(vdd), .S(vdd) ); 
DP_PAIR_PMOS xm20_xm21_xm19_xm18 ( .B(vdd), .DC(vout), .S(net052), .DA(net050), .DB(net053), .GB(vcm_in), .DD(net047) ); 
CMB_PMOS_2 xm29_xm17_xm30 ( .B(vdd), .DA(ibias), .S(vdd), .DB(net052), .DC(net044) ); 
SCM_NMOS_n12_X1_Y1 xm22_xm25 ( .B(gnd), .DA(net050), .S(gnd), .DB(net061) ); 
SCM_NMOS_n12_X1_Y1 xm23_xm24 ( .B(gnd), .DA(net053), .S(gnd), .DB(net060) ); 
SCM_PMOS_n12_X1_Y1 xm33_xm32 ( .B(vdd), .DA(net047), .S(vdd), .DB(vout) ); 
LSB_NMOS_2 xm31_xm26_xm27 ( .B(gnd), .DA(net044), .SA(gnd), .DB(vout), .SB(net060), .DC(net047), .SC(net061) ); 

endmodule

`celldefine
module global_power;
supply0 gnd;
supply1 vdd;
endmodule
`endcelldefine
