//Verilog block level netlist file for OTA_FF_2s_v3e
//Generated by UMN for ALIGN project 


module CASCODED_SCM_PMOS ( B, DA, DC, GA, S ); 
input B, DA, DC, GA, S;

Switch_PMOS_n12_X1_Y1 M0 ( .B(B), .D(DA), .G(GA), .S(DB) ); 
Switch_PMOS_n12_X1_Y1 M1 ( .B(B), .D(DB), .G(DA), .S(S) ); 
Switch_PMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 

endmodule

module CASCODED_CMB_PMOS_2 ( B, DA, DC, DD, GA, S ); 
input B, DA, DC, DD, GA, S;

Switch_PMOS_n12_X1_Y1 M3 ( .B(B), .D(DD), .G(DA), .S(S) ); 
CASCODED_SCM_PMOS M0_M1_M2 ( .B(B), .DA(DA), .GA(GA), .S(S), .DC(DC) ); 

endmodule

module CASCODED_CMB_PMOS_3 ( B, DA, DC, DD, DE, GA, S ); 
input B, DA, DC, DD, DE, GA, S;

Switch_PMOS_n12_X1_Y1 M4 ( .B(B), .D(DE), .G(DA), .S(S) ); 
CASCODED_CMB_PMOS_2 M0_M1_M3_M2 ( .B(B), .DA(DA), .GA(GA), .S(S), .DC(DD), .DD(DC) ); 

endmodule

module CMB_NMOS_2 ( B, DA, DB, DC, S ); 
input B, DA, DB, DC, S;

Switch_NMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 
SCM_NMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .S(S), .DB(DB) ); 

endmodule

module dummy_hier_m50_m20 ( cmfb, on, on1, op, op1 ); 
input cmfb, on, on1, op, op1;

Dcap_NMOS_n12_X1_Y1 m2 ( .B(avss), .S(avss), .G(on1) ); 
CMB_NMOS_2 m29_m14_m13 ( .B(avss), .DA(cmfb), .S(avss), .DB(op1), .DC(on1) ); 
Switch_NMOS_n12_X1_Y1 m19 ( .B(avss), .D(op), .G(on1), .S(avss) ); 
Dcap_NMOS_n12_X1_Y1 m66 ( .B(avss), .S(avss), .G(on1) ); 
Dcap_NMOS_n12_X1_Y1 m64 ( .B(avss), .S(avss), .G(op1) ); 
Switch_NMOS_n12_X1_Y1 m21 ( .B(avss), .D(on), .G(op1), .S(avss) ); 
Dcap_NMOS_n12_X1_Y1 m7 ( .B(avss), .S(avss), .G(op1) ); 

endmodule
