//Verilog block level netlist file for current_mirror_ota
//Generated by UMN for ALIGN project 


module current_mirror_ota ( vbiasnd, vdd, vinp, vss, id, vinn, voutp ); 
input vbiasnd, vdd, vinp, vss, id, vinn, voutp;

Switch_PMOS_n10_X6_Y4 m18s ( .D(voutp), .G(net27), .S(vdd) ); 
DCL_PMOS_n10_X3_Y2 m19 ( .D(net27), .S(vdd) ); 
Switch_PMOS_n10_X6_Y4 m20s ( .D(vbiasnd), .G(net16), .S(vdd) ); 
DCL_PMOS_n10_X3_Y2 m21 ( .D(net16), .S(vdd) ); 
SCM_NMOS_n10_X1_Y1 m14_m16 ( .DA(id), .DB(net24), .S(vss) ); 
SCM_NMOS_n10_X3_Y1 m11_m10 ( .DA(vbiasnd), .DB(voutp), .S(vss) ); 
DP_NMOS_n10_X3_Y1 m17_m15 ( .DA(net16), .GA(vinn), .S(net24), .DB(net27), .GB(vinp) ); 

endmodule
