//Verilog block level netlist file for variable_gain_amplifier
//Generated by UMN for ALIGN project 


module variable_gain_amplifier ( s0, s1, s2, vin1, vin2, vmirror_vga, vout_vga1, vout_vga2 ); 
input s0, s1, s2, vin1, vin2, vmirror_vga, vout_vga1, vout_vga2;

Switch_NMOS_B_nfin48_nf1_m1_n12_X2_Y2 MI01 ( .B(vgnd), .D(vout_vga2), .G(vin2), .S(net3) ); 
Switch_NMOS_B_nfin48_n12_X2_Y2 MI00 ( .B(vgnd), .D(vout_vga1), .G(vin1), .S(net3) ); 
Switch_NMOS_B_nfin72_n12_X3_Y2 Msw0 ( .B(vgnd), .D(net5), .G(s0), .S(net5p) ); 
Switch_NMOS_nfin72_n12_X3_Y2 MI12 ( .D(net5p), .G(vmirror_vga), .S(vgnd) ); 
Switch_NMOS_B_nfin144_n12_X4_Y3 Msw1 ( .B(vgnd), .D(net4), .G(s1), .S(net4p) ); 
Switch_NMOS_nfin144_n12_X4_Y3 MI22 ( .D(net4p), .G(vmirror_vga), .S(vgnd) ); 
Switch_NMOS_B_nfin288_n12_X6_Y4 Msw2 ( .B(vgnd), .D(net6), .G(s2), .S(net6p) ); 
Switch_NMOS_nfin288_n12_X6_Y4 MI32 ( .D(net6p), .G(vmirror_vga), .S(vgnd) ); 
Res_r400 R5 ( .MINUS(vps), .PLUS(vout_vga2) ); 
Res_r400 R6 ( .MINUS(vps), .PLUS(vout_vga1) ); 
SCM_NMOS_nfin72_nf1_m1_n12_X3_Y2 MI03_MI02 ( .DA(vmirror_vga), .DB(net3), .S(vgnd) ); 
DP_NMOS_B_nfin48_n12_X4_Y1 MI11_MI10 ( .B(vgnd), .DA(vout_vga2), .DB(vout_vga1), .GA(vin2), .GB(vin1), .S(net5) ); 
DP_NMOS_B_nfin96_n12_X8_Y1 MI21_MI20 ( .B(vgnd), .DA(vout_vga2), .DB(vout_vga1), .GA(vin2), .GB(vin1), .S(net4) ); 
DP_NMOS_B_nfin192_n12_X8_Y2 MI31_MI30 ( .B(vgnd), .DA(vout_vga2), .DB(vout_vga1), .GA(vin2), .GB(vin1), .S(net6) ); 

endmodule

`celldefine
module global_power;
supply0 vgnd;
supply1 vps;
endmodule
`endcelldefine
