//Verilog block level netlist file for ldo_error_amp
//Generated by UMN for ALIGN project 


module CASCODED_SCM_NMOS ( B, DA, DC, GA, S ); 
input B, DA, DC, GA, S;

Switch_NMOS_n12_X2_Y1 M0 ( .B(B), .D(DA), .G(GA), .S(DB) ); 
Switch_NMOS_n12_X2_Y1 M1 ( .B(B), .D(DB), .G(DA), .S(S) ); 
Switch_NMOS_n12_X2_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 

endmodule

module CASCODED_CMC_NMOS ( B, DA, DB, GA, S ); 
input B, DA, DB, GA, S;

Switch_NMOS_n12_X2_Y1 M1 ( .B(B), .D(DB), .G(GA), .S(SB) ); 
CASCODED_SCM_NMOS M0_M2_M3 ( .B(B), .DA(DA), .GA(GA), .S(S), .DC(SB) ); 

endmodule

module CMB_PMOS_2 ( B, DA, DB, DC, S ); 
input B, DA, DB, DC, S;

Switch_PMOS_n12_X3_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 
SCM_PMOS_n12_X3_Y1 M0_M1 ( .B(B), .DA(DA), .S(S), .DB(DB) ); 

endmodule

module SCM_PMOS_type1 ( B, DA, DB, S ); 
input B, DA, DB, S;

DCL_PMOS_n12_X1_Y1 M0 ( .B(B), .D(DA), .S(S) ); 
Switch_PMOS_n12_X2_Y1 M1 ( .B(B), .D(DB), .G(DA), .S(S) ); 

endmodule

module LSB_PMOS_2 ( B, DA, DB, DC, SA, SB, SC ); 
input B, DA, DB, DC, SA, SB, SC;

Switch_PMOS_n12_X3_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(SC) ); 
LS_PMOS_n12_X4_Y2 M0_M1 ( .B(B), .DA(DA), .SA(SA), .DB(DB), .SB(SB) ); 

endmodule

module ldo_error_amp ( vbias_an, vbias_bf, vfb, vg, vref ); 
input vbias_an, vbias_bf, vfb, vg, vref;

Switch_NMOS_n12_X1_Y1 mn56 ( .B(vss_x), .D(vbias6), .G(vbias_bf), .S(vss_x) ); 
Dcap_NMOS_n12_X1_Y1 mn40 ( .B(vss_x), .S(vss_x), .G(vbias_bf) ); 
Switch_NMOS_n12_X1_Y1 mn41 ( .B(vss_x), .D(vbias4), .G(vbias_an), .S(vss_x) ); 
Switch_NMOS_n12_X1_Y1 mn21 ( .B(vss_x), .D(vbias2), .G(vbias1), .S(vbias3) ); 
Switch_NMOS_n12_X2_Y1 mn55 ( .B(vss_x), .D(v3_d), .G(vbias_bf), .S(vss_x) ); 
Dcap_NMOS_n12_X1_Y1 mn3 ( .B(vss_x), .S(vss_x), .G(vbias_an) ); 
Switch_NMOS_n12_X2_Y1 mn2 ( .B(vss_x), .D(vcom1), .G(vbias_an), .S(vss_x) ); 
DCL_PMOS_n12_X1_Y1 mmp5 ( .B(vcc_nom), .D(vg), .S(vcc_nom) ); 
Switch_PMOS_n12_X2_Y1 mmp1 ( .B(vcc_nom), .D(v3_d), .G(v3), .S(vg) ); 
Switch_NMOS_n12_X1_Y1 mmn322 ( .B(vss_x), .D(vg), .G(v3_d), .S(vss_x) ); 
DCL_NMOS_n12_X2_Y2 mmn42 ( .B(vss_x), .D(vbias3), .S(vbias4) ); 
CASCODED_CMC_NMOS mn38_mn39_mn37_mn20 ( .B(vss_x), .DA(v4), .GA(vbias3), .DB(v3), .S(vss_x) ); 
CMB_PMOS_2 mp34_mp28_mp22 ( .B(vcc_nom), .DA(vbias1), .S(vcc_nom), .DB(v2), .DC(v1) ); 
SCM_PMOS_n12_X2_Y1 mp41_mp4 ( .B(vcc_nom), .DA(vbias6), .S(vcc_nom), .DB(vg) ); 
LSB_PMOS_2 mmp33_mmp30_mmp29 ( .B(vcc_nom), .DA(vbias2), .SA(vbias1), .DB(v3), .SB(v1), .DC(v4), .SC(v2) ); 
DP_NMOS_n12_X5_Y1 mn23_mn22 ( .B(vss_x), .DA(v2), .GA(vfb), .S(vcom1), .DB(v1), .GB(vref) ); 

endmodule

`celldefine
module global_power;
supply0 vss_x;
supply1 vcc_nom;
endmodule
`endcelldefine
