//Verilog block level netlist file for adder
//Generated by UMN for ALIGN project 


module adder ( n1, n2, vin, vout ); 
input n1, n2, vin, vout;

Switch_NMOS_nfin48_n12_X2_Y2_ST2 xI0|MN0 ( .D(vout), .G(vbn1), .S(vgnd) ); 
Switch_PMOS_nfin48_n12_X2_Y2_ST2 xI1|MP0 ( .D(vout), .G(vbp1), .S(vps) ); 
Res_r20000 R0 ( .MINUS(vbn1), .PLUS(n1) ); 
Res_r20000 R1 ( .MINUS(vbp1), .PLUS(n2) ); 
Res_r500 R2 ( .MINUS(vps), .PLUS(vout) ); 
Cap_cc C0_C1 ( .MINUS0(vbn1), .MINUS1(vbp1), .PLUS0(vin), .PLUS1(vin) ); 

endmodule

`celldefine
module global_power;
supply0 vgnd;
supply1 vps;
endmodule
`endcelldefine
