//Verilog block level netlist file for SW_Cres_v3_5
//Generated by UMN for ALIGN project 


module SW_Cres_v3_5 ( CK, VRCTL, VRN, VRNX, VRP, VRPX ); 
input CK, VRCTL, VRN, VRNX, VRP, VRPX;

Dcap_NMOS_n12_X1_Y1 MM3 ( .B(DVSS), .S(VRN), .G(CLK) ); 
Switch_NMOS_n12_X1_Y1 MM2 ( .B(DVSS), .D(VRN), .G(net010), .S(VRNX) ); 
Dcap_PMOS_n12_X1_Y1 MM4 ( .B(DVDD), .S(VRP), .G(net018) ); 
Switch_PMOS_n12_X1_Y1 MM1 ( .B(DVDD), .D(VRP), .G(CLK), .S(VRPX) ); 
ND2D1LVT XI11 ( .A1(CK), .A2(VRCTL), .ZN(net010), .VDD(DVDD), .VSS(DVSS) ); 
INVD0LVT XI5 ( .I(CLK), .ZN(net018), .VDD(DVDD), .VSS(DVSS) ); 
INVD0LVT XI6 ( .I(net010), .ZN(CLK), .VDD(DVDD), .VSS(DVSS) ); 

endmodule

module ND2D1LVT ( A1, A2, VDD, VSS, ZN ); 
input A1, A2, VDD, VSS, ZN;

Switch_NMOS_n12_X1_Y1 MMI1_M_u3 ( .B(VSS), .D(ZN), .G(A1), .S(net1) ); 
Switch_NMOS_n12_X1_Y1 MMI1_M_u4 ( .B(VSS), .D(net1), .G(A2), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u1 ( .B(VDD), .D(ZN), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI1_M_u2 ( .B(VDD), .D(ZN), .G(A2), .S(VDD) ); 

endmodule

module INVD0LVT ( I, VDD, VSS, ZN ); 
input I, VDD, VSS, ZN;

Switch_NMOS_n12_X1_Y1 MMU1_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU1_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 

endmodule

`celldefine
module global_power;
supply0 DVSS;
supply1 DVDD;
endmodule
`endcelldefine
