//Verilog block level netlist file for switched_capacitor_filter
//Generated by UMN for ALIGN project 


module switched_capacitor_filter ( agnd, id, vinn, vinp, voutn, voutp ); 
input agnd, id, vinn, vinp, voutn, voutp;

Switch_NMOS_B_nfin12_n12_X1_Y1_RVT m0 ( .B(vss), .D(voutn), .G(phi1), .S(net67) ); 
Switch_NMOS_B_nfin12_n12_X1_Y1_RVT m7 ( .B(vss), .D(net66), .G(phi1), .S(net63) ); 
Switch_NMOS_B_nfin12_n12_X1_Y1_RVT m6 ( .B(vss), .D(net72), .G(phi1), .S(vinn) ); 
Switch_NMOS_B_nfin12_n12_X1_Y1_RVT m3 ( .B(vss), .D(agnd), .G(phi2), .S(net67) ); 
Switch_NMOS_B_nfin12_n12_X1_Y1_RVT m5 ( .B(vss), .D(agnd), .G(phi2), .S(net63) ); 
Switch_NMOS_B_nfin12_n12_X1_Y1_RVT m4 ( .B(vss), .D(net72), .G(phi2), .S(agnd) ); 
Switch_NMOS_B_nfin12_n12_X1_Y1_RVT m8 ( .B(vss), .D(net60), .G(phi2), .S(agnd) ); 
Switch_NMOS_B_nfin12_n12_X1_Y1_RVT m11 ( .B(vss), .D(agnd), .G(phi2), .S(net68) ); 
Switch_NMOS_B_nfin12_n12_X1_Y1_RVT m9 ( .B(vss), .D(agnd), .G(phi2), .S(net62) ); 
Switch_NMOS_B_nfin12_n12_X1_Y1_RVT m10 ( .B(vss), .D(net64), .G(phi1), .S(net62) ); 
Switch_NMOS_B_nfin12_n12_X1_Y1_RVT m12 ( .B(vss), .D(net60), .G(phi1), .S(vinp) ); 
Switch_NMOS_B_nfin12_n12_X1_Y1_RVT m14 ( .B(vss), .D(voutp), .G(phi1), .S(net68) ); 
telescopic_ota xi0 ( .d1(id), .vbiasn(vbiasn), .vbiasp1(vbiasp1), .vbiasp2(vbiasp2), .vinn(net64), .vinp(net66), .voutn(voutn), .voutp(voutp) ); 
Cap_cc c0_c4 ( .MINUS0(net63), .MINUS1(net60), .PLUS0(net72), .PLUS1(net62) ); 
Cap_cc c5_c2 ( .MINUS0(vinn), .MINUS1(net66), .PLUS0(net64), .PLUS1(vinp) ); 
Cap_cc c6_c3 ( .MINUS0(net64), .MINUS1(voutn), .PLUS0(voutp), .PLUS1(net66) ); 
Cap_cc c7_c1 ( .MINUS0(net68), .MINUS1(net67), .PLUS0(net62), .PLUS1(net63) ); 
Cap_cc c9_c8 ( .MINUS0(vss), .MINUS1(voutn), .PLUS0(voutp), .PLUS1(vss) ); 

endmodule

module telescopic_ota ( d1, vbiasn, vbiasp1, vbiasp2, vinn, vinp, voutn, voutp ); 
input d1, vbiasn, vbiasp1, vbiasp2, vinn, vinp, voutn, voutp;

DCL_NMOS_nfin24_n12_X2_Y1_RVT m5 ( .D(d1), .S(vss) ); 
Switch_NMOS_nfin36_n12_X3_Y1_RVT m4 ( .D(net10), .G(d1), .S(vss) ); 
Switch_PMOS_nfin24_n12_X2_Y1_RVT m7 ( .D(voutp), .G(vbiasp2), .S(net012) ); 
Switch_PMOS_nfin24_n12_X2_Y1_RVT m6 ( .D(voutn), .G(vbiasp2), .S(net06) ); 
CMC_S_NMOS_B_nfin36_n12_X3_Y1_RVT m9_m8 ( .B(vss), .DA(voutn), .DB(voutp), .G(vbiasn), .SA(net8), .SB(net014) ); 
CMC_PMOS_nfin12_n12_X1_Y1_RVT m2_m1 ( .DA(net012), .DB(net06), .G(vbiasp1), .S(vdd) ); 
DP_NMOS_B_nfin72_n12_X6_Y1_RVT m3_m0 ( .B(vss), .DA(net014), .DB(net8), .GA(vinn), .GB(vinp), .S(net10) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd;
endmodule
`endcelldefine
