//Verilog block level netlist file for COMP_GM_STAGE_0415
//Generated by UMN for ALIGN project 


module tgate ( D, GA, GB, S ); 
input D, GA, GB, S;

Switch_NMOS_n12_X1_Y1 M0 ( .B(BN), .D(D), .G(GA), .S(S) ); 
Switch_PMOS_n12_X1_Y1 M1 ( .B(BP), .D(D), .G(GB), .S(S) ); 

endmodule

module COMP_GM_STAGE_0415 ( calm, calp, cco_icalm, cco_icalp, clk, ictrm, ictrp, inm, inp, outm, outp, pre_charge, valid_vco, vbn, vbp, vcc_comp, vcc_gm, vcm ); 
input calm, calp, cco_icalm, cco_icalp, clk, ictrm, ictrp, inm, inp, outm, outp, pre_charge, valid_vco, vbn, vbp, vcc_comp, vcc_gm, vcm;

Switch_PMOS_n12_X1_Y1 xm7 ( .B(vcc_gm), .D(net78), .G(valid_vco_b), .S(vbp) ); 
Switch_PMOS_n12_X1_Y1 xm4 ( .B(vcc_gm), .D(net78), .G(valid_vco_d), .S(vcc_gm) ); 
Dummy1_PMOS_n12_X1_Y1 xm45 ( .B(net070), .S(net070) ); 
Dummy1_PMOS_n12_X1_Y1 xm86 ( .B(vcc_comp), .S(vcc_comp) ); 
Dcap_PMOS_n12_X1_Y1 xm81 ( .B(net054), .S(net054), .G(calm) ); 
Dcap_PMOS_n12_X1_Y1 xm13 ( .B(net030), .S(net030), .G(calp) ); 
Switch_NMOS_n12_X1_Y1 xm83 ( .B(gnd), .D(outm), .G(net054), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm21 ( .B(gnd), .D(outp), .G(net030), .S(gnd) ); 
Dcap_PMOS_n12_X1_Y1 xm57 ( .B(vcc_gm), .S(vcc_gm), .G(vbp) ); 
Dcap_PMOS_n12_X1_Y1 xm56 ( .B(vcc_gm), .S(vcc_gm), .G(vbp) ); 
Switch_PMOS_n12_X1_Y1 xm52 ( .B(net036), .D(net070), .G(clkb), .S(net036) ); 
Switch_PMOS_n12_X1_Y1 xm51 ( .B(vcc_gm), .D(net036), .G(vbp), .S(vcc_comp) ); 
Switch_PMOS_n12_X1_Y1 xm0 ( .B(vcc_gm), .D(net070), .G(net78), .S(vcc_gm) ); 
INVD1BWP xi4<1> ( .i(valid_vco), .zn(valid_vco_b), .vss(gnd) ); 
INVD1BWP xi4<0> ( .i(valid_vco), .zn(valid_vco_b), .vss(gnd) ); 
INVD1BWP xi5<1> ( .i(valid_vco_b), .zn(valid_vco_d), .vss(gnd) ); 
INVD1BWP xi5<0> ( .i(valid_vco_b), .zn(valid_vco_d), .vss(gnd) ); 
INVD1BWP xi6<1> ( .i(clk), .zn(clkb), .vss(gnd) ); 
INVD1BWP xi6<0> ( .i(clk), .zn(clkb), .vss(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm38 ( .B(gnd), .D(ictrm), .G(net089), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm33 ( .B(gnd), .D(ictrp), .G(net059), .S(gnd) ); 
Dcap_NMOS_n12_X1_Y1 xm12 ( .B(gnd), .S(gnd), .G(vbn) ); 
Dcap_NMOS_n12_X1_Y1 xm3 ( .B(gnd), .S(gnd), .G(vbn) ); 
Dcap_NMOS_n12_X1_Y1 xm1 ( .B(gnd), .S(gnd), .G(vbn) ); 
COMP_GM_STAGE_BIAS_0415 xi0 ( .vbn(vbn), .vbp(vbp), .vcm(vcm), .vdd_a(vcc_gm) ); 
CCP_NMOS_S_n12_X1_Y1 xm79_xm18 ( .B(gnd), .DA(net054), .DB(net030), .S(gnd) ); 
CMC_NMOS_S_n12_X1_Y1 xm80_xm23 ( .B(gnd), .DA(net054), .G(clkb), .S(gnd), .DB(net030) ); 
CMC_NMOS_S_n12_X1_Y1 xm75_xm26 ( .B(gnd), .DA(net90), .G(clkb), .S(gnd), .DB(net83) ); 
CMC_NMOS_S_n12_X1_Y1 xm10_xm5 ( .B(gnd), .DA(net089), .G(valid_vco_b), .S(gnd), .DB(net059) ); 
CMC_NMOS_S_n12_X1_Y1 xm44_xm43 ( .B(gnd), .DA(ictrp), .G(valid_vco_b), .S(pre_charge), .DB(ictrm) ); 
CMC_NMOS_S_n12_X1_Y1 xm9_xm8 ( .B(gnd), .DA(net089), .G(valid_vco_d), .S(vbn), .DB(net059) ); 
CMC_PMOS_S_n12_X1_Y1 xm91_xm90 ( .B(vcc_gm), .DA(net89), .G(valid_vco_d), .S(vcc_gm), .DB(net073) ); 
CCP_PMOS_n12_X1_Y1 xm78_xm2 ( .B(vcc_comp), .DA(net054), .DB(net030), .SA(net90), .SB(net83) ); 
tgate xm63_xm64 ( .D(ictrm), .GA(valid_vco_d), .S(net019), .GB(valid_vco_b) ); 
tgate xm77_xm76 ( .D(ictrp), .GA(valid_vco_d), .S(net042), .GB(valid_vco_b) ); 
tgate xm19_xm17 ( .D(net83), .GA(valid_vco_b), .S(net019), .GB(valid_vco_d) ); 
tgate xm74_xm73 ( .D(net90), .GA(valid_vco_b), .S(net042), .GB(valid_vco_d) ); 
DP_PMOS_n12_X1_Y1 xm87_xm88 ( .B(vcc_gm), .DA(ictrp), .GA(net89), .S(vcc_gm), .DB(ictrm), .GB(net073) ); 
DP_PMOS_n12_X1_Y1 xm11_xm55 ( .B(net070), .DA(net019), .GA(inp), .S(net070), .DB(net042), .GB(inm) ); 
DP_PMOS_n12_X1_Y1 xm82_xm6 ( .B(vcc_comp), .DA(outm), .GA(net054), .S(vcc_comp), .DB(outp), .GB(net030) ); 
CMC_PMOS_n12_X1_Y1 xm92_xm89 ( .B(vcc_gm), .DA(net89), .G(valid_vco_b), .SA(cco_icalp), .DB(net073), .SB(cco_icalm) ); 

endmodule

module INVD1BWP ( i, vss, zn ); 
input i, vss, zn;

Switch_NMOS_n12_X1_Y1 m0 ( .B(vss), .D(zn), .G(i), .S(vss) ); 
Switch_PMOS_n12_X1_Y1 m1 ( .B(vdd), .D(zn), .G(i), .S(vdd) ); 

endmodule

module COMP_GM_STAGE_BIAS_0415 ( vbn, vbp, vcm, vdd_a ); 
input vbn, vbp, vcm, vdd_a;

Dcap_NMOS_n12_X1_Y1 xm4 ( .B(gnd), .S(gnd), .G(vbn) ); 
DCL_NMOS_n12_X1_Y1 xm0 ( .B(gnd), .D(vbn), .S(gnd) ); 
Switch_PMOS_n12_X1_Y1 xm1 ( .B(net5), .D(vbp), .G(vcm), .S(net5) ); 
Dummy1_PMOS_n12_X1_Y1 xm5 ( .B(net5), .S(vbp) ); 
Switch_PMOS_n12_X1_Y1 xm8 ( .B(vdd_a), .D(net5), .G(vbp), .S(vdd_a) ); 
Dcap_PMOS_n12_X1_Y1 xm3 ( .B(vdd_a), .S(vdd_a), .G(vbp) ); 

endmodule

`celldefine
module global_power;
supply0 gnd;
supply1 vdd;
endmodule
`endcelldefine
