//Verilog block level netlist file for five_transistor_ota_high_frequency
//Generated by UMN for ALIGN project 


module five_transistor_ota_high_frequency ( id_ota, vinn_ota, vinp_ota, vout_ota ); 
input id_ota, vinn_ota, vinp_ota, vout_ota;

Switch_PMOS_nfin12_nf2_m1_n12_X2_Y1_RVT m5 ( .D(vout_ota), .G(net19), .S(vdd_ota) ); 
DCL_PMOS_nfin12_nf2_n12_X2_Y1_RVT m4 ( .D(net19), .S(vdd_ota) ); 
DCL_NMOS_nfin12_nf2_m1_n12_X2_Y1_RVT m3 ( .D(id_ota), .S(vss_ota) ); 
Switch_NMOS_nfin12_nf16_m1_n12_X4_Y4_RVT m2 ( .D(net017), .G(id_ota), .S(vss_ota) ); 
DP_NMOS_B_nfin12_nf40_m1_n12_X20_Y2_RVT m1_m0 ( .B(vss_ota), .DA(vout_ota), .DB(net19), .GA(vinn_ota), .GB(vinp_ota), .S(net017) ); 

endmodule

`celldefine
module global_power;
supply0 vss_ota;
supply1 vdd_ota;
endmodule
`endcelldefine
