//Verilog block level netlist file for adder
//Generated by UMN for ALIGN project 


module adder ( n1, n2, vin, vout ); 
input n1, n2, vin, vout;

Switch_NMOS_n12_X2_Y2 xI0|MN0 ( .B(b), .D(vout), .G(vbn1), .S(vgnd) ); 
Switch_PMOS_n12_X2_Y2 xI1|MP0 ( .B(b), .D(vout), .G(vbp1), .S(vps) ); 
Res_20000 R0 ( .PLUS(n1), .MINUS(vbn1) ); 
Cap_48f C0 ( .PLUS(vbn1), .MINUS(vin) ); 
Res_20000 R1 ( .PLUS(n2), .MINUS(vbp1) ); 
Cap_48f C1 ( .PLUS(vbp1), .MINUS(vin) ); 
Res_500 R2 ( .PLUS(vout), .MINUS(vps) ); 

endmodule

`celldefine
module global_power;
supply0 vgnd;
supply1 vps;
endmodule
`endcelldefine
