//Verilog block level netlist file for high_speed_comparator
//Generated by UMN for ALIGN project 


module high_speed_comparator ( clk, v_in, vip, von, vop ); 
input clk, v_in, vip, von, vop;

Switch_PMOS_n12_X1_Y1 mmp5 ( .B(vdd_nom_123), .D(vy), .G(clk), .S(vdd_nom_123) ); 
Switch_PMOS_n12_X1_Y1 mmp7 ( .B(vdd_nom_123), .D(vop), .G(vyy), .S(vdd_nom_123) ); 
Switch_PMOS_n12_X1_Y1 mmp4 ( .B(vdd_nom_123), .D(vyy), .G(clk), .S(vdd_nom_123) ); 
Switch_PMOS_n12_X1_Y1 mmp6 ( .B(vdd_nom_123), .D(von), .G(vxx), .S(vdd_nom_123) ); 
Switch_PMOS_n12_X1_Y1 mmp3 ( .B(vdd_nom_123), .D(vx), .G(clk), .S(vdd_nom_123) ); 
Switch_PMOS_n12_X1_Y1 mmp2 ( .B(vdd_nom_123), .D(vxx), .G(clk), .S(vdd_nom_123) ); 
Switch_NMOS_n12_X4_Y2 mmn2 ( .B(vss), .D(vcom), .G(clk), .S(vss) ); 
Switch_NMOS_n12_X1_Y1 mmn5 ( .B(vss), .D(von), .G(vxx), .S(vss) ); 
Switch_NMOS_n12_X1_Y1 mmn6 ( .B(vss), .D(vop), .G(vyy), .S(vss) ); 
CCP_PMOS_S_n12_X4_Y1 mmp1_mmp0 ( .B(vdd_nom_123), .DA(vxx), .DB(vyy), .S(vdd_nom_123) ); 
CCP_NMOS_n12_X4_Y2 mmn4_mmn3 ( .B(vss), .DA(vxx), .DB(vyy), .SA(vx), .SB(vy) ); 
DP_NMOS_n12_X8_Y2 mmn1_mmn0 ( .B(vss), .DA(vy), .DB(vx), .GA(vip), .GB(v_in), .S(vcom) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd_nom_123;
endmodule
`endcelldefine
