//Verilog block level netlist file for powertrain_binary
//Generated by UMN for ALIGN project 


module powertrain_binary ( on_d[0], on_d[1], on_d[2], on_d[3], on_d[4], on_d[5], vout ); 
input on_d[0], on_d[1], on_d[2], on_d[3], on_d[4], on_d[5], vout;

powertrain_cell xu_pmos_1[2] ( .ond(on_d[1]), .vout(vout) ); 
powertrain_cell xu_pmos_1[1] ( .ond(on_d[1]), .vout(vout) ); 
powertrain_cell xu_pmos_5[32] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[31] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[30] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[29] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[28] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[27] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[26] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[25] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[24] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[23] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[22] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[21] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[20] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[19] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[18] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[17] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[16] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[15] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[14] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[13] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[12] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[11] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[10] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[9] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[8] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[7] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[6] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[5] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[4] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[3] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[2] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_5[1] ( .ond(on_d[5]), .vout(vout) ); 
powertrain_cell xu_pmos_4[16] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[15] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[14] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[13] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[12] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[11] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[10] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[9] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[8] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[7] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[6] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[5] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[4] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[3] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[2] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_4[1] ( .ond(on_d[4]), .vout(vout) ); 
powertrain_cell xu_pmos_3[8] ( .ond(on_d[3]), .vout(vout) ); 
powertrain_cell xu_pmos_3[7] ( .ond(on_d[3]), .vout(vout) ); 
powertrain_cell xu_pmos_3[6] ( .ond(on_d[3]), .vout(vout) ); 
powertrain_cell xu_pmos_3[5] ( .ond(on_d[3]), .vout(vout) ); 
powertrain_cell xu_pmos_3[4] ( .ond(on_d[3]), .vout(vout) ); 
powertrain_cell xu_pmos_3[3] ( .ond(on_d[3]), .vout(vout) ); 
powertrain_cell xu_pmos_3[2] ( .ond(on_d[3]), .vout(vout) ); 
powertrain_cell xu_pmos_3[1] ( .ond(on_d[3]), .vout(vout) ); 
powertrain_cell xu_pmos_2[4] ( .ond(on_d[2]), .vout(vout) ); 
powertrain_cell xu_pmos_2[3] ( .ond(on_d[2]), .vout(vout) ); 
powertrain_cell xu_pmos_2[2] ( .ond(on_d[2]), .vout(vout) ); 
powertrain_cell xu_pmos_2[1] ( .ond(on_d[2]), .vout(vout) ); 
powertrain_cell xu_pmos_0 ( .ond(on_d[0]), .vout(vout) ); 

endmodule

module powertrain_cell ( ond, vout ); 
input ond, vout;

Switch_PMOS_n12_X3_Y1 mmp0 ( .B(vcc), .D(vout), .G(ond), .S(vcc) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vcc;
endmodule
`endcelldefine
