//Verilog block level netlist file for sc_dc_dc_converter
//Generated by UMN for ALIGN project 


module sc_dc_dc_converter ( phi1, phi2, vin, vout ); 
input phi1, phi2, vin, vout;

Switch_NMOS_n12_X139_Y6 m3 ( .B(vss), .D(vout), .G(phi2), .S(net10) ); 
Cap_1000000f c1 ( .PLUS(net7), .MINUS(net8) ); 
Cap_1000000f c0 ( .PLUS(net10), .MINUS(net9) ); 
CMC_NMOS_S_n12_X139_Y6 m7_m4 ( .B(vss), .DA(net7), .G(phi2), .S(vss), .DB(net9) ); 
DP_NMOS_n12_X139_Y6 m6_m5 ( .B(vss), .DA(vout), .GA(phi2), .S(net8), .DB(net9), .GB(phi1) ); 
CMC_NMOS_n12_X139_Y6 m8_m0 ( .B(vss), .DA(vout), .G(phi1), .SA(net7), .DB(net10), .SB(vin) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd;
endmodule
`endcelldefine
