//Verilog block level netlist file for telescopic_ota_with_bias
//Generated by UMN for ALIGN project 


module CASCODED_SCM_PMOS ( B, DA, DC, GA, S ); 
input B, DA, DC, GA, S;

Switch_PMOS_n12_X5_Y2 M0 ( .B(B), .D(DA), .G(GA), .S(DB) ); 
Switch_PMOS_n12_X2_Y2 M1 ( .B(B), .D(DB), .G(DA), .S(S) ); 
Switch_PMOS_n12_X2_Y2 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 

endmodule

module CASCODED_CMC_PMOS ( B, DA, DB, GA, S ); 
input B, DA, DB, GA, S;

Switch_PMOS_n12_X5_Y2 M0 ( .B(B), .D(DA), .G(GA), .S(SA) ); 
CASCODED_SCM_PMOS M1_M3_M2 ( .B(B), .DA(DB), .GA(GA), .S(S), .DC(SA) ); 

endmodule

module LSB_NMOS_2 ( B, DA, DB, DC, SA, SB, SC ); 
input B, DA, DB, DC, SA, SB, SC;

Switch_NMOS_n12_X3_Y2 M2 ( .B(B), .D(DC), .G(DA), .S(SC) ); 
LS_NMOS_n12_X3_Y2 M0_M1 ( .B(B), .DA(DA), .SA(SA), .DB(DB), .SB(SB) ); 

endmodule

module telescopic_ota_with_bias ( d1, vinn, vinp, vout ); 
input d1, vinn, vinp, vout;

DCL_PMOS_n12_X1_Y1 m13 ( .B(vdd), .D(vbiasp), .S(vdd) ); 
CASCODED_CMC_PMOS m7_m6_m2_m1 ( .B(vdd), .DA(vout), .GA(vbiasp), .DB(vpgate), .S(vdd) ); 
SCM_NMOS_n12_X3_Y3 m5_m4 ( .B(vss), .DA(D1), .S(vss), .DB(net10) ); 
SCM_PMOS_n12_X1_Y1 m16_m17 ( .B(vdd), .DA(net9), .S(vdd), .DB(vbiasn) ); 
CMC_NMOS_S_n12_X1_Y1 m15_m12 ( .B(vss), .DA(net9), .G(d1), .S(vss), .DB(vbiasp) ); 
LSB_NMOS_2 m10_m9_m8 ( .B(vss), .DA(vbiasn), .SA(net10), .DB(vpgate), .SB(net8), .DC(vout), .SC(net014) ); 
DP_NMOS_n12_X4_Y3 m3_m0 ( .B(vss), .DA(net014), .GA(vinn), .S(net10), .DB(net8), .GB(vinp) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd;
endmodule
`endcelldefine
