//Verilog block level netlist file for Tristate_buffer
//Generated by UMN for ALIGN project 


module Tristate_buffer ( VSS, VDD, vout, enable, vin ); 
inout VSS, VDD, vout, enable, vin;

Switch_NMOS_10_1x1 M0 ( .D(net26), .G(enable), .S(VSS) ); 
Switch_NMOS_10_1x1 M1 ( .D(vout), .G(vin), .S(net26) ); 
Switch_PMOS_10_1x1 M2 ( .D(vout), .G(vin), .S(net30) ); 
Switch_PMOS_10_1x1 M3 ( .D(net30), .G(inv_out), .S(VDD) ); 
Switch_PMOS_10_1x1 M4 ( .D(inv_out), .G(enable), .S(VDD) ); 
Switch_NMOS_10_1x1 M5 ( .D(inv_out), .G(enable), .S(VSS) ); 

endmodule


// End HDL models
// Global nets module
`celldefine
module cds_globals;

supply0 VDD;
supply1 VSS;

endmodule
`endcelldefine