//Verilog block level netlist file for telescopic_ota
//Generated by UMN for ALIGN project 


module telescopic_ota ( vbiasnd, vss, vinn, voutn, voutp, vbiasp1, vinp, vbiasn, vbiasp2, vdd, d1 ); 
input vbiasnd, vss, vinn, voutn, voutp, vbiasp1, vinp, vbiasn, vbiasp2, vdd, d1;

CMC_PMOS_S_n12_X1_Y1 m2_m1 ( .DA(net012), .G(vbiasp1), .DB(net06), .S(vdd) ); 
CMFB_NMOS_n12_X3_Y1 m5_m4 ( .DA(d1), .S(vss), .DB(net10), .GB(vbiasnd) ); 
DP_NMOS_n12_X3_Y3 m3_m0 ( .DA(net014), .GA(vinn), .S(net10), .DB(net8), .GB(vinp) ); 
CMC_PMOS_n12_X2_Y1 m6_m7 ( .DA(voutn), .G(vbiasp2), .DB(voutp), .SA(net06), .SB(net012) ); 
CMC_NMOS_n12_X3_Y1 m9_m8 ( .DA(voutn), .G(vbiasn), .DB(voutp), .SA(net8), .SB(net014) ); 

endmodule
