//Verilog block level netlist file for switched_capacitor_filter
//Generated by UMN for ALIGN project 


module switched_capacitor_combination ( Vin, Vin_ota, Voutn, phi1, phi2 ); 
input Vin, Vin_ota, Voutn, phi1, phi2;

Cap_60fF c0 ( .MINUS(net63), .PLUS(net72) ); 
Cap_30fF c1 ( .MINUS(net67), .PLUS(net63) ); 
Cap_60fF c3 ( .MINUS(Voutn), .PLUS(Vin_ota) ); 
Switch_NMOS_n12_X2_Y1 m4 ( .D(net72), .G(phi2), .S(analog_gnd) ); 
Switch_NMOS_n12_X2_Y1 m6 ( .D(net72), .G(phi1), .S(Vin) ); 
DP_NMOS_n12_X2_Y1 m7_m5 ( .DA(Vin_ota), .GA(phi1), .S(net63), .DB(analog_gnd), .GB(phi2) ); 
DP_NMOS_n12_X2_Y1 m0_m3 ( .DA(Voutn), .GA(phi1), .S(net67), .DB(analog_gnd), .GB(phi2) ); 

endmodule


module switched_capacitor_filter ( voutn, voutp, vinp, vinn, id ); 
telescopic_ota xi0 ( .d1(id), .vbiasn(vbiasn), .vbiasnd(vbiasnd), .vbiasp1(vbiasp1), .vbiasp2(vbiasp2), .vinn(net64), .vinp(net66), .voutn(voutn), .voutp(voutp) ); 
switched_capacitor_combination m6_c0_m4_m3_m5_c1_m7_c3_m0 ( .Vin(vinn), .Vin_ota(net66), .Voutn(voutn), .phi1(phi1), .phi2(phi2) ); 
switched_capacitor_combination m12_c4_m8_m11_m9_c7_m10_c6_m14 ( .Vin(vinp), .Vin_ota(net64), .Voutn(voutp), .phi1(phi1), .phi2(phi2) ); 

endmodule

module telescopic_ota ( d1, vbiasn, vbiasnd, vbiasp1, vbiasp2, vinn, vinp, voutn, voutp ); 
input d1, vbiasn, vbiasnd, vbiasp1, vbiasp2, vinn, vinp, voutn, voutp;
specify
    specparam CDS_LIBNAME = "pcell";
    specparam CDS_CELLNAME = "telescopic_ota";
    specparam CDS_VIEWNAME = "schematic";
endspecify
CMC_PMOS_S_n12_X2_Y1 m2_m1 ( .DA(net012), .G(vbiasp1), .DB(net06), .S(analog_vdd) ); 
DP_NMOS_n12_X2_Y1 m3_m0 ( .DA(net014), .GA(vinn), .S(net10), .DB(net8), .GB(vinp) ); 
CMFB_NMOS_n12_X2_Y1 m5_m4 ( .DA(d1), .S(analog_gnd), .DB(net10), .GB(vbiasnd) ); 
CMC_PMOS_n12_X2_Y1 m6_m7 ( .DA(voutn), .G(vbiasp2), .DB(voutp), .SA(net06), .SB(net012) ); 
CMC_NMOS_n12_X2_Y1 m9_m8 ( .DA(voutn), .G(vbiasn), .DB(voutp), .SA(net8), .SB(net014) ); 

endmodule

`celldefine
module analog_power;
supply0 analog_gnd;
supply1 analog_vdd;
endmodule
`endcelldefine
