//Verilog block level netlist file for SAR_ADC_6b_2GSPS
//Generated by UMN for ALIGN project 


module SAR_ADC_6b_2GSPS ( CLK, DOUT<0>, DOUT<1>, DOUT<2>, DOUT<3>, DOUT<4>, DOUT<5>, IN, IP, REFN, REFP ); 
input CLK, DOUT<0>, DOUT<1>, DOUT<2>, DOUT<3>, DOUT<4>, DOUT<5>, IN, IP, REFN, REFP;

SUB3_CLK1 I11 ( .CK_E(QE), .I(CLK), .QIP(QIP), .QSN(QSN), .QSP(QSP), .QS_DEL_more(QD) ); 
SUB2_COMP_DUPLEX I18 ( .DN<1>(DN<1>), .DN<2>(DN<2>), .DP<1>(DP<1>), .DP<2>(DP<2>), .INN(ON), .INP(OP), .LAT<1>(LAT<1>), .LAT<2>(LAT<2>), .RDY<1>(RDY<1>), .RDY<2>(RDY<2>), .RS<1>(RS<1>), .RS<2>(RS<2>) ); 
SUB1_CDAC_6b_diff I27 ( .CTRLn<5>(N_Nch<5>), .CTRLn<4>(N_Nch<4>), .CTRLn<3>(N_Nch<3>), .CTRLn<2>(N_Nch<2>), .CTRLn<1>(N_Nch<1>), .CTRLp<5>(P_Nch<5>), .CTRLp<4>(P_Nch<4>), .CTRLp<3>(P_Nch<3>), .CTRLp<2>(P_Nch<2>), .CTRLp<1>(P_Nch<1>), .IN(IN), .IP(IP), .ON(ON), .OP(OP), .QSN(QSN), .QSP(QSP), .REFN(REFN), .REFP(REFP) ); 
SUB5_SEQ_TOP_6b_v2 I20 ( .DN<1>(DN<1>), .DN<2>(DN<2>), .DOUT<5>(DOUT<5>), .DOUT<4>(DOUT<4>), .DOUT<3>(DOUT<3>), .DOUT<2>(DOUT<2>), .DOUT<1>(DOUT<1>), .DOUT<0>(DOUT<0>), .DP<1>(DP<1>), .DP<2>(DP<2>), .ENV<2>(ENV<2>), .ENV<3>(ENV<3>), .ENV<4>(ENV<4>), .INITP(QIP), .N_Nch<5>(N_Nch<5>), .N_Nch<4>(N_Nch<4>), .N_Nch<3>(N_Nch<3>), .N_Nch<2>(N_Nch<2>), .N_Nch<1>(N_Nch<1>), .P_Nch<5>(P_Nch<5>), .P_Nch<4>(P_Nch<4>), .P_Nch<3>(P_Nch<3>), .P_Nch<2>(P_Nch<2>), .P_Nch<1>(P_Nch<1>), .QSP(QE), .RDY<1>(RDY<1>), .RDY<2>(RDY<2>) ); 
SUB3_CLK2 I10 ( .ENV<2>(ENV<2>), .ENV<3>(ENV<3>), .ENV<4>(ENV<4>), .LAT<1>(LAT<1>), .LAT<2>(LAT<2>), .QS_DEL(QD), .RDY<1>(RDY<1>), .RDY<2>(RDY<2>), .RS<1>(RS<1>), .RS<2>(RS<2>) ); 

endmodule

module SUB3_CLK1 ( CK_E, I, QIP, QSN, QSP, QS_DEL_more ); 
input CK_E, I, QIP, QSN, QSP, QS_DEL_more;

BUF_X4 I25 ( .Y(net073), .VNW(VDD), .VPW(VSS), .A(QS_DEL) ); 
INV_X4 I43 ( .Y(net025), .VNW(VDD), .VPW(VSS), .A(QS_DEL_more) ); 
INV_X4 I27 ( .Y(QS_DEL_more), .VNW(VDD), .VPW(VSS), .A(net062) ); 
INV_X6 I108 ( .Y(QS_DEL), .VNW(VDD), .VPW(VSS), .A(net062) ); 
INV_X6 I100 ( .Y(net37), .VNW(VDD), .VPW(VSS), .A(net35) ); 
BUF_X12 I121 ( .Y(CK_E), .VNW(VDD), .VPW(VSS), .A(net074) ); 
BUF_X12 I97 ( .Y(net033), .VNW(VDD), .VPW(VSS), .A(I) ); 
Cap_4f C13 ( .PLUS(QS_DEL), .MINUS(VSS) ); 
Cap_4f C10 ( .PLUS(VSS), .MINUS(net060) ); 
Cap_4f C11 ( .PLUS(VSS), .MINUS(net061) ); 
Cap_4f C12 ( .PLUS(VSS), .MINUS(net062) ); 
Cap_6f C5 ( .PLUS(VSS), .MINUS(net35) ); 
Cap_6f C15 ( .PLUS(VSS), .MINUS(net37) ); 
Cap_6f C7 ( .PLUS(VSS), .MINUS(net011) ); 
DLY2_X2 I41 ( .Y(net026), .VNW(VDD), .VPW(VSS), .A(net019) ); 
DLY2_X2 I104 ( .Y(net061), .VNW(VDD), .VPW(VSS), .A(net060) ); 
DLY2_X2 I102 ( .Y(net062), .VNW(VDD), .VPW(VSS), .A(net061) ); 
DLY2_X2 I18 ( .Y(net35), .VNW(VDD), .VPW(VSS), .A(net011) ); 
DLY2_X2 I46 ( .Y(net011), .VNW(VDD), .VPW(VSS), .A(net033) ); 
INV_X16 I109 ( .Y(QSP), .VNW(VDD), .VPW(VSS), .A(net076) ); 
INV_X16 I111 ( .Y(QSN), .VNW(VDD), .VPW(VSS), .A(net057) ); 
INV_X8 I120 ( .Y(QIP), .VNW(VDD), .VPW(VSS), .A(net025) ); 
INV_X8 I110 ( .Y(net076), .VNW(VDD), .VPW(VSS), .A(net057) ); 
BUF_X6 I112 ( .Y(net057), .VNW(VDD), .VPW(VSS), .A(net073) ); 
NAND2_X4 I40 ( .Y(net074), .VNW(VDD), .VPW(VSS), .A(net019), .B(net026) ); 
NAND2_X4 I101 ( .Y(net069), .VNW(VDD), .VPW(VSS), .A(net37), .B(net033) ); 
DLY4_X4 I29 ( .Y(net019), .VNW(VDD), .VPW(VSS), .A(net060) ); 
DLY4_X4 I22 ( .Y(net060), .VNW(VDD), .VPW(VSS), .A(net069) ); 

endmodule
