//Verilog block level netlist file for unity_gain_buffers
//Generated by UMN for ALIGN project 


module unity_gain_buffers ( vbias_an, vo_hs, vo_ls, vref_hs, vref_ls ); 
input vbias_an, vo_hs, vo_ls, vref_hs, vref_ls;

Switch_NMOS_nfin4_nf1_m4_n12_X2_Y1_ST2 xmn43 ( .D(vo_ls), .G(v_p1), .S(vss) ); 
Switch_NMOS_nfin4_nf1_m4_n12_X2_Y1_ST4 xmn41 ( .D(vbias4), .G(vbias_an), .S(vss) ); 
Dcap_NMOS_nfin4_nf1_m4_n12_X2_Y1_ST4 xmn3 ( .G(vbias_an), .S(vss) ); 
Switch_NMOS_nfin4_nf1_m8_n12_X3_Y1_ST4 xmn2 ( .D(vcom_n), .G(vbias_an), .S(vss) ); 
DCL_NMOS_B_nfin4_nf2_m16_n12_X11_Y1 mmn42 ( .B(vss), .D(vbias_m), .S(vbias4) ); 
DCL_PMOS_B_nfin4_nf2_m16_n12_X11_Y1 mmp33 ( .B(vcc), .D(vbias_m), .S(vbias_n1) ); 
Switch_PMOS_nfin4_nf1_m8_n12_X3_Y1_ST4 xmp10 ( .D(vcom_p), .G(vbias_n1), .S(vcc) ); 
Switch_PMOS_nfin4_nf1_m4_n12_X2_Y1_ST2 xmp7 ( .D(vo_hs), .G(v_n2), .S(vcc) ); 
DCL_PMOS_nfin4_nf1_m4_n12_X2_Y1_ST4 xmp34 ( .D(vbias_n1), .S(vcc) ); 
SCM_NMOS_nfin4_nf1_m8_n12_X3_Y1_ST4 xmn0_xmn1 ( .DA(v_p2), .DB(v_p1), .S(vss) ); 
SCM_PMOS_nfin4_nf1_m8_n12_X3_Y1_ST4 xmp28_xmp22 ( .DA(v_n1), .DB(v_n2), .S(vcc) ); 
DP_NMOS_B_nfin4_nf1_m20_n12_X7_Y1_ST2 xmn23_xmn22 ( .B(vss), .DA(v_n2), .DB(v_n1), .GA(vref_hs), .GB(vo_hs), .S(vcom_n) ); 
DP_PMOS_B_nfin4_nf1_m20_n12_X7_Y1_ST2 xmp8_xmp9 ( .B(vcc), .DA(v_p2), .DB(v_p1), .GA(vo_ls), .GB(vref_ls), .S(vcom_p) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vcc;
endmodule
`endcelldefine
