//Verilog block level netlist file for comparator_3
//Generated by UMN for ALIGN project 


module comparator_3 ( vss, vip, vin, vcc, vout, bias ); 
input vss, vip, vin, vcc, vout, bias;

Switch_NMOS_n12_X3_Y1 mn10 ( .D(9), .G(5), .S(8), .Bg(vss) ); 
Switch_NMOS_n12_X3_Y1 mn1 ( .D(2), .G(vip), .S(1), .Bg(vss) ); 
Switch_NMOS_n12_X3_Y1 mn11 ( .D(vout), .G(9), .S(vss), .Bg(vss) ); 
Switch_NMOS_n12_X3_Y1 mn12 ( .D(1), .G(bias), .S(vss), .Bg(vss) ); 
Switch_NMOS_n12_X3_Y1 mn2 ( .D(3), .G(vin), .S(1), .Bg(vss) ); 
DCL_NMOS_n12_X3_Y1 mn3 ( .D(4), .S(vss), .Bg(vss) ); 
DCL_NMOS_n12_X3_Y1 mn4 ( .D(5), .S(4), .Bg(vss) ); 
Switch_NMOS_n12_X3_Y1 mn5 ( .D(5), .G(6), .S(4), .Bg(vss) ); 
Switch_NMOS_n12_X3_Y1 mn6 ( .D(6), .G(5), .S(4), .Bg(vss) ); 
DCL_NMOS_n12_X3_Y1 mn7 ( .D(6), .S(4), .Bg(vss) ); 
Switch_NMOS_n12_X3_Y1 mn8 ( .D(8), .G(7), .S(vss), .Bg(vss) ); 
Switch_NMOS_n12_X3_Y1 mn9 ( .D(7), .G(6), .S(8), .Bg(vss) ); 
DCL_PMOS_n12_X2_Y1 mp1 ( .D(2), .S(vcc), .Bg(vcc) ); 
Switch_PMOS_n12_X2_Y1 mp2 ( .D(5), .G(2), .S(vcc), .Bg(vcc) ); 
DCL_PMOS_n12_X2_Y1 mp3 ( .D(3), .S(vcc), .Bg(vcc) ); 
Switch_PMOS_n12_X2_Y1 mp4 ( .D(6), .G(3), .S(vcc), .Bg(vcc) ); 
DCL_PMOS_n12_X2_Y1 mp5 ( .D(7), .S(vcc), .Bg(vcc) ); 
Switch_PMOS_n12_X2_Y1 mp6 ( .D(9), .G(7), .S(vcc), .Bg(vcc) ); 
Switch_PMOS_n12_X2_Y1 mp7 ( .D(vout), .G(9), .S(vcc), .Bg(vcc) ); 

endmodule
