//Verilog block level netlist file for cascode_current_mirror_ota
//Generated by UMN for ALIGN project 


module cascode_current_mirror_ota ( id, vbiasn, vbiasnd, vbiasp, vinn, vinp, voutp ); 
input id, vbiasn, vbiasnd, vbiasp, vinn, vinp, voutp;

Switch_NMOS_B_nfin24_n12_X2_Y1_RVT m25 ( .B(vss), .D(voutp), .G(vbiasn), .S(net034) ); 
DCL_NMOS_nfin5_n12_X1_Y1_RVT m1ndown ( .D(net9b), .S(vss) ); 
DCL_PMOS_nfin5_n12_X1_Y1_RVT m1pup ( .D(net8b), .S(vdd) ); 
Switch_PMOS_B_nfin120_n12_X5_Y2_RVT m23 ( .B(vdd), .D(voutp), .G(vbiasp), .S(net024) ); 
Switch_PMOS_nfin5_n12_X1_Y1_RVT m21 ( .D(net015), .G(net16), .S(vdd) ); 
Switch_PMOS_nfin10_n12_X1_Y1_RVT m20 ( .D(net06), .G(net16), .S(vdd) ); 
Switch_PMOS_nfin5_n12_X1_Y1_RVT m19 ( .D(net021), .G(net27), .S(vdd) ); 
Switch_PMOS_nfin10_n12_X1_Y1_RVT m18 ( .D(net024), .G(net27), .S(vdd) ); 
SCM_NMOS_nfin15_n12_X2_Y1_RVT m14_m16 ( .DA(id), .DB(net24), .S(vss) ); 
LS_S_NMOS_B_nfin24_n12_X2_Y1_RVT m1nup_m24 ( .DA(vbiasn), .DB(vbiasnd), .SA(net9b), .SB(net033) ); 
LS_S_PMOS_B_nfin120_n12_X10_Y1_RVT m1pdown_m22 ( .DA(vbiasp), .DB(vbiasnd), .SA(net8b), .SB(net06) ); 
CMC_S_PMOS_B_nfin60_n12_X5_Y1_RVT m27_m26 ( .B(vdd), .DA(net27), .DB(net16), .G(vbiasp), .SA(net021), .SB(net015) ); 
CMC_NMOS_nfin30_n12_X3_Y1_RVT m11_m10 ( .DA(net033), .DB(net034), .G(vbiasnd), .S(vss) ); 
DP_NMOS_B_nfin30_n12_X3_Y1_RVT m17_m15 ( .B(vss), .DA(net16), .DB(net27), .GA(vinn), .GB(vinp), .S(net24) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd;
endmodule
`endcelldefine
