//Verilog block level netlist file for powertrain_thermo
//Generated by UMN for ALIGN project 


module powertrain_thermo ( on_d[0], on_d[10], on_d[11], on_d[12], on_d[13], on_d[14], on_d[15], on_d[16], on_d[17], on_d[18], on_d[19], on_d[1], on_d[20], on_d[21], on_d[22], on_d[23], on_d[24], on_d[25], on_d[26], on_d[27], on_d[28], on_d[29], on_d[2], on_d[30], on_d[31], on_d[32], on_d[33], on_d[34], on_d[35], on_d[36], on_d[37], on_d[38], on_d[39], on_d[3], on_d[40], on_d[41], on_d[42], on_d[43], on_d[44], on_d[45], on_d[46], on_d[47], on_d[48], on_d[49], on_d[4], on_d[50], on_d[51], on_d[52], on_d[53], on_d[54], on_d[55], on_d[56], on_d[57], on_d[58], on_d[59], on_d[5], on_d[60], on_d[61], on_d[62], on_d[63], on_d[6], on_d[7], on_d[8], on_d[9], vout ); 
input on_d[0], on_d[10], on_d[11], on_d[12], on_d[13], on_d[14], on_d[15], on_d[16], on_d[17], on_d[18], on_d[19], on_d[1], on_d[20], on_d[21], on_d[22], on_d[23], on_d[24], on_d[25], on_d[26], on_d[27], on_d[28], on_d[29], on_d[2], on_d[30], on_d[31], on_d[32], on_d[33], on_d[34], on_d[35], on_d[36], on_d[37], on_d[38], on_d[39], on_d[3], on_d[40], on_d[41], on_d[42], on_d[43], on_d[44], on_d[45], on_d[46], on_d[47], on_d[48], on_d[49], on_d[4], on_d[50], on_d[51], on_d[52], on_d[53], on_d[54], on_d[55], on_d[56], on_d[57], on_d[58], on_d[59], on_d[5], on_d[60], on_d[61], on_d[62], on_d[63], on_d[6], on_d[7], on_d[8], on_d[9], vout;

Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[63] ( .D(vout), .G(on_d[63]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[62] ( .D(vout), .G(on_d[62]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[61] ( .D(vout), .G(on_d[61]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[60] ( .D(vout), .G(on_d[60]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[59] ( .D(vout), .G(on_d[59]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[58] ( .D(vout), .G(on_d[58]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[57] ( .D(vout), .G(on_d[57]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[56] ( .D(vout), .G(on_d[56]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[55] ( .D(vout), .G(on_d[55]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[54] ( .D(vout), .G(on_d[54]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[53] ( .D(vout), .G(on_d[53]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[52] ( .D(vout), .G(on_d[52]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[51] ( .D(vout), .G(on_d[51]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[50] ( .D(vout), .G(on_d[50]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[49] ( .D(vout), .G(on_d[49]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[48] ( .D(vout), .G(on_d[48]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[47] ( .D(vout), .G(on_d[47]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[46] ( .D(vout), .G(on_d[46]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[45] ( .D(vout), .G(on_d[45]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[44] ( .D(vout), .G(on_d[44]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[43] ( .D(vout), .G(on_d[43]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[42] ( .D(vout), .G(on_d[42]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[41] ( .D(vout), .G(on_d[41]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[40] ( .D(vout), .G(on_d[40]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[39] ( .D(vout), .G(on_d[39]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[38] ( .D(vout), .G(on_d[38]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[37] ( .D(vout), .G(on_d[37]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[36] ( .D(vout), .G(on_d[36]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[35] ( .D(vout), .G(on_d[35]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[34] ( .D(vout), .G(on_d[34]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[33] ( .D(vout), .G(on_d[33]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[32] ( .D(vout), .G(on_d[32]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[31] ( .D(vout), .G(on_d[31]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[30] ( .D(vout), .G(on_d[30]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[29] ( .D(vout), .G(on_d[29]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[28] ( .D(vout), .G(on_d[28]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[27] ( .D(vout), .G(on_d[27]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[26] ( .D(vout), .G(on_d[26]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[25] ( .D(vout), .G(on_d[25]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[24] ( .D(vout), .G(on_d[24]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[23] ( .D(vout), .G(on_d[23]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[22] ( .D(vout), .G(on_d[22]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[21] ( .D(vout), .G(on_d[21]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[20] ( .D(vout), .G(on_d[20]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[19] ( .D(vout), .G(on_d[19]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[18] ( .D(vout), .G(on_d[18]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[17] ( .D(vout), .G(on_d[17]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[16] ( .D(vout), .G(on_d[16]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[15] ( .D(vout), .G(on_d[15]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[14] ( .D(vout), .G(on_d[14]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[13] ( .D(vout), .G(on_d[13]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[12] ( .D(vout), .G(on_d[12]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[11] ( .D(vout), .G(on_d[11]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[10] ( .D(vout), .G(on_d[10]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[9] ( .D(vout), .G(on_d[9]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[8] ( .D(vout), .G(on_d[8]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[7] ( .D(vout), .G(on_d[7]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[6] ( .D(vout), .G(on_d[6]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[5] ( .D(vout), .G(on_d[5]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[4] ( .D(vout), .G(on_d[4]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[3] ( .D(vout), .G(on_d[3]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[2] ( .D(vout), .G(on_d[2]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[1] ( .D(vout), .G(on_d[1]), .S(vcc) ); 
Switch_PMOS_nfin4_nf8_m4_n12_X11_Y1 xu_pmos_title[0] ( .D(vout), .G(on_d[0]), .S(vcc) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vcc;
endmodule
`endcelldefine
