//Verilog block level netlist file for ldo_error_amp_v2
//Generated by UMN for ALIGN project 


module ldo_error_amp_v2 ( vbias, vin, vip, vout ); 
input vbias, vin, vip, vout;

DCL_PMOS_nfin6_m8_n12_X2_Y2_ST2_LVT Xi27 ( .D(n2), .S(vcc) ); 
DCL_PMOS_nfin6_m8_n12_X2_Y2_ST2_LVT Xi26 ( .D(n1), .S(vcc) ); 
Switch_PMOS_nfin6_m16_n12_X4_Y2_ST2_LVT Xi33 ( .D(vout), .G(n1), .S(vcc) ); 
Switch_PMOS_nfin6_m16_n12_X4_Y2_ST2_LVT Xi41 ( .D(n4), .G(n2), .S(vcc) ); 
Switch_NMOS_nfin6_m16_n12_X4_Y2_ST2_LVT Xi30 ( .D(vcom), .G(vbias), .S(vssx) );
SCM_NMOS_nfin6_m16_n12_X4_Y2_ST2_LVT Xi43_Xi34 ( .DA(n4), .DB(vout), .S(vssx) ); 
DP_NMOS_B_nfin6_m16_n12_X8_Y1_ST2_LVT Xi29_Xi28 ( .B(vssx), .DA(n1), .DB(n2), .GA(vip), .GB(vin), .S(vcom) ); 

endmodule


`celldefine
module global_power;
supply0 vssx;
supply1 vcc;
endmodule
`endcelldefine
