//Verilog block level netlist file for Sanitized_CK_Divider8
//Generated by UMN for ALIGN project 


module Sanitized_CK_Divider8 ( CKIN, COMPEN, INPHASE, OUTPHASE, PRESET, QPHASE, VDD, VSS ); 
input CKIN, COMPEN, INPHASE, OUTPHASE, PRESET, QPHASE, VDD, VSS;

INVD2LVT XI14 ( .I(PRESET), .VDD(VDD), .VSS(VSS), .ZN(net039) ); 
DCAP8LVT XI51<18> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<17> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<16> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<15> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<14> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<13> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<12> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<11> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<10> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<9> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<8> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<7> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<6> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<5> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<4> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<3> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<2> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<1> ( .VDD(VDD), .VSS(VSS) ); 
DCAP8LVT XI51<0> ( .VDD(VDD), .VSS(VSS) ); 
INVD1LVT XI50 ( .I(PRESET), .VDD(VDD), .VSS(VSS), .ZN(net048) ); 
CKBD1LVT XI6 ( .I(CKIN), .VDD(VDD), .VSS(VSS), .Z(net45) ); 
AN2D1LVT XI139 ( .A1(net048), .A2(net015), .VDD(VDD), .VSS(VSS), .Z(COMPEN) ); 
CKND1LVT XI5 ( .I(net45), .VDD(VDD), .VSS(VSS), .ZN(net49) ); 
DFCND1LVT XI8 ( .CDN(net039), .CP(net011), .D(net48), .Q(net015), .QN(net48), .VDD(VDD), .VSS(VSS) ); 
DFCND1LVT XI7 ( .CDN(net039), .CP(net018), .D(net50), .Q(net076), .QN(net50), .VDD(VDD), .VSS(VSS) ); 
CKND3LVT XI43 ( .I(net076), .VDD(VDD), .VSS(VSS), .ZN(net059) ); 
CKND3LVT XI39 ( .I(net48), .VDD(VDD), .VSS(VSS), .ZN(net063) ); 
CKND3LVT XI37 ( .I(net015), .VDD(VDD), .VSS(VSS), .ZN(net064) ); 
CKND8LVT XI42 ( .I(net059), .VDD(VDD), .VSS(VSS), .ZN(QPHASE) ); 
CKND8LVT XI38 ( .I(net063), .VDD(VDD), .VSS(VSS), .ZN(OUTPHASE) ); 
CKND8LVT XI20 ( .I(net064), .VDD(VDD), .VSS(VSS), .ZN(INPHASE) ); 
DFCND1LVT_schematic XI29 ( .CDN(net039), .CP(net49), .D(net016), .QN(net016), .VDD(VDD), .VSS(VSS) ); 
DFCND1LVT_schematic XI28 ( .CDN(net039), .CP(net016), .D(net018), .QN(net018), .VDD(VDD), .VSS(VSS) ); 
DFCND1LVT_schematic XI27 ( .CDN(net039), .CP(net45), .D(net040), .QN(net040), .VDD(VDD), .VSS(VSS) ); 
DFCND1LVT_schematic XI26 ( .CDN(net039), .CP(net040), .D(net011), .QN(net011), .VDD(VDD), .VSS(VSS) ); 

endmodule

module INVD2LVT ( I, VDD, VSS, ZN ); 
input I, VDD, VSS, ZN;

Switch_NMOS_n12_X1_Y1 MMU1_0_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU1_0_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 

endmodule

module DCAP8LVT ( VDD, VSS ); 
input VDD, VSS;

Dcap_NMOS_n12_X1_Y1 MMI4 ( .B(VSS), .S(VSS), .G(net9) ); 
Switch_NMOS_n12_X1_Y1 MM_u2 ( .B(VSS), .D(net11), .G(net9), .S(VSS) ); 
Dcap_PMOS_n12_X1_Y1 MMI3 ( .B(VDD), .S(VDD), .G(net11) ); 
Switch_PMOS_n12_X1_Y1 MM_u1 ( .B(VDD), .D(net9), .G(net11), .S(VDD) ); 

endmodule

module INVD1LVT ( I, VDD, VSS, ZN ); 
input I, VDD, VSS, ZN;

Switch_NMOS_n12_X1_Y1 MMU1_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU1_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 

endmodule

module INV_LVT ( SN, SP, i, zn ); 
input SN, SP, i, zn;

Switch_NMOS_n12_X1_Y1 xm0 ( .B(SN), .D(zn), .G(i), .S(SN) ); 
Switch_PMOS_n12_X1_Y1 xm1 ( .B(SP), .D(zn), .G(i), .S(SP) ); 

endmodule

module stage2_inv ( G1, G2, SN, SP ); 
input G1, G2, SN, SP;

INV_LVT MM0_MM2 ( .zn(G1), .i(D), .SN(SN), .SP(SP) ); 
INV_LVT MM1_MM3 ( .zn(D), .i(G2), .SN(SN), .SP(SP) ); 

endmodule

module CKBD1LVT ( I, VDD, VSS, Z ); 
input I, VDD, VSS, Z;

stage2_inv MMU23_MM_u15_MMU21_MM_u3 ( .G1(Z), .SN(VSS), .G2(I), .SP(VDD) ); 

endmodule

module AN2D1LVT ( A1, A2, VDD, VSS, Z ); 
input A1, A2, VDD, VSS, Z;

Switch_PMOS_n12_X1_Y1 MM_u3_M_u3 ( .B(VDD), .D(Z), .G(net5), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u1 ( .B(VDD), .D(net5), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u2_M_u2 ( .B(VDD), .D(net5), .G(A2), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MM_u3_M_u2 ( .B(VSS), .D(Z), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u4 ( .B(VSS), .D(net17), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_M_u3 ( .B(VSS), .D(net5), .G(A1), .S(net17) ); 

endmodule

module CKND1LVT ( I, VDD, VSS, ZN ); 
input I, VDD, VSS, ZN;

Switch_NMOS_n12_X1_Y1 MM_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MM_u1 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 

endmodule

module tgate ( D, GA, GB, S ); 
input D, GA, GB, S;

Switch_NMOS_n12_X1_Y1 M0 ( .B(BN), .D(D), .G(GA), .S(S) ); 
Switch_PMOS_n12_X1_Y1 M1 ( .B(BP), .D(D), .G(GB), .S(S) ); 

endmodule

module DFCND1LVT ( CDN, CP, D, Q, QN, VDD, VSS ); 
input CDN, CP, D, Q, QN, VDD, VSS;

Switch_NMOS_n12_X1_Y1 MMI4 ( .B(VSS), .D(net53), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI21_M_u3 ( .B(VSS), .D(net95), .G(net79), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MMI13_M_u2 ( .B(VSS), .D(net81), .G(net25), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI5 ( .B(VSS), .D(net25), .G(D), .S(net53) ); 
Switch_NMOS_n12_X1_Y1 MMI49 ( .B(VSS), .D(net20), .G(CDN), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI48 ( .B(VSS), .D(net17), .G(net81), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMI27_M_u2 ( .B(VSS), .D(Q), .G(net95), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI21_M_u4 ( .B(VSS), .D(net9), .G(CDN), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI47 ( .B(VSS), .D(net25), .G(net67), .S(net17) ); 
Switch_PMOS_n12_X1_Y1 MMI43 ( .B(VDD), .D(net72), .G(net81), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI6 ( .B(VDD), .D(net25), .G(D), .S(net104) ); 
Switch_PMOS_n12_X1_Y1 MMI27_M_u3 ( .B(VDD), .D(Q), .G(net95), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI44 ( .B(VDD), .D(net72), .G(CDN), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI13_M_u3 ( .B(VDD), .D(net81), .G(net25), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI21_M_u1 ( .B(VDD), .D(net95), .G(net79), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI45 ( .B(VDD), .D(net25), .G(net5), .S(net72) ); 
Switch_PMOS_n12_X1_Y1 MMI7 ( .B(VDD), .D(net104), .G(net67), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI21_M_u2 ( .B(VDD), .D(net95), .G(CDN), .S(VDD) ); 
stage2_inv MMI32_M_u2_MMI22_M_u2_MMI32_M_u3_MMI22_M_u3 ( .G1(net67), .SN(VSS), .G2(CP), .SP(VDD) ); 
stage2_inv MMI29_M_u2_MMI14_M_u2_MMI29_M_u3_MMI14_M_u3 ( .G1(QN), .SN(VSS), .G2(net95), .SP(VDD) ); 
tgate MMI15_MMI16 ( .D(net81), .GA(net67), .S(net79), .GB(net5) ); 
tgate MMI18_MMI17 ( .D(net33), .GA(net5), .S(net79), .GB(net67) ); 

endmodule

module CKND3LVT ( I, VDD, VSS, ZN ); 
input I, VDD, VSS, ZN;

Switch_PMOS_n12_X1_Y1 MM_u1_0 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM_u1_1 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_1 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 

endmodule

module CKND8LVT ( I, VDD, VSS, ZN ); 
input I, VDD, VSS, ZN;

Switch_PMOS_n12_X1_Y1 MM_u1_1 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 
Switch_NMOS_n12_X1_Y1 MM_u2_2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 

endmodule

module DFCND1LVT_schematic ( CDN, CP, D, QN, VDD, VSS ); 
input CDN, CP, D, QN, VDD, VSS;

Switch_NMOS_n12_X1_Y1 MMI4 ( .B(VSS), .D(net53), .G(net5), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI21_M_u3 ( .B(VSS), .D(net95), .G(net79), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MMI13_M_u2 ( .B(VSS), .D(net81), .G(net25), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI5 ( .B(VSS), .D(net25), .G(D), .S(net53) ); 
Switch_NMOS_n12_X1_Y1 MMI49 ( .B(VSS), .D(net20), .G(CDN), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI48 ( .B(VSS), .D(net17), .G(net81), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMI27_M_u2 ( .B(VSS), .D(net036), .G(net95), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI21_M_u4 ( .B(VSS), .D(net9), .G(CDN), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI47 ( .B(VSS), .D(net25), .G(net67), .S(net17) ); 
Switch_PMOS_n12_X1_Y1 MMI43 ( .B(VDD), .D(net72), .G(net81), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI6 ( .B(VDD), .D(net25), .G(D), .S(net104) ); 
Switch_PMOS_n12_X1_Y1 MMI27_M_u3 ( .B(VDD), .D(net036), .G(net95), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI44 ( .B(VDD), .D(net72), .G(CDN), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI13_M_u3 ( .B(VDD), .D(net81), .G(net25), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI21_M_u1 ( .B(VDD), .D(net95), .G(net79), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI45 ( .B(VDD), .D(net25), .G(net5), .S(net72) ); 
Switch_PMOS_n12_X1_Y1 MMI7 ( .B(VDD), .D(net104), .G(net67), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMI21_M_u2 ( .B(VDD), .D(net95), .G(CDN), .S(VDD) ); 
stage2_inv MMI32_M_u2_MMI22_M_u2_MMI32_M_u3_MMI22_M_u3 ( .G1(net67), .SN(VSS), .G2(CP), .SP(VDD) ); 
stage2_inv MMI29_M_u2_MMI14_M_u2_MMI29_M_u3_MMI14_M_u3 ( .G1(QN), .SN(VSS), .G2(net95), .SP(VDD) ); 
tgate MMI15_MMI16 ( .D(net81), .GA(net67), .S(net79), .GB(net5) ); 
tgate MMI18_MMI17 ( .D(net33), .GA(net5), .S(net79), .GB(net67) ); 

endmodule

`celldefine
module global_power;
supply0 DVSS;
supply1 DVDD;
endmodule
`endcelldefine
