//Verilog block level netlist file for TEST
//Generated by UMN for ALIGN project 


module LSB_NMOS_2 ( B, DA, DB, DC, SA, SB, SC ); 
input B, DA, DB, DC, SA, SB, SC;

Switch_NMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(SC) ); 
LS_NMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .SA(SA), .DB(DB), .SB(SB) ); 

endmodule

module LSB_PMOS_2 ( B, DA, DB, DC, SA, SB, SC ); 
input B, DA, DB, DC, SA, SB, SC;

Switch_PMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(SC) ); 
LS_PMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .SA(SA), .DB(DB), .SB(SB) ); 

endmodule

module TEST ( ibias, vref, vrefp ); 
input ibias, vref, vrefp;

Dummy1_NMOS_n12_X1_Y1 xm72 ( .B(gnd), .S(net0211) ); 
Dummy1_NMOS_n12_X1_Y1 xm71 ( .B(gnd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 xm70 ( .B(gnd), .S(net0176) ); 
Dummy1_NMOS_n12_X1_Y1 xm69 ( .B(gnd), .S(net0211) ); 
Dummy1_NMOS_n12_X1_Y1 xm54 ( .B(gnd), .S(net0144) ); 
Dummy1_NMOS_n12_X1_Y1 xm51 ( .B(gnd), .S(net0111) ); 
Dummy1_NMOS_n12_X1_Y1 xm48 ( .B(gnd), .S(net0129) ); 
Dummy1_NMOS_n12_X1_Y1 xm43 ( .B(gnd), .S(net0109) ); 
Dummy1_NMOS_n12_X1_Y1 xm68 ( .B(gnd), .S(net0160) ); 
Dummy1_NMOS_n12_X1_Y1 xm62 ( .B(gnd), .S(net0147) ); 
Dummy1_NMOS_n12_X1_Y1 xm65 ( .B(gnd), .S(net0149) ); 
Dummy1_NMOS_n12_X1_Y1 xm58 ( .B(gnd), .S(net0103) ); 
Dummy1_NMOS_n12_X1_Y1 xm55 ( .B(gnd), .S(net0103) ); 
Dummy1_NMOS_n12_X1_Y1 xm57 ( .B(gnd), .S(net0111) ); 
Dummy1_NMOS_n12_X1_Y1 xm59 ( .B(gnd), .S(net0144) ); 
Dummy1_NMOS_n12_X1_Y1 xm61 ( .B(gnd), .S(net0149) ); 
Switch_NMOS_n12_X1_Y1 xm24 ( .B(gnd), .D(net0148), .G(vdd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm67 ( .B(gnd), .D(net0211), .G(vdd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm21 ( .B(gnd), .D(net0160), .G(ibias), .S(net0211) ); 
Dummy1_NMOS_n12_X1_Y1 xm64 ( .B(gnd), .S(net0147) ); 
Switch_NMOS_n12_X1_Y1 xm30 ( .B(gnd), .D(net0176), .G(ibias), .S(net0207) ); 
Dummy1_NMOS_n12_X1_Y1 xm14 ( .B(gnd), .S(net0140) ); 
Switch_NMOS_n12_X1_Y1 xm6 ( .B(gnd), .D(net017), .G(vdd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm3 ( .B(gnd), .D(net016), .G(vdd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 xm9 ( .B(gnd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 xm10 ( .B(gnd), .S(net016) ); 
Dummy1_NMOS_n12_X1_Y1 xm11 ( .B(gnd), .S(ibias) ); 
Switch_NMOS_n12_X1_Y1 xm66 ( .B(gnd), .D(net0207), .G(vdd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 xm13 ( .B(gnd), .S(net016) ); 
Dummy1_NMOS_n12_X1_Y1 xm12 ( .B(gnd), .S(net017) ); 
Dcap_PMOS_n12_X1_Y1 xm35 ( .B(vdd), .S(vdd), .G(net0144) ); 
Dummy1_PMOS_n12_X1_Y1 xm2 ( .B(vdd), .S(vfb) ); 
Dummy1_PMOS_n12_X1_Y1 xm4 ( .B(vdd), .S(net0168) ); 
Dummy1_PMOS_n12_X1_Y1 xm5 ( .B(vdd), .S(vrefp) ); 
Dummy1_PMOS_n12_X1_Y1 xm31 ( .B(vdd), .S(net0160) ); 
Switch_PMOS_n12_X1_Y1 xm28 ( .B(vdd), .D(vrefp), .G(net0176), .S(net0168) ); 
Dummy1_PMOS_n12_X1_Y1 xm26 ( .B(vdd), .S(vfb) ); 
Dummy1_PMOS_n12_X1_Y1 xm0 ( .B(vdd), .S(net0156) ); 
Dcap_PMOS_n12_X1_Y1 xm34 ( .B(vdd), .S(vdd), .G(net0160) ); 
Switch_PMOS_n12_X1_Y1 xm15 ( .B(vdd), .D(vfb), .G(net0144), .S(net0156) ); 
Dummy1_PMOS_n12_X1_Y1 xm79 ( .B(vdd), .S(net0122) ); 
Dummy1_PMOS_n12_X1_Y1 xm75 ( .B(vdd), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm49 ( .B(vdd), .D(net093), .G(gnd), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 xm85 ( .B(vdd), .S(net0133) ); 
Dummy1_PMOS_n12_X1_Y1 xm84 ( .B(vdd), .S(net0102) ); 
Dummy1_PMOS_n12_X1_Y1 xm83 ( .B(vdd), .S(net0134) ); 
Dummy1_PMOS_n12_X1_Y1 xm82 ( .B(vdd), .S(net0101) ); 
Dummy1_PMOS_n12_X1_Y1 xm81 ( .B(vdd), .S(net0129) ); 
Dummy1_PMOS_n12_X1_Y1 xm80 ( .B(vdd), .S(net0109) ); 
Dummy1_PMOS_n12_X1_Y1 xm73 ( .B(vdd), .S(net0140) ); 
Dummy1_PMOS_n12_X1_Y1 xm77 ( .B(vdd), .S(net0118) ); 
Dummy1_PMOS_n12_X1_Y1 xm78 ( .B(vdd), .S(net0118) ); 
Dummy1_PMOS_n12_X1_Y1 xm74 ( .B(vdd), .S(net093) ); 
Dummy1_PMOS_n12_X1_Y1 xm89 ( .B(vdd), .S(net0156) ); 
Dummy1_PMOS_n12_X1_Y1 xm88 ( .B(vdd), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm86 ( .B(vdd), .D(net0168), .G(gnd), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm87 ( .B(vdd), .D(net0156), .G(gnd), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 xm76 ( .B(vdd), .S(net0122) ); 
CMC_NMOS_S_n12_X1_Y1 xm23_xm25 ( .B(gnd), .DA(net0149), .G(vdd), .S(gnd), .DB(net0147) ); 
CMC_PMOS_S_n12_X1_Y1 xm60_xm52 ( .B(vdd), .DA(net0134), .G(gnd), .S(vdd), .DB(net0101) ); 
CMC_PMOS_S_n12_X1_Y1 xm53_xm56 ( .B(vdd), .DA(net0122), .G(gnd), .S(vdd), .DB(net0118) ); 
LSB_NMOS_2 xm7_xm8_xm20 ( .B(gnd), .DA(ibias), .SA(net017), .DB(net0140), .SB(net016), .DC(net0111), .SC(net0148) ); 
LSB_PMOS_2 xm45_xm47_xm46 ( .B(vdd), .DA(net0140), .SA(net093), .DB(net0144), .SB(net0133), .DC(net0103), .SC(net0102) ); 
LS_NMOS_n12_X1_Y1 xm1_xm22 ( .B(gnd), .DA(net0103), .SA(net0149), .DB(net0144), .SB(net0147) ); 
LS_PMOS_n12_X1_Y1 xm41_xm40 ( .B(vdd), .DA(net0109), .SA(net0118), .DB(net0102), .SB(net0101) ); 
LS_PMOS_n12_X1_Y1 xm44_xm42 ( .B(vdd), .DA(net0129), .SA(net0122), .DB(net0133), .SB(net0134) ); 
LS_PMOS_n12_X1_Y1 xm27_xm29 ( .B(vdd), .DA(net0160), .SA(vfb), .DB(net0176), .SB(vrefp) ); 
DP_NMOS_n12_X1_Y1 xm16_xm18 ( .B(gnd), .DA(net0144), .GA(vref), .S(net0111), .DB(net0103), .GB(vfb) ); 
DP_NMOS_n12_X1_Y1 xm19_xm17 ( .B(gnd), .DA(net0129), .GA(vfb), .S(net0111), .DB(net0109), .GB(vref) ); 

endmodule

`celldefine
module global_power;
supply0 gnd;
supply1 vdd;
endmodule
`endcelldefine
