//Verilog block level netlist file for BUFFER_VREFP
//Generated by UMN for ALIGN project 


module CMB_NMOS_2 ( B, DA, DB, DC, S ); 
input B, DA, DB, DC, S;

Switch_NMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 
SCM_NMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .S(S), .DB(DB) ); 

endmodule

module CMB_NMOS_3 ( B, DA, DB, DC, DD, S ); 
input B, DA, DB, DC, DD, S;

Switch_NMOS_n12_X1_Y1 M3 ( .B(B), .D(DD), .G(DA), .S(S) ); 
CMB_NMOS_2 M0_M2_M1 ( .B(B), .DA(DA), .S(S), .DB(DC), .DC(DB) ); 

endmodule

module CMB_NMOS_4 ( B, DA, DB, DC, DD, DE, S ); 
input B, DA, DB, DC, DD, DE, S;

Switch_NMOS_n12_X1_Y1 M4 ( .B(B), .D(DE), .G(DA), .S(S) ); 
CMB_NMOS_3 M0_M3_M2_M1 ( .B(B), .DA(DA), .S(S), .DB(DD), .DC(DC), .DD(DB) ); 

endmodule

module LSB_PMOS_2 ( B, DA, DB, DC, SA, SB, SC ); 
input B, DA, DB, DC, SA, SB, SC;

Switch_PMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(SC) ); 
LS_PMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .SA(SA), .DB(DB), .SB(SB) ); 

endmodule

module dummy_hier_xm11_xm8 ( net051, net054, net211, net215 ); 
input net051, net054, net211, net215;

SCM_PMOS_n12_X1_Y1 xm25_xm26 ( .B(vdd), .DA(net211), .S(vdd), .DB(net054) ); 
Dummy1_PMOS_n12_X1_Y1 xm35 ( .B(vdd), .S(net211) ); 
Dummy1_NMOS_n12_X1_Y1 xm43 ( .B(gnd), .S(net211) ); 
Dummy1_PMOS_n12_X1_Y1 xm36 ( .B(vdd), .S(net215) ); 
Dummy1_NMOS_n12_X1_Y1 xm44 ( .B(gnd), .S(net215) ); 
SCM_PMOS_n12_X1_Y1 xm23_xm24 ( .B(vdd), .DA(net215), .S(vdd), .DB(net051) ); 

endmodule

module dummy_hier_xm12_xm10 ( net036, net051, net054, net204, net207, net211, net215 ); 
input net036, net051, net054, net204, net207, net211, net215;

LSB_PMOS_2 xm22_xm14_xm13 ( .B(vdd), .DA(net204), .SA(vdd), .DB(net207), .SB(net054), .DC(net036), .SC(net051) ); 
dummy_hier_xm11_xm8 xm25_xm26_xm35_xm43_xm36_xm44_xm23_xm24 ( .net211(net211), .net054(net054), .net215(net215), .net051(net051) ); 
Dummy1_PMOS_n12_X1_Y1 xm42 ( .B(vdd), .S(net051) ); 
Dummy1_NMOS_n12_X1_Y1 xm45 ( .B(gnd), .S(net051) ); 
Dummy1_NMOS_n12_X1_Y1 xm46 ( .B(gnd), .S(net054) ); 
Dummy1_PMOS_n12_X1_Y1 xm41 ( .B(vdd), .S(net054) ); 

endmodule

module BUFFER_VREFP ( ibias, vref, vrefp ); 
input ibias, vref, vrefp;

Dummy1_PMOS_n12_X1_Y1 xm60 ( .B(vdd), .S(vrefp) ); 
Dcap_PMOS_n12_X1_Y1 xm37 ( .B(vdd), .S(vdd), .G(net057) ); 
Switch_PMOS_n12_X1_Y1 xm28 ( .B(vdd), .D(vrefp), .G(net052), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm15 ( .B(vdd), .D(net049), .G(net036), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 xm59 ( .B(vdd), .S(net057) ); 
Dummy1_PMOS_n12_X1_Y1 xm57 ( .B(vdd), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 xm58 ( .B(vdd), .S(net049) ); 
Dummy1_PMOS_n12_X1_Y1 xm55 ( .B(vdd), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 xm54 ( .B(vdd), .S(net049) ); 
Dcap_PMOS_n12_X1_Y1 xm38 ( .B(vdd), .S(vdd), .G(net036) ); 
Dummy1_NMOS_n12_X1_Y1 xm63 ( .B(gnd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 xm62 ( .B(gnd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 xm56 ( .B(gnd), .S(net057) ); 
Dummy1_NMOS_n12_X1_Y1 xm53 ( .B(gnd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 xm52 ( .B(gnd), .S(net036) ); 
Dummy1_NMOS_n12_X1_Y1 xm47 ( .B(gnd), .S(net212) ); 
Dummy1_NMOS_n12_X1_Y1 xm50 ( .B(gnd), .S(net207) ); 
Dummy1_NMOS_n12_X1_Y1 xm40 ( .B(gnd), .S(net204) ); 
Dummy1_NMOS_n12_X1_Y1 xm39 ( .B(gnd), .S(ibias) ); 
Dummy1_PMOS_n12_X1_Y1 xm33 ( .B(vdd), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 xm32 ( .B(vdd), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 xm31 ( .B(vdd), .S(net204) ); 
CMB_NMOS_4 xm4_xm3_xm5_xm21_xm30 ( .B(gnd), .DA(ibias), .S(gnd), .DB(net212), .DC(net204), .DD(net057), .DE(net052) ); 
SCM_NMOS_n12_X1_Y1 xm1_xm6 ( .B(gnd), .DA(net207), .S(gnd), .DB(net036) ); 
LS_PMOS_n12_X1_Y1 xm27_xm29 ( .B(vdd), .DA(net057), .SA(net049), .DB(net052), .SB(vrefp) ); 
DP_NMOS_n12_X1_Y1 xm12_xm10 ( .B(gnd), .DA(net051), .GA(vref), .S(net212), .DB(net054), .GB(net049) ); 
DP_NMOS_n12_X1_Y1 xm11_xm8 ( .B(gnd), .DA(net211), .GA(vref), .S(net212), .DB(net215), .GB(net049) ); 
dummy_hier_xm12_xm10 xm22_xm14_xm13_xm25_xm26_xm35_xm43_xm36_xm44_xm23_xm24_xm42_xm45_xm46_xm41 ( .net204(net204), .net036(net036), .net207(net207), .net051(net051), .net054(net054), .net211(net211), .net215(net215) ); 

endmodule

`celldefine
module global_power;
supply0 gnd;
supply1 vdd;
endmodule
`endcelldefine
