//Verilog block level netlist file for current_mirror_ota
//Generated by UMN for ALIGN project 


module current_mirror_ota ( id, vinp, vinn, vdd, vbiasnd, vss, voutp ); 
input id, vinp, vinn, vdd, vbiasnd, vss, voutp;

Switch_PMOS_n12_X5_Y4 m18s ( .D(voutp), .G(net27), .S(vdd) ); 
DCL_PMOS_n12_X5_Y1 m19 ( .D(net27), .S(vdd) ); 
Switch_PMOS_n12_X5_Y4 m20s ( .D(vbiasnd), .G(net16), .S(vdd) ); 
DCL_PMOS_n12_X5_Y1 m21 ( .D(net16), .S(vdd) ); 
SCM_NMOS_n12_X1_Y1 m14_m16 ( .DA(id), .DB(net24), .S(vss) ); 
SCM_NMOS_n12_X2_Y1 m11_m10 ( .DA(vbiasnd), .DB(voutp), .S(vss) ); 
DP_NMOS_n12_X3_Y1 m17_m15 ( .DA(net16), .GA(vinn), .S(net24), .DB(net27), .GB(vinp) ); 

endmodule
