//Verilog block level netlist file for BUFFER_VREFP_ud
//Generated by UMN for ALIGN project 


module CMB_NMOS_2 ( B, DA, DB, DC, S ); 
input B, DA, DB, DC, S;

Switch_NMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 
SCM_NMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .S(S), .DB(DB) ); 

endmodule

module LSB_PMOS_2 ( B, DA, DB, DC, SA, SB, SC ); 
input B, DA, DB, DC, SA, SB, SC;

Switch_PMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(SC) ); 
LS_PMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .SA(SA), .DB(DB), .SB(SB) ); 

endmodule

module BUFFER_VREFP_ud ( ibias1, ibias2, vref, vrefp ); 
input ibias1, ibias2, vref, vrefp;

Dummy1_PMOS_n12_X1_Y1 m60 ( .B(vdd), .S(vrefp) ); 
Dcap_PMOS_n12_X1_Y1 m37 ( .B(vdd), .S(vdd), .G(net057) ); 
Switch_PMOS_n12_X1_Y1 m28 ( .B(vdd), .D(vrefp), .G(net052), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 m15 ( .B(vdd), .D(net050), .G(net036), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 m59 ( .B(vdd), .S(net057) ); 
Dummy1_PMOS_n12_X1_Y1 m57 ( .B(vdd), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 m58 ( .B(vdd), .S(net050) ); 
Dummy1_PMOS_n12_X1_Y1 m55 ( .B(vdd), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 m54 ( .B(vdd), .S(net050) ); 
Dcap_PMOS_n12_X1_Y1 m38 ( .B(vdd), .S(vdd), .G(net036) ); 
Dummy1_NMOS_n12_X1_Y1 m65 ( .B(gnd), .S(ibias2) ); 
Dummy1_NMOS_n12_X1_Y1 m63 ( .B(gnd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 m61 ( .B(gnd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 m56 ( .B(gnd), .S(net057) ); 
Dummy1_NMOS_n12_X1_Y1 m43 ( .B(gnd), .S(net211) ); 
Dummy1_NMOS_n12_X1_Y1 m53 ( .B(gnd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 m52 ( .B(gnd), .S(net036) ); 
Dummy1_NMOS_n12_X1_Y1 m47 ( .B(gnd), .S(net212) ); 
Dummy1_NMOS_n12_X1_Y1 m50 ( .B(gnd), .S(net207) ); 
Dummy1_NMOS_n12_X1_Y1 m45 ( .B(gnd), .S(net051) ); 
Dummy1_NMOS_n12_X1_Y1 m49 ( .B(gnd), .S(gnd) ); 
Dummy1_NMOS_n12_X1_Y1 m40 ( .B(gnd), .S(net204) ); 
Dummy1_NMOS_n12_X1_Y1 m46 ( .B(gnd), .S(net054) ); 
Dummy1_NMOS_n12_X1_Y1 m44 ( .B(gnd), .S(net215) ); 
Dummy1_NMOS_n12_X1_Y1 m39 ( .B(gnd), .S(ibias1) ); 
Dummy1_PMOS_n12_X1_Y1 m42 ( .B(vdd), .S(net051) ); 
Dummy1_PMOS_n12_X1_Y1 m35 ( .B(vdd), .S(net211) ); 
Dummy1_PMOS_n12_X1_Y1 m33 ( .B(vdd), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 m41 ( .B(vdd), .S(net054) ); 
Dummy1_PMOS_n12_X1_Y1 m32 ( .B(vdd), .S(vdd) ); 
Dummy1_PMOS_n12_X1_Y1 m36 ( .B(vdd), .S(net215) ); 
Dummy1_PMOS_n12_X1_Y1 m31 ( .B(vdd), .S(net204) ); 
CMB_NMOS_2 m4_m5_m3 ( .B(gnd), .DA(ibias1), .S(gnd), .DB(net204), .DC(net212) ); 
CMB_NMOS_2 m64_m30_m21 ( .B(gnd), .DA(ibias2), .S(gnd), .DB(net052), .DC(net057) ); 
SCM_NMOS_n12_X1_Y1 m1_m6 ( .B(gnd), .DA(net207), .S(gnd), .DB(net036) ); 
SCM_PMOS_n12_X1_Y1 m23_m24 ( .B(vdd), .DA(net215), .S(vdd), .DB(net051) ); 
SCM_PMOS_n12_X1_Y1 m25_m26 ( .B(vdd), .DA(net211), .S(vdd), .DB(net054) ); 
LSB_PMOS_2 m22_m14_m13 ( .B(vdd), .DA(net204), .SA(vdd), .DB(net207), .SB(net054), .DC(net036), .SC(net051) ); 
LS_PMOS_n12_X1_Y1 m27_m29 ( .B(vdd), .DA(net057), .SA(net050), .DB(net052), .SB(vrefp) ); 
DP_NMOS_n12_X1_Y1 m12_m10 ( .B(gnd), .DA(net051), .GA(vref), .S(net212), .DB(net054), .GB(net050) ); 
DP_NMOS_n12_X1_Y1 m8_m11 ( .B(gnd), .DA(net215), .GA(net050), .S(net212), .DB(net211), .GB(vref) ); 

endmodule

`celldefine
module global_power;
supply0 gnd;
supply1 vdd;
endmodule
`endcelldefine
