//Verilog block level netlist file for BUFFER_VCM
//Generated by UMN for ALIGN project 


module CMB_PMOS_2 ( B, DA, DB, DC, S ); 
input B, DA, DB, DC, S;

Switch_PMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 
SCM_PMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .S(S), .DB(DB) ); 

endmodule

module CMB_PMOS_3 ( B, DA, DB, DC, DD, S ); 
input B, DA, DB, DC, DD, S;

Switch_PMOS_n12_X1_Y1 M3 ( .B(B), .D(DD), .G(DA), .S(S) ); 
CMB_PMOS_2 M0_M2_M1 ( .B(B), .DA(DA), .S(S), .DB(DC), .DC(DB) ); 

endmodule

module LSB_NMOS_2 ( B, DA, DB, DC, SA, SB, SC ); 
input B, DA, DB, DC, SA, SB, SC;

Switch_NMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(SC) ); 
LS_NMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .SA(SA), .DB(DB), .SB(SB) ); 

endmodule

module BUFFER_VCM ( vbias, vout, vref ); 
input vbias, vout, vref;

Switch_PMOS_n12_X1_Y1 xm1 ( .B(vdd), .D(vout), .G(net111), .S(vdd) ); 
Cap_5000f c1 ( .PLUS(net107), .MINUS(vout) ); 
Cap_1000f c0 ( .PLUS(gnd), .MINUS(vout) ); 
CMB_PMOS_3 xm29_xm30_xm17_xm3 ( .B(vdd), .DA(vbias), .S(vdd), .DB(net93), .DC(net102), .DD(net019) ); 
SCM_NMOS_n12_X1_Y1 xm23_xm24 ( .B(gnd), .DA(net103), .S(gnd), .DB(net107) ); 
SCM_NMOS_n12_X1_Y1 xm22_xm25 ( .B(gnd), .DA(net99), .S(gnd), .DB(net114) ); 
SCM_NMOS_n12_X1_Y1 xm31_xm0 ( .B(gnd), .DA(net93), .S(gnd), .DB(vout) ); 
SCM_PMOS_n12_X1_Y1 xm33_xm32 ( .B(vdd), .DA(net96), .S(vdd), .DB(net111) ); 
LSB_NMOS_2 xm2_xm27_xm26 ( .B(gnd), .DA(net019), .SA(gnd), .DB(net96), .SB(net114), .DC(net111), .SC(net107) ); 
DP_PMOS_n12_X1_Y1 xm21_xm19 ( .B(net102), .DA(net99), .GA(vref), .S(net102), .DB(net103), .GB(vout) ); 
DP_PMOS_n12_X1_Y1 xm18_xm20 ( .B(net102), .DA(net96), .GA(vout), .S(net102), .DB(net111), .GB(vref) ); 

endmodule

`celldefine
module global_power;
supply0 gnd;
supply1 vdd;
endmodule
`endcelldefine
