//Verilog block level netlist file for COMPARATOR_PRE_AMP
//Generated by UMN for ALIGN project 


module INV_LVT ( SN, SP, i, zn ); 
input SN, SP, i, zn;

Switch_NMOS_n12_X1_Y1 xm0 ( .B(SN), .D(zn), .G(i), .S(SN) ); 
Switch_PMOS_n12_X1_Y1 xm1 ( .B(SP), .D(zn), .G(i), .S(SP) ); 

endmodule

module COMPARATOR_PRE_AMP ( _net0, _net1, clk, crossn, crossp, intern, interp, outm, outp ); 
input _net0, _net1, clk, crossn, crossp, intern, interp, outm, outp;

Dcap_NMOS_n12_X1_Y1 xm0 ( .B(gnd), .S(gnd), .G(intern) ); 
Dcap_NMOS_n12_X1_Y1 xm22 ( .B(gnd), .S(gnd), .G(interp) ); 
Switch_NMOS_n12_X1_Y1 xm7 ( .B(gnd), .D(net050), .G(clk), .S(gnd) ); 
CCP_PMOS_S_n12_X1_Y1 xm13_xm14 ( .B(vdd), .DA(crossp), .DB(crossn), .S(vdd) ); 
CMC_PMOS_S_n12_X1_Y1 xm12_xm10 ( .B(vdd), .DA(crossp), .G(clk), .S(vdd), .DB(crossn) ); 
CMC_PMOS_S_n12_X1_Y1 xm19_xm18 ( .B(vdd), .DA(interp), .G(clk), .S(vdd), .DB(intern) ); 
CCP_NMOS_n12_X1_Y1 xm3_xm4 ( .B(gnd), .DA(crossp), .DB(crossn), .SA(interp), .SB(intern) ); 
INV_LVT xm17_xm15 ( .zn(outp), .i(crossn), .SN(gnd), .SP(vdd) ); 
INV_LVT xm16_xm8 ( .zn(outm), .i(crossp), .SN(gnd), .SP(vdd) ); 
DP_NMOS_n12_X1_Y1 xm6_xm5 ( .B(gnd), .DA(interp), .GA(_net1), .S(net050), .DB(intern), .GB(_net0) ); 

endmodule

`celldefine
module global_power;
supply0 gnd;
supply1 vdd;
endmodule
`endcelldefine
