name: "ALIGN-public pull request build/test workflow"

on:
  pull_request:
    branches:
    - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        container: [['ubuntu-latest', 'manylinux_2_24_x86_64', 'cp38-cp38'], ['ubuntu-latest', 'manylinux2014_x86_64', 'cp38-cp38']]
    runs-on: ${{matrix.container[0]}}
    container: quay.io/pypa/${{matrix.container[1]}}
    steps:
    - name: Checkout
      if: matrix.container[0] == 'ubuntu-latest'
      uses: actions/checkout@v2
      with:
        ref: ${{github.ref}}
    - name: Build wheel
      run: |
        ALIGN_HOME=`pwd`
        bin/build_wheel.sh ${{matrix.container[2]}}
    - name: Test wheel
      run: |
        ALIGN_HOME=`pwd`
        mkdir ${ALIGN_HOME}/work
        ALIGN_WORK_DIR=${rdir}/work
        bin/test_wheel.sh ${{matrix.container[2]}}
