//Verilog block level netlist file for BUFFER_VREFP1
//Generated by UMN for ALIGN project 


module INV_LVT ( SN, SP, i, zn ); 
input SN, SP, i, zn;

Switch_NMOS_n12_X1_Y1 xm0 ( .B(SN), .D(zn), .G(i), .S(SN) ); 
Switch_PMOS_n12_X1_Y1 xm1 ( .B(SP), .D(zn), .G(i), .S(SP) ); 

endmodule

module stage2_inv ( G1, G2, SN, SP ); 
input G1, G2, SN, SP;

INV_LVT MM0_MM2 ( .zn(G1), .i(D), .SN(SN), .SP(SP) ); 
INV_LVT MM1_MM3 ( .zn(D), .i(G2), .SN(SN), .SP(SP) ); 

endmodule

module LSB_NMOS_2 ( B, DA, DB, DC, SA, SB, SC ); 
input B, DA, DB, DC, SA, SB, SC;

Switch_NMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(SC) ); 
LS_NMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .SA(SA), .DB(DB), .SB(SB) ); 

endmodule

module LSB_PMOS_2 ( B, DA, DB, DC, SA, SB, SC ); 
input B, DA, DB, DC, SA, SB, SC;

Switch_PMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(SC) ); 
LS_PMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .SA(SA), .DB(DB), .SB(SB) ); 

endmodule

module BUFFER_VREFP1 ( ibias, sw<0>, sw<1>, sw<2>, vref, vrefp ); 
input ibias, sw<0>, sw<1>, sw<2>, vref, vrefp;

Switch_PMOS_n12_X1_Y1 xm34 ( .B(vdd), .D(vrefp), .G(net459), .S(net0121) ); 
Switch_PMOS_n12_X1_Y1 xm33 ( .B(vdd), .D(vrefp), .G(net459), .S(net0140) ); 
Dcap_PMOS_n12_X1_Y1 xm106 ( .B(vdd), .S(vdd), .G(net078) ); 
DCL_PMOS_n12_X1_Y1 xm27 ( .B(vdd), .D(net078), .S(vfb) ); 
Switch_PMOS_n12_X1_Y1 xm28 ( .B(vdd), .D(vrefp), .G(net459), .S(net0127) ); 
Switch_PMOS_n12_X1_Y1 xm15 ( .B(vdd), .D(vfb), .G(net450), .S(net0138) ); 
Switch_PMOS_n12_X1_Y1 xm58 ( .B(vdd), .D(vrefp), .G(net459), .S(net0125) ); 
Switch_NMOS_n12_X1_Y1 xm21 ( .B(net426), .D(net078), .G(ibias), .S(net426) ); 
Switch_NMOS_n12_X1_Y1 xm5 ( .B(gnd), .D(net410), .G(ibias), .S(net468) ); 
Switch_NMOS_n12_X1_Y1 xm3 ( .B(gnd), .D(net417), .G(ibias), .S(net467) ); 
Switch_NMOS_n12_X1_Y1 xm0 ( .B(gnd), .D(net469), .G(vdd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm2 ( .B(gnd), .D(net468), .G(vdd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm9 ( .B(gnd), .D(net467), .G(vdd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm17 ( .B(gnd), .D(net426), .G(vdd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm18 ( .B(gnd), .D(net470), .G(vdd), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm19 ( .B(gnd), .D(net463), .G(swn0), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm20 ( .B(gnd), .D(net464), .G(swn1), .S(gnd) ); 
Switch_NMOS_n12_X1_Y1 xm55 ( .B(gnd), .D(net465), .G(swn2), .S(gnd) ); 
Switch_PMOS_n12_X1_Y1 xm37 ( .B(vdd), .D(net0132), .G(gnd), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm42 ( .B(vdd), .D(net0138), .G(gnd), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm56 ( .B(vdd), .D(net0125), .G(swp2), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm44 ( .B(vdd), .D(net0127), .G(gnd), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm45 ( .B(vdd), .D(net0140), .G(swp0), .S(vdd) ); 
Switch_PMOS_n12_X1_Y1 xm46 ( .B(vdd), .D(net0121), .G(swp1), .S(vdd) ); 
stage2_inv xm50_xm48_xm49_xm47 ( .G1(swn0), .SN(gnd), .G2(sw<0>), .SP(vdd) ); 
stage2_inv xm54_xm51_xm53_xm52 ( .G1(swn1), .SN(gnd), .G2(sw<1>), .SP(vdd) ); 
stage2_inv xm62_xm59_xm61_xm60 ( .G1(swn2), .SN(gnd), .G2(sw<2>), .SP(vdd) ); 
CMC_NMOS_S_n12_X1_Y1 xm16_xm7 ( .B(gnd), .DA(net471), .G(vdd), .S(gnd), .DB(net466) ); 
CMC_PMOS_S_n12_X1_Y1 xm41_xm38 ( .B(vdd), .DA(net0130), .G(gnd), .S(vdd), .DB(net0126) ); 
CMC_PMOS_S_n12_X1_Y1 xm39_xm40 ( .B(vdd), .DA(net0139), .G(gnd), .S(vdd), .DB(net0134) ); 
CMC_PMOS_S_n12_X1_Y1 xm43_xm35 ( .B(vdd), .DA(net0135), .G(net078), .S(vrefp), .DB(net0116) ); 
CMC_PMOS_S_n12_X1_Y1 xm29_xm32 ( .B(vdd), .DA(net459), .G(net078), .S(vrefp), .DB(net0118) ); 
LSB_NMOS_2 xm4_xm31_xm36 ( .B(gnd), .DA(ibias), .SA(net469), .DB(net0118), .SB(net463), .DC(net0116), .SC(net464) ); 
LSB_PMOS_2 xm22_xm13_xm14 ( .B(vdd), .DA(net410), .SA(net0132), .DB(net450), .SB(net0129), .DC(net411), .SC(net0119) ); 
LS_NMOS_n12_X1_Y1 xm1_xm6 ( .B(gnd), .DA(net411), .SA(net466), .DB(net450), .SB(net471) ); 
LS_PMOS_n12_X1_Y1 xm25_xm26 ( .B(vdd), .DA(net416), .SA(net0134), .DB(net0119), .SB(net0126) ); 
LS_PMOS_n12_X1_Y1 xm23_xm24 ( .B(vdd), .DA(net422), .SA(net0139), .DB(net0129), .SB(net0130) ); 
DP_NMOS_n12_X1_Y1 xm12_xm10 ( .B(gnd), .DA(net450), .GA(vref), .S(net417), .DB(net411), .GB(vfb) ); 
DP_NMOS_n12_X1_Y1 xm8_xm11 ( .B(gnd), .DA(net422), .GA(vfb), .S(net417), .DB(net416), .GB(vref) ); 
CMC_NMOS_n12_X1_Y1 xm30_xm57 ( .B(gnd), .DA(net459), .G(ibias), .SA(net470), .DB(net0135), .SB(net465) ); 

endmodule

`celldefine
module global_power;
supply0 gnd;
supply1 vdd;
endmodule
`endcelldefine
