//Verilog block level netlist file for cascode_current_mirror_ota
//Generated by UMN for ALIGN project 


module CASCODED_CMC_PMOS ( B, DA, DB, GA, S ); 
input B, DA, DB, GA, S;

Switch_PMOS_n12_X5_Y2 M0 ( .B(B), .D(DA), .G(GA), .S(SA) ); 
Switch_PMOS_n12_X5_Y1 M1 ( .B(B), .D(DB), .G(GA), .S(SB) ); 
Switch_PMOS_n12_X1_Y1 M2 ( .B(B), .D(SA), .G(DB), .S(S) ); 
Switch_PMOS_n12_X1_Y1 M3 ( .B(B), .D(SB), .G(DB), .S(S) ); 

endmodule

module CASCODED_CMC_NMOS ( B, DA, DB, GA, S ); 
input B, DA, DB, GA, S;

CMC_NMOS_S_n12_X3_Y1 M3_M2 ( .B(B), .DA(SB), .G(DA), .S(S), .DB(SA) ); 
CMC_NMOS_n12_X2_Y1 M1_M0 ( .B(B), .DA(DB), .G(GA), .SA(SB), .DB(DA), .SB(SA) ); 

endmodule

module cascode_current_mirror_ota ( id, vbiasn, vbiasnd, vbiasp, vinn, vinp, voutp ); 
input id, vbiasn, vbiasnd, vbiasp, vinn, vinp, voutp;

DCL_NMOS_n12_X1_Y1 m1nup ( .B(vss), .D(vbiasn), .S(net9b) ); 
DCL_NMOS_n12_X1_Y1 m1ndown ( .B(vss), .D(net9b), .S(vss) ); 
DCL_PMOS_n12_X1_Y1 m1pup ( .B(vdd), .D(net8b), .S(vdd) ); 
DCL_PMOS_n12_X1_Y1 m1pdown ( .B(vdd), .D(vbiasp), .S(net8b) ); 
CASCODED_CMC_PMOS m23_m27_m18_m19 ( .B(vdd), .DA(voutp), .GA(vbiasp), .DB(net27), .S(vdd) ); 
CASCODED_CMC_PMOS m22_m26_m20_m21 ( .B(vdd), .DA(vbiasnd), .GA(vbiasp), .DB(net16), .S(vdd) ); 
CASCODED_CMC_NMOS m24_m25_m11_m10 ( .B(vss), .DA(vbiasnd), .GA(vbiasn), .DB(voutp), .S(vss) ); 
SCM_NMOS_n12_X2_Y1 m14_m16 ( .B(vss), .DA(id), .S(vss), .DB(net24) ); 
DP_NMOS_n12_X3_Y1 m17_m15 ( .B(vss), .DA(net16), .GA(vinn), .S(net24), .DB(net27), .GB(vinp) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd;
endmodule
`endcelldefine
