#include "PnRdatabase.h"

void PnRdatabase::HardDesignRule() {
  PnRDB::metal_info tmp_metal;
  tmp_metal.name="M1";
  tmp_metal.width=18;
  tmp_metal.dist_ss=18;
  tmp_metal.direct=0;
  tmp_metal.grid_unit_x=128;
  tmp_metal.grid_unit_y=128;
  this->DRC_info.Metal_info.push_back(tmp_metal);
  tmp_metal.name="M2";
  tmp_metal.width=18;
  tmp_metal.dist_ss=18;
  tmp_metal.direct=1;
  tmp_metal.grid_unit_x=128;
  tmp_metal.grid_unit_y=128;
  this->DRC_info.Metal_info.push_back(tmp_metal);
  tmp_metal.name="M3";
  tmp_metal.width=18;
  tmp_metal.dist_ss=18;
  tmp_metal.direct=0;
  tmp_metal.grid_unit_x=128;
  tmp_metal.grid_unit_y=128;
  this->DRC_info.Metal_info.push_back(tmp_metal);
  tmp_metal.name="M4";
  tmp_metal.width=24;
  tmp_metal.dist_ss=24;
  tmp_metal.direct=1;
  tmp_metal.grid_unit_x=360;
  tmp_metal.grid_unit_y=192;
  this->DRC_info.Metal_info.push_back(tmp_metal);
  tmp_metal.name="M5";
  tmp_metal.width=24;
  tmp_metal.dist_ss=24;
  tmp_metal.direct=0;
  tmp_metal.grid_unit_x=192;
  tmp_metal.grid_unit_y=360;
  this->DRC_info.Metal_info.push_back(tmp_metal);
  tmp_metal.name="M6";
  tmp_metal.width=32;
  tmp_metal.dist_ss=32;
  tmp_metal.direct=1;
  tmp_metal.grid_unit_x=360;
  tmp_metal.grid_unit_y=256;
  this->DRC_info.Metal_info.push_back(tmp_metal);
  tmp_metal.name="M7";
  tmp_metal.width=32;
  tmp_metal.dist_ss=32;
  tmp_metal.direct=0;
  tmp_metal.grid_unit_x=256;
  tmp_metal.grid_unit_y=360;
  this->DRC_info.Metal_info.push_back(tmp_metal);

  PnRDB::via_info tmp_via;
  tmp_via.name="V1";
  tmp_via.lower_metal_index=0;
  tmp_via.upper_metal_index=1;
  tmp_via.width=18;
  tmp_via.cover_l=5;
  tmp_via.cover_u=5;
  tmp_via.dist_ss=30;
  this->DRC_info.Via_info.push_back(tmp_via);
  tmp_via.name="V2";
  tmp_via.lower_metal_index=1;
  tmp_via.upper_metal_index=2;
  tmp_via.width=18;
  tmp_via.cover_l=5;
  tmp_via.cover_u=5;
  tmp_via.dist_ss=30;
  this->DRC_info.Via_info.push_back(tmp_via);
  tmp_via.name="V3";
  tmp_via.lower_metal_index=2;
  tmp_via.upper_metal_index=3;
  tmp_via.width=18;
  tmp_via.cover_l=5;
  tmp_via.cover_u=11;
  tmp_via.dist_ss=30;
  this->DRC_info.Via_info.push_back(tmp_via);
  tmp_via.name="V4";
  tmp_via.lower_metal_index=3;
  tmp_via.upper_metal_index=4;
  tmp_via.width=24;
  tmp_via.cover_l=11;
  tmp_via.cover_u=11;
  tmp_via.dist_ss=33;
  this->DRC_info.Via_info.push_back(tmp_via);
  tmp_via.name="V5";
  tmp_via.lower_metal_index=4;
  tmp_via.upper_metal_index=5;
  tmp_via.width=24;
  tmp_via.cover_l=11;
  tmp_via.cover_u=11;
  tmp_via.dist_ss=33;
  this->DRC_info.Via_info.push_back(tmp_via);
  tmp_via.name="V6";
  tmp_via.lower_metal_index=5;
  tmp_via.upper_metal_index=6;
  tmp_via.width=32;
  tmp_via.cover_l=11;
  tmp_via.cover_u=11;
  tmp_via.dist_ss=45;
  this->DRC_info.Via_info.push_back(tmp_via);

  PnRDB::ViaModel tmp_vm; std::vector<PnRDB::point> tmp_pv; PnRDB::point tmp_p;
  tmp_vm.name="V1";
  tmp_vm.ViaIdx=0;
  tmp_vm.LowerIdx=0;
  tmp_vm.UpperIdx=1;
  tmp_pv.clear();
  tmp_p.x=-9; tmp_p.y=-9;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=9; tmp_p.y=9;
  tmp_pv.push_back(tmp_p);
  tmp_vm.ViaRect=tmp_pv;
  tmp_pv.clear();
  tmp_p.x=-9; tmp_p.y=-14;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=9; tmp_p.y=14;
  tmp_pv.push_back(tmp_p);
  tmp_vm.LowerRect=tmp_pv;
  tmp_pv.clear();
  tmp_p.x=-14; tmp_p.y=-9;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=14; tmp_p.y=9;
  tmp_pv.push_back(tmp_p);
  tmp_vm.UpperRect=tmp_pv;
  this->DRC_info.Via_model.push_back(tmp_vm);
  tmp_vm.name="V2";
  tmp_vm.ViaIdx=1;
  tmp_vm.LowerIdx=1;
  tmp_vm.UpperIdx=2;
  tmp_pv.clear();
  tmp_p.x=-9; tmp_p.y=-9;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=9; tmp_p.y=9;
  tmp_pv.push_back(tmp_p);
  tmp_vm.ViaRect=tmp_pv;
  tmp_pv.clear();
  tmp_p.x=-14; tmp_p.y=-9;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=14; tmp_p.y=9;
  tmp_pv.push_back(tmp_p);
  tmp_vm.LowerRect=tmp_pv;
  tmp_pv.clear();
  tmp_p.x=-9; tmp_p.y=-14;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=9; tmp_p.y=14;
  tmp_pv.push_back(tmp_p);
  tmp_vm.UpperRect=tmp_pv;
  this->DRC_info.Via_model.push_back(tmp_vm);
  tmp_vm.name="V3";
  tmp_vm.ViaIdx=2;
  tmp_vm.LowerIdx=2;
  tmp_vm.UpperIdx=3;
  tmp_pv.clear();
  tmp_p.x=-9; tmp_p.y=-9;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=9; tmp_p.y=9;
  tmp_pv.push_back(tmp_p);
  tmp_vm.ViaRect=tmp_pv;
  tmp_pv.clear();
  tmp_p.x=-9; tmp_p.y=-14;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=9; tmp_p.y=14;
  tmp_pv.push_back(tmp_p);
  tmp_vm.LowerRect=tmp_pv;
  tmp_pv.clear();
  tmp_p.x=-23; tmp_p.y=-12;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=23; tmp_p.y=12;
  tmp_pv.push_back(tmp_p);
  tmp_vm.UpperRect=tmp_pv;
  this->DRC_info.Via_model.push_back(tmp_vm);
  tmp_vm.name="V4";
  tmp_vm.ViaIdx=3;
  tmp_vm.LowerIdx=3;
  tmp_vm.UpperIdx=4;
  tmp_pv.clear();
  tmp_p.x=-12; tmp_p.y=-12;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=12; tmp_p.y=12;
  tmp_pv.push_back(tmp_p);
  tmp_vm.ViaRect=tmp_pv;
  tmp_pv.clear();
  tmp_p.x=-23; tmp_p.y=-12;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=23; tmp_p.y=12;
  tmp_pv.push_back(tmp_p);
  tmp_vm.LowerRect=tmp_pv;
  tmp_pv.clear();
  tmp_p.x=-12; tmp_p.y=-23;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=12; tmp_p.y=23;
  tmp_pv.push_back(tmp_p);
  tmp_vm.UpperRect=tmp_pv;
  this->DRC_info.Via_model.push_back(tmp_vm);
  tmp_vm.name="V5";
  tmp_vm.ViaIdx=4;
  tmp_vm.LowerIdx=4;
  tmp_vm.UpperIdx=5;
  tmp_pv.clear();
  tmp_p.x=-12; tmp_p.y=-12;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=12; tmp_p.y=12;
  tmp_pv.push_back(tmp_p);
  tmp_vm.ViaRect=tmp_pv;
  tmp_pv.clear();
  tmp_p.x=-12; tmp_p.y=-23;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=12; tmp_p.y=23;
  tmp_pv.push_back(tmp_p);
  tmp_vm.LowerRect=tmp_pv;
  tmp_pv.clear();
  tmp_p.x=-27; tmp_p.y=-16;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=27; tmp_p.y=16;
  tmp_pv.push_back(tmp_p);
  tmp_vm.UpperRect=tmp_pv;
  this->DRC_info.Via_model.push_back(tmp_vm);
  tmp_vm.name="V6";
  tmp_vm.ViaIdx=5;
  tmp_vm.LowerIdx=5;
  tmp_vm.UpperIdx=6;
  tmp_pv.clear();
  tmp_p.x=-16; tmp_p.y=-16;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=16; tmp_p.y=16;
  tmp_pv.push_back(tmp_p);
  tmp_vm.ViaRect=tmp_pv;
  tmp_pv.clear();
  tmp_p.x=-27; tmp_p.y=-16;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=27; tmp_p.y=16;
  tmp_pv.push_back(tmp_p);
  tmp_vm.LowerRect=tmp_pv;
  tmp_pv.clear();
  tmp_p.x=-16; tmp_p.y=-27;
  tmp_pv.push_back(tmp_p);
  tmp_p.x=16; tmp_p.y=27;
  tmp_pv.push_back(tmp_p);
  tmp_vm.UpperRect=tmp_pv;
  this->DRC_info.Via_model.push_back(tmp_vm);

  this->DRC_info.Metalmap["M1"]=0;
  this->DRC_info.Metalmap["M2"]=1;
  this->DRC_info.Metalmap["M3"]=2;
  this->DRC_info.Metalmap["M4"]=3;
  this->DRC_info.Metalmap["M5"]=4;
  this->DRC_info.Metalmap["M6"]=5;
  this->DRC_info.Metalmap["M7"]=6;

  this->DRC_info.Viamap["V1"]=0;
  this->DRC_info.Viamap["V2"]=1;
  this->DRC_info.Viamap["V3"]=2;
  this->DRC_info.Viamap["V4"]=3;
  this->DRC_info.Viamap["V5"]=4;
  this->DRC_info.Viamap["V6"]=5;

  this->DRC_info.metal_weight.resize(7,1);

  this->DRC_info.MaskID_Metal.push_back("19");
  this->DRC_info.MaskID_Metal.push_back("20");
  this->DRC_info.MaskID_Metal.push_back("30");
  this->DRC_info.MaskID_Metal.push_back("40");
  this->DRC_info.MaskID_Metal.push_back("50");
  this->DRC_info.MaskID_Metal.push_back("60");
  this->DRC_info.MaskID_Metal.push_back("70");
  this->DRC_info.MaskID_Via.push_back("21");
  this->DRC_info.MaskID_Via.push_back("25");
  this->DRC_info.MaskID_Via.push_back("35");
  this->DRC_info.MaskID_Via.push_back("45");
  this->DRC_info.MaskID_Via.push_back("55");
  this->DRC_info.MaskID_Via.push_back("65");
  this->DRC_info.MaskID_Via.push_back("75");
}
