//Verilog block level netlist file for cascode_current_mirror_ota
//Generated by UMN for ALIGN project 


module cascode_current_mirror_ota ( vout, vss, id, vdd, vinn, vinp ); 
input vout, vss, id, vdd, vinn, vinp;

Switch_NMOS_n12_X4_Y4 m1 ( .D(net2), .G(vinp), .S(net1), .BG(vss) ); 
DCL_NMOS_n12_X3_Y1 m10 ( .D(id), .S(vss), .BG(vss) ); 
Switch_NMOS_n12_X4_Y4 m2 ( .D(vout), .G(vinn), .S(net1), .BG(vss) ); 
DCL_PMOS_n12_X5_Y2 m5 ( .D(net2), .S(net3), .BG(vdd) ); 
Switch_PMOS_n12_X5_Y2 m6 ( .D(vout), .G(net2), .S(net4), .BG(vdd) ); 
DCL_PMOS_n12_X5_Y2 m7 ( .D(net3), .S(vdd), .BG(vdd) ); 
Switch_PMOS_n12_X5_Y2 m8 ( .D(net4), .G(net3), .S(vdd), .BG(vdd) ); 
Switch_NMOS_n12_X2_Y2 m9 ( .D(net1), .G(id), .S(vss), .BG(vss) ); 

endmodule
