//Verilog block level netlist file for buffer
//Generated by UMN for ALIGN project 


module buffer ( vin, vout ); 
input vin, vout;

Switch_PMOS_nfin12_n12_X1_Y1 mp1 ( .D(vxx), .G(vin), .S(vdd) ); 
Switch_NMOS_nfin12_n12_X1_Y1 mn1 ( .D(vxx), .G(vin), .S(vss) ); 
Switch_PMOS_nfin24_n12_X2_Y1 mp2 ( .D(vout), .G(vxx), .S(vdd) ); 
Switch_NMOS_nfin48_n12_X2_Y2 mn2 ( .D(vout), .G(vxx), .S(vss) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd;
endmodule
`endcelldefine
