//Verilog block level netlist file for single_to_differential_converter
//Generated by UMN for ALIGN project 


module single_to_differential_converter ( vb, vin, vout_sdc1, vout_sdc2 ); 
input vb, vin, vout_sdc1, vout_sdc2;

Switch_NMOS_n12_X2_Y1 xI0|MN0 ( .B(b), .D(vd), .G(net1), .S(vs) ); 
Res_20000 R2 ( .PLUS(net1), .MINUS(vb) ); 
Res_900 R1 ( .PLUS(vgnd), .MINUS(vs) ); 
Res_900 R0 ( .PLUS(vd), .MINUS(vps) ); 
Cap_12f C2 ( .PLUS(vout_sdc2), .MINUS(vs) ); 
Cap_12f C1 ( .PLUS(vd), .MINUS(vout_sdc1) ); 
Cap_48f C0 ( .PLUS(net1), .MINUS(vin) ); 

endmodule

`celldefine
module global_power;
supply0 vgnd;
supply1 vps;
endmodule
`endcelldefine
