//Verilog block level netlist file for Sanitized_Coarse_Comp_CK
//Generated by UMN for ALIGN project 


module Sanitized_Coarse_Comp_CK ( CKC, CKSBT, OUTNC, OUTPC, ST_FINE, VALIDC, VCTIN ); 
input CKC, CKSBT, OUTNC, OUTPC, ST_FINE, VALIDC, VCTIN;

PINVD0YVT XI67 ( .I(net07), .P(VCTIN), .VDD(DVDD), .VSS(DVSS), .ZN(net09) ); 
PINVD0YVT XI46 ( .I(net30), .P(VCTIN), .VDD(DVDD), .VSS(DVSS), .ZN(net29) ); 
PINVD0YVT XI21 ( .I(net33), .P(VCTIN), .VDD(DVDD), .VSS(DVSS), .ZN(net32) ); 
PINVD0YVT XI12 ( .I(net34), .P(VCTIN), .VDD(DVDD), .VSS(DVSS), .ZN(net33) ); 
PINVD0YVT XI47 ( .I(net31), .P(VCTIN), .VDD(DVDD), .VSS(DVSS), .ZN(net30) ); 
INVD0HVT XI0 ( .I(net29), .ZN(net07), .VDD(DVDD), .VSS(DVSS) ); 
INVD0HVT XI22 ( .I(net32), .ZN(net31), .VDD(DVDD), .VSS(DVSS) ); 
ND2D3LVT XI3 ( .A1(OUTNC), .A2(OUTPC), .ZN(VALIDC), .VDD(DVDD), .VSS(DVSS) ); 
NR3D1LVT XI218 ( .A1(VALIDC), .A2(ST_FINE), .A3(CKSBT), .ZN(net34), .VDD(DVDD), .VSS(DVSS) ); 
INVD2LVT XI65 ( .I(net09), .ZN(CKC), .VDD(DVDD), .VSS(DVSS) ); 

endmodule

module PINVD0YVT ( I, P, VDD, VSS, ZN ); 
input I, P, VDD, VSS, ZN;

Switch_NMOS_n12_X1_Y1 MM4 ( .B(VSS), .D(ZN), .G(I), .S(net11) ); 
Switch_NMOS_n12_X1_Y1 MM1 ( .B(VSS), .D(net11), .G(P), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MM3 ( .B(VDD), .D(net09), .G(VSS), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MM0 ( .B(VDD), .D(ZN), .G(I), .S(net09) ); 

endmodule

module INVD0HVT ( I, VDD, VSS, ZN ); 
input I, VDD, VSS, ZN;

Switch_NMOS_n12_X1_Y1 MMU1_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU1_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 

endmodule

module ND2D3LVT ( A1, A2, VDD, VSS, ZN ); 
input A1, A2, VDD, VSS, ZN;

Switch_NMOS_n12_X1_Y1 MMU3_1_M_u3 ( .B(VSS), .D(ZN), .G(A1), .S(net20) ); 
Switch_NMOS_n12_X1_Y1 MMU3_2_M_u4 ( .B(VSS), .D(net13), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMU3_0_M_u3 ( .B(VSS), .D(ZN), .G(A1), .S(net21) ); 
Switch_NMOS_n12_X1_Y1 MMU3_2_M_u3 ( .B(VSS), .D(ZN), .G(A1), .S(net13) ); 
Switch_PMOS_n12_X1_Y1 MMU3_2_M_u1 ( .B(VDD), .D(ZN), .G(A1), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU3_1_M_u2 ( .B(VDD), .D(ZN), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU3_0_M_u2 ( .B(VDD), .D(ZN), .G(A2), .S(VDD) ); 
Switch_PMOS_n12_X1_Y1 MMU3_0_M_u1 ( .B(VDD), .D(ZN), .G(A1), .S(VDD) ); 
CMC_NMOS_S_n12_X1_Y1 MMU3_1_M_u4_MMU3_0_M_u4 ( .B(VSS), .DA(net20), .G(A2), .S(VSS), .DB(net21) ); 

endmodule

module NR3D1LVT ( A1, A2, A3, VDD, VSS, ZN ); 
input A1, A2, A3, VDD, VSS, ZN;

Switch_PMOS_n12_X1_Y1 MMI1_1 ( .B(VDD), .D(ZN), .G(A1), .S(net5) ); 
Switch_PMOS_n12_X1_Y1 MMI1_0 ( .B(VDD), .D(ZN), .G(A1), .S(net9) ); 
Switch_NMOS_n12_X1_Y1 MMI3 ( .B(VSS), .D(ZN), .G(A1), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MMI2 ( .B(VSS), .D(ZN), .G(A2), .S(VSS) ); 
Switch_NMOS_n12_X1_Y1 MM_u4 ( .B(VSS), .D(ZN), .G(A3), .S(VSS) ); 
CMC_PMOS_S_n12_X1_Y1 MM_u1_1_MM_u1_0 ( .B(VDD), .DA(net1), .G(A3), .S(VDD), .DB(net17) ); 
CMC_PMOS_n12_X1_Y1 MMI0_1_MMI0_0 ( .B(VDD), .DA(net5), .G(A2), .SA(net1), .DB(net9), .SB(net17) ); 

endmodule

module INVD2LVT ( I, VDD, VSS, ZN ); 
input I, VDD, VSS, ZN;

Switch_NMOS_n12_X1_Y1 MMU1_0_M_u2 ( .B(VSS), .D(ZN), .G(I), .S(VSS) ); 
Switch_PMOS_n12_X1_Y1 MMU1_0_M_u3 ( .B(VDD), .D(ZN), .G(I), .S(VDD) ); 

endmodule

`celldefine
module global_power;
supply0 DVSS;
supply1 DVDD;
endmodule
`endcelldefine
