//Verilog block level netlist file for current_mirror_ota
//Generated by UMN for ALIGN project 


module current_mirror_ota ( id, vout, vss, vinp, vdd, vinn ); 
input id, vout, vss, vinp, vdd, vinn;

Switch_NMOS_n12_X2_Y1 m10 ( .D(vout), .G(vbiasnd), .S(vss), .BG(vss) ); 
DCL_NMOS_n12_X2_Y1 m11 ( .D(vbiasnd), .S(vss), .BG(vss) ); 
DCL_NMOS_n12_X1_Y1 m14 ( .D(id), .S(vss), .BG(vss) ); 
Switch_NMOS_n12_X2_Y1 m15 ( .D(net27), .G(vinp), .S(net24), .BG(vss) ); 
Switch_NMOS_n12_X1_Y1 m16 ( .D(net24), .G(id), .S(vss), .BG(vss) ); 
Switch_NMOS_n12_X2_Y1 m17 ( .D(net16), .G(vinn), .S(net24), .BG(vss) ); 
Switch_PMOS_n12_X5_Y2 m18 ( .D(vout), .G(net27), .S(vdd), .BG(vdd) ); 
DCL_PMOS_n12_X5_Y1 m19 ( .D(net27), .S(vdd), .BG(vdd) ); 
Switch_PMOS_n12_X5_Y2 m20 ( .D(vbiasnd), .G(net16), .S(vdd), .BG(vdd) ); 
DCL_PMOS_n12_X5_Y1 m21 ( .D(net16), .S(vdd), .BG(vdd) ); 

endmodule
