//Verilog block level netlist file for cascode_current_mirror_ota
//Generated by UMN for ALIGN project 


module CASCODED_CMC_PMOS ( DA, GA, DB, S ); 
input DA, GA, DB, S;

CMC_PMOS_S_n12_X1_Y1 M2_M3 ( .DA(SA), .G(DB), .DB(SB), .S(S) ); 
CMC_PMOS_n12_X5_Y2 M0_M1 ( .DA(DA), .G(GA), .DB(DB), .SA(SA), .SB(SB) ); 

endmodule

module CASCODED_CMC_NMOS ( DA, GA, DB, S ); 
input DA, GA, DB, S;

CMC_NMOS_S_n12_X3_Y1 M2_M3 ( .DA(SA), .G(DA), .DB(SB), .S(S) ); 
CMC_NMOS_n12_X2_Y1 M0_M1 ( .DA(DA), .G(GA), .DB(DB), .SA(SA), .SB(SB) ); 

endmodule

module cascode_current_mirror_ota ( vss, vbiasnd, voutp, vbiasp, vinn, vinp, vdd, id, vbiasn ); 
input vss, vbiasnd, voutp, vbiasp, vinn, vinp, vdd, id, vbiasn;

DCL_NMOS_n12_X1_Y1 m1ndown ( .D(net9b), .S(vss) ); 
DCL_NMOS_n12_X1_Y1 m1nup ( .D(vbiasn), .S(net9b) ); 
DCL_PMOS_n12_X1_Y1 m1pdown ( .D(vbiasp), .S(net8b) ); 
DCL_PMOS_n12_X1_Y1 m1pup ( .D(net8b), .S(vdd) ); 
CASCODED_CMC_PMOS m22_m26_m20_m21 ( .DA(vbiasnd), .GA(vbiasp), .DB(net16), .S(vdd) ); 
CASCODED_CMC_PMOS m23_m27_m18_m19 ( .DA(voutp), .GA(vbiasp), .DB(net27), .S(vdd) ); 
CASCODED_CMC_NMOS m24_m25_m11_m10 ( .DA(vbiasnd), .GA(vbiasn), .DB(voutp), .S(vss) ); 
SCM_NMOS_n12_X2_Y1 m14_m16 ( .DA(id), .DB(net24), .S(vss) ); 
DP_NMOS_n12_X3_Y1 m17_m15 ( .DA(net16), .GA(vinn), .S(net24), .DB(net27), .GB(vinp) ); 

endmodule
