//Verilog block level netlist file for five_transistor_ota
//Generated by UMN for ALIGN project 


module five_transistor_ota ( id, vinn, vinp, vout ); 
input id, vinn, vinp, vout;

SCM_NMOS_n12_X1_Y1 m5_m4 ( .B(vss), .DA(id), .S(vss), .DB(net10) ); 
SCM_PMOS_n12_X1_Y1 m1_m2 ( .B(vdd), .DA(net8), .S(vdd), .DB(vout) ); 
DP_NMOS_n12_X1_Y1 m3_m0 ( .B(vss), .DA(vout), .GA(vinn), .S(net10), .DB(net8), .GB(vinp) ); 

endmodule

`celldefine
module global_power;
supply0 vss;
supply1 vdd;
endmodule
`endcelldefine
