//Verilog block level netlist file for BUFFER_VCM_FINAL
//Generated by UMN for ALIGN project 


module CMB_NMOS_2 ( B, DA, DB, DC, S ); 
input B, DA, DB, DC, S;

Switch_NMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 
SCM_NMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .S(S), .DB(DB) ); 

endmodule

module CMB_NMOS_3 ( B, DA, DB, DC, DD, S ); 
input B, DA, DB, DC, DD, S;

Switch_NMOS_n12_X1_Y1 M3 ( .B(B), .D(DD), .G(DA), .S(S) ); 
CMB_NMOS_2 M0_M2_M1 ( .B(B), .DA(DA), .S(S), .DB(DC), .DC(DB) ); 

endmodule

module CMB_NMOS_4 ( B, DA, DB, DC, DD, DE, S ); 
input B, DA, DB, DC, DD, DE, S;

Switch_NMOS_n12_X1_Y1 M4 ( .B(B), .D(DE), .G(DA), .S(S) ); 
CMB_NMOS_3 M0_M3_M2_M1 ( .B(B), .DA(DA), .S(S), .DB(DD), .DC(DC), .DD(DB) ); 

endmodule

module CASCODED_SCM_PMOS ( B, DA, DC, GA, S ); 
input B, DA, DC, GA, S;

Switch_PMOS_n12_X1_Y1 M0 ( .B(B), .D(DA), .G(GA), .S(DB) ); 
Switch_PMOS_n12_X1_Y1 M1 ( .B(B), .D(DB), .G(DA), .S(S) ); 
Switch_PMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 

endmodule

module CASCODED_CMC_PMOS ( B, DA, DB, GA, S ); 
input B, DA, DB, GA, S;

Switch_PMOS_n12_X1_Y1 M0 ( .B(B), .D(DA), .G(GA), .S(SA) ); 
CASCODED_SCM_PMOS M1_M3_M2 ( .B(B), .DA(DB), .GA(GA), .S(S), .DC(SA) ); 

endmodule

module CMB_PMOS_2 ( B, DA, DB, DC, S ); 
input B, DA, DB, DC, S;

Switch_PMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(S) ); 
SCM_PMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .S(S), .DB(DB) ); 

endmodule

module CMB_PMOS_3 ( B, DA, DB, DC, DD, S ); 
input B, DA, DB, DC, DD, S;

Switch_PMOS_n12_X1_Y1 M3 ( .B(B), .D(DD), .G(DA), .S(S) ); 
CMB_PMOS_2 M0_M2_M1 ( .B(B), .DA(DA), .S(S), .DB(DC), .DC(DB) ); 

endmodule

module LSB_NMOS_2 ( B, DA, DB, DC, SA, SB, SC ); 
input B, DA, DB, DC, SA, SB, SC;

Switch_NMOS_n12_X1_Y1 M2 ( .B(B), .D(DC), .G(DA), .S(SC) ); 
LS_NMOS_n12_X1_Y1 M0_M1 ( .B(B), .DA(DA), .SA(SA), .DB(DB), .SB(SB) ); 

endmodule

module BUFFER_VCM_FINAL ( ibias, vcm_in, vout ); 
input ibias, vcm_in, vout;

Dcap_PMOS_n12_X1_Y1 xm10 ( .B(vout), .S(vout), .G(net065) ); 
Switch_PMOS_n12_X1_Y1 xm1 ( .B(vdd), .D(vout), .G(net138), .S(vdd) ); 
DCL_PMOS_n12_X1_Y1 xm7 ( .B(vdd), .D(net122), .S(vdd) ); 
CMB_NMOS_4 xm31_xm0_xm25_xm6_xm24 ( .B(gnd), .DA(net132), .S(gnd), .DB(vout), .DC(net125), .DD(net122), .DE(net065) ); 
CASCODED_CMC_PMOS xm4_xm5_xm32_xm33 ( .B(vdd), .DA(net138), .GA(net122), .DB(net128), .S(vdd) ); 
CMB_PMOS_3 xm29_xm17_xm30_xm3 ( .B(vdd), .DA(ibias), .S(vdd), .DB(net133), .DC(net132), .DD(net123) ); 
LSB_NMOS_2 xm2_xm27_xm26 ( .B(gnd), .DA(net123), .SA(gnd), .DB(net128), .SB(net125), .DC(net138), .SC(net065) ); 
DP_PMOS_n12_X1_Y1 xm21_xm19 ( .B(net133), .DA(net125), .GA(vout), .S(net133), .DB(net065), .GB(vcm_in) ); 

endmodule

`celldefine
module global_power;
supply0 gnd;
supply1 vdd;
endmodule
`endcelldefine
